### ISSUE TITLE
[Bug] Bell bearings that I offered doesn't save

### ISSUE THREAD

**Issue by justn1** [LukeYui/EldenRingSeamlessCoopRelease#10]
Got bell bearings as a cooperative player, when I later joined the session with the same host and I went to the Twin Maiden Husks, all the shops that I got from the bell bearings as well as the smithing stones were gone. 

Edit: A recommendation I have for this is that when any player offers a bell bearing is that it's synchronized for all players (saved on the host). and that when new players join a host game, all of the host's bell bearings and stuff like that is sent to the new client.

**Comment by Andethir** [comment]
Going to add an addendum to this as its not just bell bearings but also Spell tomes to spell teachers as well. 

From what i have seen however all the items are available when playing solo. Its solely when joining another player as a client. Perhaps its not detecting the flags for the client for shop inventories?

**Comment by Corosar** [comment]
You already figured this one out? My god I swear your doing some sort of dark ritual with this mod sometimes. I will keep my eyes out for anything else we run into in our runthrough.
