### ISSUE TITLE
[Bug]: Infinite Loading Loop on Roundtable Hold

### ISSUE THREAD

**Issue by OneWhoLepps** [LukeYui/EldenRingSeamlessCoopRelease#100]
### Discord Username

OneWhoLepps#6794

### Describe the issue in detail

After losing to Margit (who was actually Rykard since we were using a randomizer mod), my buddy talked to malenia. I got kicked from the world, so I went to talk to malena & get the same dialogs.

After the malenia dialog that leads to the roundtable hold, my game is now permanently stuck in a loop of loading from 0-100, the screen flashes black then grey, then another loading screen appears. This loop does not stop. Rebooting the game does not fix the issue.

### Steps to recreate the bug

Install https://www.nexusmods.com/eldenring/mods/428 (randomizer mod)

Install seamless coop mod

Get to Margit, have the host player die. At this point, I was kicked out.

In your world, talk to malenia about the roundtable hold.

Enter infinite loading loop after the malenia dialog & anytime trying to continue the save afterwards.

### Version

1.2.1 (Latest)

**Comment by gunkman230** [comment]
Also dealing with this issue, was having a blast until this locked me out of the game. Still stuck the next day.

**Comment by Nordgaren** [comment]
Hello!

Can you try to set this flag ID with Debug Tool? `105`

Just download the tool, unzip it anywhere, run it while you are in game on your character. Go to misc tab and type in 105 and hit enable and see if that fixes this issue?

https://github.com/Nordgaren/Elden-Ring-Debug-Tool/releases/tag/0.8.1

Let me know what happens! Thanks!

**Comment by OneWhoLepps** [comment]
Issue has been closed! @Nordgaren 's comment on setting flag 105 whilst in the load menu to my game worked like a charm!
