### ISSUE TITLE
[Bug]: game crashes

### ISSUE THREAD

**Issue by 404streamernotfound** [LukeYui/EldenRingSeamlessCoopRelease#102]
### Discord Username

404_streamernotfound#5904

### Describe the issue in detail

The game always crashes for one person of my team when we fight rennala and it starts her second phase. it happens every time and only for the same person. (sorry the log is in german, i hope this still helps)

### Steps to recreate the bug

go beat phase 1 of rennala and "enter" phase 2

### Version

1.2.1 (Latest)

### Relevant Crash log

```shell
Name der fehlerhaften Anwendung: eldenring.exe, Version: 1.4.1.0, Zeitstempel: 0x625fce14
Name des fehlerhaften Moduls: eldenring.exe, Version: 1.4.1.0, Zeitstempel: 0x625fce14
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000001e54f34
ID des fehlerhaften Prozesses: 0x3350
Startzeit der fehlerhaften Anwendung: 0x01d87cff9f1b9db1
Pfad der fehlerhaften Anwendung: E:\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Pfad des fehlerhaften Moduls: E:\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Berichtskennung: 36b82ec8-dfde-4bdb-abdb-0dc94c444ac6
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:
```

**Comment by LukeYui** [comment]
This is a bug with the base game.

Try verifying your game with Steam using "Verify integrity of Game Files". This usually fixes the issue.
