### ISSUE TITLE
[Bug]: Stationary/invisible Wanderer on horseback.

### ISSUE THREAD

**Issue by dystopia7** [LukeYui/EldenRingSeamlessCoopRelease#106]
### Discord Username

Jimmy Rustle#8442

### Describe the issue in detail

I was playing with an additional player and we would experience the host being stationary when they rode around on their horse seemingly at random at first. However, you could tell where they were going (as they were invisible - model was stationary where they mounted) due to a constantly flickering HP bar/name in the direction where they were going. When dismounted they appear at their new location. This was pretty easily fixed by resetting the game to the main menu. At some point in Liurnia though, this would occur on a fresh game load to the joined person (not the host) and no amount of resetting would fix it.  

### Steps to recreate the bug

Seemed random at first in Liurnia but at some point near the Academy it would happen on a fresh save game load. This occured at the end of our play session last night - will get more details and video of the bug some time later today.

### Version

1.2.1 (Latest)

**Comment by BTSpaniel** [comment]
Can Confirm this, Downgrading to 1.2.0 does fix it.
Also to note the spectating bug in 1.2.1 is still broken.

**Comment by alvarotuso** [comment]
Confirmed here as well, downgrading to 1.2.0 fixed it

**Comment by DynamicMountain** [comment]
Also noticing this from 1.2.1, when we didn't have the issue in 1.2.0
