### ISSUE TITLE
[Bug]: Flask upgrade resets

### ISSUE THREAD

**Issue by Copperhead48** [LukeYui/EldenRingSeamlessCoopRelease#109]
### Discord Username

Copperhead48#6329

### Describe the issue in detail

I rebirthed myself with rennala and it reset my sacred tear charges back down to +1 from +11 and i cant get them back. We were right before going to farum azula.

### Steps to recreate the bug

Get rebirthed by rennala i guess

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment]
Duplicate of #58
