### ISSUE TITLE
Rennala Second Phase Crash As Cooperator

### ISSUE THREAD

**Issue by justn1** [LukeYui/EldenRingSeamlessCoopRelease#11]
My friend was the host, we defeated rennala's first phase, everytime the cutscene triggers to go into the second phase my game crashes but my friend's game is fine.

**Comment by Alphaz0r** [comment]
I think this could be related to the host having a cutscene. I had the same behaviour when Melina gives you the Torrent's whistle

**Comment by LukeYui** [comment]
Hi, sorry for the delay. This is more often than not a problem with the base game, try re-verifying your game files with Steam. This should fix the crashing.
