### ISSUE TITLE
[Bug]: Horse glitch

### ISSUE THREAD

**Issue by Kepfa** [LukeYui/EldenRingSeamlessCoopRelease#111]
### Discord Username

Kepfa#4879

### Describe the issue in detail

when me and my friends hop on our horses we all experience different kind of glitches like sometimes you'll see one or more person with an invisible horse, or on your screen they wont be moving, like they are just standing in place but for them theyre moving and/or sometimes when we hop on horses we wont be able to see the other real players at all, we can only see them if they get off the horse. theres times when we will hop on a horse near an enemy and run away but somehow will still be getting hit from them and we fix it by getting off the horse then back on but yeah.

### Steps to recreate the bug

getting on our horse? and by the way for the version this glitch has been happening in, its been since it came out but it doesnt let me choose all so i chose latest version. 

### Version

1.2.1 (Latest)

**Comment by Kepfa** [comment]
anytime my game crashes, i dont get crash logs so i cant send you that sorry

**Comment by DynamicMountain** [comment]
I'm also seeing this bug with the horse, but its consistent. It appears to happen when any non host gets on a horse, keeping that player in the same space in the hosts world, but moving them to their actual location when they dismount. You can see glances of the other players health bar as they move, but they are otherwise invisible.

Note that this is only happening since we updated from 1.2.0 to 1.2.1

**Comment by musaha13** [comment]
Same only happened after updating from 1.2.0 to 1.2.1

**Comment by davidonabus** [comment]
I see this consistently as well. It began in 1.2.1

**Comment by insanemhelo** [comment]
I noticed this bug a few times before the 1.2.1 update but it happened very very very rarely and didnt happen long.  After 1.2.1 we see it all the time.  We have had to do areas on foot just so we could stay together.

**Comment by C-atmaca** [comment]
When me and/or my friend hop on our horses they are just standing in place but we can see each others name tags moving. The models stay in place while all the horse animations play.
