### ISSUE TITLE
[Bug]: Margit, the Fell Omen's health regains after wanderer dies

### ISSUE THREAD

**Issue by Ed-boye** [LukeYui/EldenRingSeamlessCoopRelease#112]
### Discord Username

Ed_boye#0069

### Describe the issue in detail

When fighting Margit after I died as a wanderer and the host was left alive, Margit suddenly regened a large portion of their health.

### Steps to recreate the bug

2 player co-op
Fight Margit (probably we were fighting at least 1 minute)
Wanderer dies
Margit gets health back

### Version

1.2.1 (Latest)

**Comment by Ed-boye** [comment]
Seemed to happen again after Rogier died with the two of us.

**Comment by LukeYui** [comment]
Duplicate of #54
