### ISSUE TITLE
[Bug]: End Game bosses don't react properly to party death

### ISSUE THREAD

**Issue by NoNutNed** [LukeYui/EldenRingSeamlessCoopRelease#113]
### Discord Username

nonutned#7460

### Describe the issue in detail

(This was all done with two players)
This one has a few issues. The mod worked very well for a good majority of the game, and we were able to complete a full playthrough from start to elden beast. However, Fire Giant, Beast Clergyman and Radagon/Elden Beast gave us some weird bugs. 

1. Fire Giant. Dying to him once he is in second phase (when his ankle breaks) caused a peculiar issue. Once we died, the game had put us back in the boss arena with a full health fire giant, but he was in second phase. To work around it, we had to close the session and quit to menu.
2. Beast Clergyman. Similar to above. Once we died to him, it would sometimes spawn us in his boss arena and when it did, he either wasn't there or would only be visible to one player. He would also be in a full health second phase sometimes. Probably depending on when we died to him
3. Godfrey, we didn't die to him, but something similar may happen.
4. Radagon. We didn't die to Radagon, but we did the Elden Beast. It would spawn us in at the Godfrey bonfire properly, but the elden beast's boss bar would be on screen. Then, when we entered Radagon's boss fog, he would only target one of us.

### Steps to recreate the bug

Simply dying to these bosses when they are in their second phase.

### Version

1.2.0

**Comment by pu1i** [comment]
In the godfrey fight if somebody dies in phase 1 he will bug almost the same way as the Fire Giant, and when you get him alone in phase 2 he goes down through the map not being able to kill him or kill yourself, so you need to leave the game or find a way to kill yourself
