### ISSUE TITLE
[Bug]: Finger Reader in Roundtable was floating after Godrick and After Rennala she dissapeared

### ISSUE THREAD

**Issue by Saltandpepper123** [LukeYui/EldenRingSeamlessCoopRelease#114]
### Discord Username

babyblender#1269

### Describe the issue in detail

Me and my friend went to get our remembrance items and she was gone. I think she floated away or something. The fingers had also gone straight, as if I was in endgame. Which we are not. We just killed Rennala.

### Steps to recreate the bug

Kill Godrick and Rennala in coop and the Finger reader will float away. Or dissapear, I don't know what happened.

### Version

1.2.1 (Latest)

**Comment by TheRealSagittarius** [comment]
Happened to me too.
