### ISSUE TITLE
[Bug]: Night's cavelry boss fight, horse does not despawn even after boss is defeated

### ISSUE THREAD

**Issue by Myheartdies** [LukeYui/EldenRingSeamlessCoopRelease#117]
### Discord Username

Neil_Yu#0939

### Describe the issue in detail

In a two-player coop session (I as wanderer), during the night's cavelry boss fight in weeping peninsula, we killed the horse first, the boss then resummon his horse, and we killed the "cavelry" part, finishing the boss fight with the horses still alive. 

Instead of disappearing, the boss horse seems to be taken over by regular riderless horse animation and behavior, and start to run away, and then stops at what I assume is the invisible border for the open world boss arena. The horse then pause all behavior, and does not react to player appearing or player's attack. Attacking it will still make it play the hurt animation and reduce it's health, but the horse will not "die" even after its health bar is drained (does not play death animation, does not despawn, hitting it will still make it show hurt animation and damage number, but the health bar is empty).

The stationary horse does not despawn after resting at a grace site, and warping out and warping back at "castle morne rampart" grace site at night will cause the horse alone to be spawn at the night's cavelry spawn point (even aftter the boss is defeated), the behavior remain as above.
This issue happens at least at the wanderer side, as I did not ask the host whether the same issue happens.

### Steps to recreate the bug

Go to the night's cavelry boss fight in weeping peninsula, kill the mount without killing the mount, allow boss to resummon mount, and then kill the rider without killing the mount.
(For respawning horse) Warp to the grace site "castle morne rampart", make sure the time is night, and go to the position where the night's cavelry boss will originally spawn.

### Version

1.2.1 (Latest)

**Comment by Neofaucheur** [comment]
I had something similar happen to me as host. Except we didn't let the rider resummon his horse, but it someone reappeared after killing the boss, exactly in the state you described. We had that happen on several Night's Cavalry. The only one that didn't leave his horse behind was actually the one we let resummon his horse, so the condition might be something else. Maybe related to the players riding Torrent?
