### ISSUE TITLE
Boss targeting spectating player's dead body.

### ISSUE THREAD

**Issue by skechinballs** [LukeYui/EldenRingSeamlessCoopRelease#12]
When fighting most bosses, if one player dies the boss will continue to target the dead player's body causing it to lose it's AI and get stuck in one frame of their walking animation. If the living player attacks the boss it will do one cycle of the animation and lock up again or sometimes will retarget the living player, do one attack/combo, retarget the dead player and become locked again. video of this can be found on my twitch or youtube(same name as git).

**Comment by Ozzyx-SVK** [comment]
had a same issue with gordick the grafted

**Comment by LAxemann** [comment]
Can confirm!
