### ISSUE TITLE
[Bug]: Complete NG+ Lockdown,

### ISSUE THREAD

**Issue by JonoRedder** [LukeYui/EldenRingSeamlessCoopRelease#121]
### Discord Username

Jono#7033

### Describe the issue in detail

Me and a friend killed the Elden beast. Then we reappeared in the room were we fought Ragagon only to notice that he had resurrected to me but was invisible to my friend. We panicked because we had no way to heal ourselves anymore after the fight with the end game boss and rushed to the altar to restore the elden ring. The end game cutscene played and we reappeared UNDER the game map. We fell into the void and died, only to reappear on the site of grace outside of the Radagon boss arena, but now we cannot enter the golden fog anymore completely locking us out of starting NG+.

### Steps to recreate the bug

Defeat Radagon, defeat the elden beast, Radagon glitch somehow and reappears to one of the players, rush to the altar and activate the "restore the elden ring" ending. You both appear under the map and die. You reappear outside of Radagon boss fight but now cannot enter his boss fight anymore.

### Version

1.2.1 (Latest)

**Comment by Zenoo** [comment]
You can start NG+ from the roundtable grace, we had this issue too.
