### ISSUE TITLE
[Bug]: Greyol died on a respawn after our party dying to a Fallingstar beast in Sellia's tunnel

### ISSUE THREAD

**Issue by HexRadiant** [LukeYui/EldenRingSeamlessCoopRelease#129]
### Discord Username

HiJacked#8306

### Describe the issue in detail

We were fighting Fallingstar beast in Sellia's tunnel, my friend died first (he was a wanderer), and I died sometimes afterwards (I am the host, we are playing with only 2 of us). I respawned first, my friend spawned after me and as soon as he spawned we got awarded 133k souls, 5 dragon hearts and a message about new draconic powers being availabe and the dragon communion. We later warped to dragon cathedral and noticed the we now can buy Greyol's roar, thus we established that Greyol just decided to die for no reason. I have a video on this issue happening but I can't link it here as the video is too big. I can stream it in discord if needs will be.

### Steps to recreate the bug

No idea, but try to invite a friend as a wanderer, let him die first and you die after. Maybe that will do the trick.

### Version

1.2.1 (Latest)

**Comment by musaha13** [comment]
Can confirm, playing with a party of 4 and we also got 5 dragon hearts and were awarded 133k souls after dying to The Fallingstar Beast. v1.2.1

**Comment by insanemhelo** [comment]
Greyoll Never appeared in our game and we never got the runes or the option to buy his roar.  We went to hunt him down for the free runes and he wasnt there
