### ISSUE TITLE
[Bug] Joiner can't use horse

### ISSUE THREAD

**Issue by Alphaz0r** [LukeYui/EldenRingSeamlessCoopRelease#13]
Randomly in the game, the joiner can't spawn his horse, the horse appears then disappears immediatly (on the host POV). I believe the bug is related to death system but not sure. We have already got the whistle. 

EDIT : Now I'm sure the bug happens with the death system

**Comment by thembees** [comment]
> Now I'm sure the bug happens with the death system

Can you clarify how this bug happens with the death system? How do you recreate the issue you're having?

**Comment by Alphaz0r** [comment]
> > Now I'm sure the bug happens with the death system
> 
> Can you clarify how this bug happens with the death system? How do you recreate the issue you're having?

I just saw on nexusmod MintedTea said that it is related to when a player sit on a site of grace. The bug I encounter is probably the same

**Comment by LukeYui** [comment]
v1.1.0 should have fixed this. It was an issue with the horse being dead on your end but being alive for the host.
