### ISSUE TITLE
[Bug]: Sorcerer Rogier isn't selling any Ashes of War

### ISSUE THREAD

**Issue by TheUnluckyGnome** [LukeYui/EldenRingSeamlessCoopRelease#130]
### Describe the issue in detail

Sorcerer Rogier's Ash of War/"Learn skills" shop is missing the three Ashes he would usually sell: Carian Greatsword, Glintstone Pebble, and Spinning Weapon.

This occurs when speaking to him in Stormveil Castle and in the Rountable Hold. We, unfortunately, haven't progressed far enough to say if it still happens when using his bell bearing at the Twin Maiden Husks. It also seems to make no difference if we're in a Co-op session or solo.

My friends and I (3 users in total) are all experiencing the same issue. Unfortunately, the usual verifying game files and/or re-installing hasn't fixed it either.

Thanks again for this amazing mod and your dedication to squash bugs like this :)

### Steps to recreate the bug

Speak to Sorcerer Rogier, select the "Learn skills" dialogue option to open his shop, and there will be no Ashes of War to select/purchase.

### Version

1.2.2 (Latest)

### Relevant Crash log

Screenshot of the "store" page,
![image](https://user-images.githubusercontent.com/66805470/173445395-cbf7895b-cc96-4129-b81d-fbc5f24c2324.png)

**Comment by Yoni0040** [comment]
don't know if this helps but my party experienced no issues with rogier and the only difference i could think of is that we haven't talked to him in stormveil castle.
though i doubt it even matters.

**Comment by TheUnluckyGnome** [comment]
Hey Yoni, thanks for the tip. It seems that might actually be the "trigger" so to speak. I started a new character and skipped talking to Rogier at Stormveil Castle. Well, when he showed up at Roundtable Hold, he was selling the Ashes like usual.

Also, as a side-note, this was on version 1.2.2 of the mod still. Updating to 1.2.4 has, unfortunately, shown no change for the working and non-working saves.
