### ISSUE TITLE
[Bug]: "Renna" Encounter at Church of Elleh

### ISSUE THREAD

**Issue by JaytheShifter** [LukeYui/EldenRingSeamlessCoopRelease#132]
### Discord Username

JaytheShifter#0556

### Describe the issue in detail

I have been playing co-op with a friend. After receiving Torrent, we fast-travelled to the Church of Elleh in order to get the Summoning Bell from "Renna". She appeared for me as I spawned in, but once my companion spawned as well, the church walls "blew up" and "Renna" disappeared. Couldn't summon her again unless we teleported again, at which point I quickly spoke with her for the Summoning Bell. She wasn't there anymore for my companion but the Summoning Bell was on the ground where she usually spawns.

### Steps to recreate the bug

After receiving Torrent, we fast-travelled to the Church of Elleh in order to get the Summoning Bell from "Renna". She appeared for me as I spawned in, but once my companion spawned as well, the church walls "blew up" and "Renna" disappeared. Couldn't summon her again unless we teleported again, at which point I quickly spoke with her for the Summoning Bell. She wasn't there anymore for my companion but the Summoning Bell was on the ground where she usually spawns.

### Version

1.2.2 (Latest)

**Comment by moldobmf** [comment]
Still happens in 1.2.4.
