### ISSUE TITLE
[Bug]:  Flask reset 

### ISSUE THREAD

**Issue by Killallravens** [LukeYui/EldenRingSeamlessCoopRelease#134]
### Discord Username

Sicarius#2841

### Describe the issue in detail

Upgrade my flask from 11+ to 12+ and it reset back to 1+

### Steps to recreate the bug

upgrading flask in a co-op session from 11+ to 12+

### Version

1.2.2 (Latest)

**Comment by TheGayestMinotaur** [comment]
**Discord Username**
The Gayest Minotaur

Hi! This also happens if your flask is +12 and you have an extra sacred tear in your inventory! The game allows you to level up the flask, but sets it at +1. 

**Steps to recreate the bug**
Upgrading the flask in a co-op session from +12 using an excess sacred tear in inventory. 

**Version**
 1.2.4 (Latest)

**Comment by thephenixer** [comment]
this issue still happened to me

**Comment by steelsmith** [comment]
### Discord Username
OPness#2858

### Describe the issue in detail
Flask went from +11 to +1

### Steps to recreate the bug
Joined partners session. Upgraded flask from 11 to 12. Host upgrade worked, mine reset back to 1

### Version
1.3.0

### Relevant Crash log
No response

### Attempted fixes
Joined session of brand new character with no sacred tears. There were no sacred tears available in any church.
Joined session of brand new NG+ character. There were no sacred tears available in any church.

Not sure of how I can finish the game now. If anyone can point me to a game editor that I can manually set flask level that would be great. If not then I guess that's 100 hours down the toilet.

**Comment by GeneralZain** [comment]
this also happened to me! after I got to just before the fire giant, with a +11 flask I picked up the upgrade mat at the church, upgraded from 11 to 1 no idea how to fix...im so late in the game and idk if there's any more places I get get flask charges...
