### ISSUE TITLE
[Bug]: Unable to join players in Caelid

### ISSUE THREAD

**Issue by Aleuvian** [LukeYui/EldenRingSeamlessCoopRelease#135]
### Discord Username

Aleuvian#4579

### Describe the issue in detail

**Mods used:**

- Elden Ring Seamless Coop
- thefifthmatt's Elden Ring Item and Enemy Randomizer
- Mod Engine 2
- Elden Mod Loader

**Expected event:** 

Upon using the Effigy of Melania, players should be able to connect to the host, as long as they have properly used the pot item to open their lobby and have the correct password.

**Actual event:**

Upon using the Effigy of Melania, players are unable to connect **if the host player is in Caelid, specifically.** The player is met with "Connecting to player", then are placed into the loading screen, then reload into a singleplayer session in the same spot, regardless of whether they are in Caelid, or any other region.

**Notes:** 

- Players are able to enter Caelid through traditional means: Travel, transporter chest, etc.
- Players can respawn in Caelid at their last activated grace, as expected.
- Online play is not affected in any other region tested so far. (Limgrave, Weeping Isle, Liurnia)
- Players cannot fast travel to Caelid. All clients are disconnected on travel completion.
- Players cannot join a session already in Caelid if they are not in Caelid. (Host is in Caelid, Client is not.)
- Players cannot join a session already in Caelid if they are in Caelid. (Both Host and Client are in Caelid.)
- Players cannot join a session already in Caelid if they are in the same location. (Same grace, +/- a few meters)

### Steps to recreate the bug

**As Host:**

1. Travel to any location within Caelid.
2. Activate the Tiny Great Pot.
3. Wait for a player to attempt to connect.

**As Client:**

1. Travel to any location (ideally near the host location.)
2. Activate the Effigy of Melania.
3. Receive the "Connecting" prompt.
4. Enter the loading screen to connect.
5. Return to the same location in a singleplayer session.

### Version

1.2.2 (Latest)

**Comment by TevildoBM** [comment]
This seems to still be happening as of 1.2.4. Game is modless on my end and there are other bugs when trying to join the host in Caelid.

While it doesn't disconnect all the time, it does so after fast traveling (Game loads forever until it kicks you out.) At one occasion, the loading screen got stuck for both me (client) and the host and had to alt+f4 to exit. 

Other bugs of note while this was happening:

- Redmane Castle's site of grace (before Radhann's boss arena) is sometimes locked by golden fog (as if still fighting the Crucible Knight, yet there are no enemies).
- Redmane Castle's Festival sometimes resets. Client has to speak to Jerren again, even though the host/client has done it before. Even then, gates to Radhann's arena remain closed.
