### ISSUE TITLE
[Bug]: game crash 

### ISSUE THREAD

**Issue by killerki14248** [LukeYui/EldenRingSeamlessCoopRelease#139]
### Discord Username

killerki1424

### Describe the issue in detail

ive gotten to the part where you fight renala queen of the full moon and my game has repeatedly crashed.

### Steps to recreate the bug

fight renala queen of the full moon till the second stage then when the cutscene  starts the game crashes 

### Version

1.2.2 (Latest)

**Comment by LukeYui** [comment]
Hi, thanks for the report. This is a bug with the base game, try verifying your game files with Steam - it should fix the issue.
