### ISSUE TITLE
Forlorn Hound Evergaol vote issue

### ISSUE THREAD

**Issue by rgipsonhansen** [LukeYui/EldenRingSeamlessCoopRelease#14]
Votes/teleporting does not bring all players to arena (and inconsistent ability to vote), players get stuck to summoning platform and only knocked off when hit (but does not necessarily bring the player to the realm). Some players do not port to boss arena but still have music playing until death (not just rest). Happened with 3 people in game.

**Comment by LukeYui** [comment]
Should be fixed in 1.2.0
