### ISSUE TITLE
[Bug]: Game update incompatibility

### ISSUE THREAD

**Issue by SweiryTal** [LukeYui/EldenRingSeamlessCoopRelease#141]
### Describe the issue in detail

Everytime I try to open my world my game crashes, it happens to my friends as well, its probably because there was an update today. Do you know by any chance when will the mod work with the current patch? thanks

### Steps to recreate the bug

Open the world after opening the game.

### Version

1.2.2 (Latest)

**Comment by Yoni0040** [comment]
that's because you updated the game version to 1.05.
the mod isn't compatible with that version yet.

**Comment by LukeYui** [comment]
I fixed in it v1.2.3
