### ISSUE TITLE
[Bug]: Multiplayer boundary

### ISSUE THREAD

**Issue by ValkyrianTorment** [LukeYui/EldenRingSeamlessCoopRelease#142]
### Describe the issue in detail

While hosting a multiplayer session, seemingly any place that dismounts you from Torrent, or the Spiritsprings, acts like a multiplayer boundary and teleports you back. For example, the beach by the Seaside Ruins Site of Grace doesn't let you jump down using the Spiritspring, and if you activate the multiplayer while down there, you aren't allowed back up, even with teleporting.

### Steps to recreate the bug

Use the Tiny Great Pot to host a session, then enter an area that affects Torrent.

### Version

1.2.3

**Comment by LukeYui** [comment]
Are you actually using 1.2.4, and not 1.2.3?

**Comment by ValkyrianTorment** [comment]
The game asked us for an update, and I thought we got it, since it didn't ask again after we did, but apparently that was still 1.2.3, my bad.
