### ISSUE TITLE
[Bug]: "failed to launch eldenring.exe" whenever i execute launch_elden_ring_seamlesscoop.exe

### ISSUE THREAD

**Issue by Topfschnitte** [LukeYui/EldenRingSeamlessCoopRelease#144]
### Discord Username

Zweihand22#8921

### Describe the issue in detail

![Screenshot 2022-06-13 161019](https://user-images.githubusercontent.com/107416030/173372836-654fe86b-ddeb-4551-bee8-6c24633679bc.png)

i installed the latest version of the mod and followed the rather simple tutorial, but i just get this error message and dont rlly know what to do...

its worth mentioning i had a struggle with the easy anti cheat a while back, because i disable anti cheat  manually and tampering with the .bin rendered it untrustworthy. after a long struggle ive fixed it by (not so sure anymore) replacing the bin file by a clean version i think.
could be that this is irellevant but ill leave it here in any case.

ive also used mod engine 2 if that causes any problems.
![Screenshot 2022-06-13 161706](https://user-images.githubusercontent.com/107416030/173374310-4d437d74-b954-47a4-8b05-6a69eba77245.png)
![Screenshot 2022-06-13 161652](https://user-images.githubusercontent.com/107416030/173374361-e8f6d07b-ca13-4827-86c9-82150b6c9c87.png)

### Steps to recreate the bug

just followed the basic installation steps.

### Version

1.2.4 (Latest)

### Relevant Crash log

```shell
since the game doesnt start, there is no crash log.
```

**Comment by clarson15** [comment]
Since you've talked about modifying your installation multiple times in the past, I'd recommend verifying the integrity of your game files through steam and following the setup instructions again.

**Comment by LukeYui** [comment]
I can see in your screenshot that you require administrator privilages to launch eldenring.exe. Therefore the launcher will also need to be ran with these same privilages to open the game.

Could you try to run the mod launcher as an admin and see if that resolves the problem?

**Comment by LukeYui** [comment]
Glad to hear, I'll close this report for now and make a note in case others have this problem
