### ISSUE TITLE
Using Grace Causing Lag In Area

### ISSUE THREAD

**Issue by justn1** [LukeYui/EldenRingSeamlessCoopRelease#15]
Playing with a friend, used a grace at Mountaintops of the Giant (At around 'Church of Repose'), right outside the church if you face your camera there you get a huge amount of frame drops which makes the game unplayable until you look away

**Comment by LukeYui** [comment]
The mod doesn't affect anything that should lead to lower performance. I can't see how it would cause frame drops unless someone was repeatedly resting at a site of grace.

Resting reloads all of the enemies in the area, so some performance hit is expected. All I can suggest is to re-verify your game files with steam and see if that fixes things.

**Comment by justn1** [comment]
It's not happening to me only though, it's happening to everyone in the session

**Comment by justn1** [comment]
@LukeYui Definitely has nothing to do with the game files (which I did indeed re-verify). As you can see my friend has the same problem as well. The frame drop is significantly bad.

1) Friend has the same issue:
https://medal.tv/games/elden-ring/clips/nmJvDDGPW82BQ/fSqMWj1vaI6n?invite=cr-MSw3dTYsNjYyNzExNjYs

2) Everything you need to see:
https://medal.tv/games/elden-ring/clips/nnqYd2dH8Wbo-/d1337Hw4gbPC?invite=cr-MSxrV00sNDI2OTc1NTUs
