### ISSUE TITLE
[Bug]: Can't use Festering bloody finger

### ISSUE THREAD

**Issue by DannyDarth** [LukeYui/EldenRingSeamlessCoopRelease#152]
### Discord Username

DannyDarth

### Describe the issue in detail

There is a quest line that needs to invade. But you can't actually invade.

### Steps to recreate the bug

Load up seemless coop and try to use festering bloody finger.

### Version

1.2.4 (Latest)

**Comment by Yoni0040** [comment]
that's intended as there are mod related items to start co-op
