### ISSUE TITLE
[Bug]: NPC appearing inconsistently for any player either host or wanderer.

### ISSUE THREAD

**Issue by EmuuXD** [LukeYui/EldenRingSeamlessCoopRelease#154]
### Discord Username

Emu#1001

### Describe the issue in detail

I am playing with 1 other person and NPCs will often appear for my friend but not me despite doing all quests together. Yura would often appear for my friend but not me unless I closed the world and reloaded the area to talk to them alone. The Volcano Manor was especially bad about this where the entire manor would be empty often but not always. 

A small thing that didn't affect our quests for the manor was some of the letters depicting quest locations didn't spawn. Even if I went to the manor in a closed world and reloaded the area I could never get a letter that I was meant to get.

Thanks for the mod, we love it <3

### Steps to recreate the bug

Playing with other players when you arrive to where an NPC should be.

### Version

1.2.4 (Latest)

**Comment by chrsolr** [comment]
I faced this issue since `1.1.0`. I think it got worse on `1.2.0`.
 We need to check with each other if we can see the NPC. If we don't, then we do the questline solo.
