### ISSUE TITLE
[Bug]: Don't respawn from death after defeating dragon boss in front of Ranni's Rise.

### ISSUE THREAD

**Issue by NeoConker2k22** [LukeYui/EldenRingSeamlessCoopRelease#156]
### Describe the issue in detail

I was the host and died to the dragon boss, Glintstone Dragon Adula, that spawns in front of Ranni's Rise. My co-op partner got the dragon to half health and it disappeared for its encounter later in the game. I remained in spectator mode even after the dragon was long gone. I didn't actually die and respawn until my co-op partner rested at a Site of Grace. After that things worked as normal.

I assume this happens because this dragon boss isn't technically "dead" as it's a scripted event so that the dragon can appear later in the story outside the Cathedral of Manus Celes in south Liurnia. I also assume this would happen with the other dragon that disappears at half health.

### Steps to recreate the bug

1. Initiate fight with dragon boss in front of Ranni's Rise.
2. One of the players die and enter spectator mode.
3. Watch your co-op partner defeat the dragon -- get the dragon to half health where it then disappears.
4. The dead player remains in spectator mode until your co-op partner sits at a Site of Grace.

### Version

1.2.4 (Latest)

**Comment by nameonascreen** [comment]
pretty sure thats not a bug. in my experience, if me or my friend died during any boss, we had to rest at a site of grace to respawn our friend.
