### ISSUE TITLE
[Bug]: Tiny Great Pot extreme duplication bug

### ISSUE THREAD

**Issue by Upsettis** [LukeYui/EldenRingSeamlessCoopRelease#157]
### Discord Username

Upset#5469

### Describe the issue in detail

I was in my friend's world at the roundtable hold upgrading my weapon. Then I upgraded it and it said I had no more smithing stones and tiny great pots started infinitely spawning into my inventory.
![1](https://user-images.githubusercontent.com/107449728/173480279-33b4aafd-216f-4680-9f63-51c3334045f2.png)
![2](https://user-images.githubusercontent.com/107449728/173480291-8abf0613-bb77-4144-9f45-2965ee20164e.png)
![7](https://user-images.githubusercontent.com/107449728/173480379-ced4aa9a-d14f-49f8-8274-d0174edf81a3.png)
 Disconnecting simply stopped them being added, however there are now uncountable amounts of great pots in my inventory

### Steps to recreate the bug

Have not been able to recreate bug, sorry for any inconvience

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Duplicate of #71
