### ISSUE TITLE
Melina/Roundtable Hold keeps triggering

### ISSUE THREAD

**Issue by LAxemann** [LukeYui/EldenRingSeamlessCoopRelease#16]
Heya, first and foremost thanks a lot for the mod, it's THE experience for my friend and me right now. :)

**Issue:**
We're facing an issue where the cooperator keeps triggering the sequence of Melina bringing you to the RoundTable hold whenever using a site of Grace. Nothing happens upon agreeing to do so, it just plays the hand-holding animation and resumes with the grace menu.
We also have issues with questline progressions which might or might not be related, which I will create another issue for.

**Rough steps:**
1. Started the game together, cooperator jumped down a cliff and triggered the cave-sequence for him, both panic-alt-f4'd
2. Joined back in the starting area, got killed by scion, both players got the cave-sequence again and proceeded
3. Talked to Varre, then explored around Limgrave, finished the Stormfoot Catacombs and got to Sellen
4. Triggered the sequence with Melina at Agheel Lake North grace and teleported to Roundtable Hold, bug persists since then (Note: We both spoke to her simultaneously and both agreed to go to the Roundtable Hold almost simultaneously)

**Comment by Arclesis420** [comment]
The Melina thing keeps happening to me and my friend as well.

**Comment by CriticalCatch** [comment]
Is this resolved?

**Comment by Amnesiac9** [comment]
Still happening 1.2.4 - only to my buddy who joins my world.

**Comment by legodude0202** [comment]
Hi, me and a friend are having the same issue, with some alterations. When I first join his game and use a site of grace, Melina does her roundtable hold dialogue. This goes away after the first interaction with her. However, after beating Morgot the omen in front of the erdtree, she does her "burn the erdtree" dialouge every time I rest at a site of grace. The initial problem isn't that bad, but the new dialogue occurs EVERY time I rest at a site of grace. Any more information is needed, I will gladly give it.

**Comment by clara-a-correia** [comment]
Me and my co-op partner are also experiencing this. I'm the one hosting, and he states that not only Melina keeps repeating the roundtable dialogue but that most NPCs also recite their initial dialogue regardless of how many times they were interacted with

**Comment by Brankurtzz** [comment]
This happened to me somethimes, after i killed Morgott, Melina talk to me in every Grace i rest, she stop spawning after the Fire Giant when You can go to Farum Azula

**Comment by Corosar** [comment]
A part of me thinks this might be somehow tied with the client's NPC progression flags either not being detected when visiting a host world (which is preventing shopkeepers from maintaining their solo item stocks). or they are not syncing with the host's flags (which just doesn't let clients get anything but the basic items from shopkeeps). just a thought?
