### ISSUE TITLE
[Bug]: boss focus on one person and don't move is that person die

### ISSUE THREAD

**Issue by bvives** [LukeYui/EldenRingSeamlessCoopRelease#163]
### Discord Username

Xbug#2612

### Describe the issue in detail

This happens to us in radagon/elden beast.

After a non bugged fight we dead to elden beast and in the rematch, both, radagon and later elden beast only focus the host.

Also when the host dies in elden beast, it simply put in idle stance and become unresponsive until the death.

As a bonus bugs, 
-if someone die on elden beast, and others finish it, the loser can't get the runes, this isn't strictly a mod bug, but is an effect of the spectator mode.
-after the final scene, we spawn below the throne grace, inside the textures.

### Steps to recreate the bug

Two persons.
Go to radagon fight, kill him, then dead to elden beast, retry the fight.

For the bug of spawn below the grace, simply end the game.

### Version

1.2.4 (Latest)

**Comment by Ed-boye** [comment]
I've ran into this with Margit, Godrick, and Rennala too, +1

**Comment by Zenoo** [comment]
Same issue with Malenia

**Comment by RoseVesper** [comment]
Same issue with Mohg.
