### ISSUE TITLE
[Bug]: Quit Game and Return to Desktop buttons both greyed out

### ISSUE THREAD

**Issue by LividCynic** [LukeYui/EldenRingSeamlessCoopRelease#164]
### Describe the issue in detail

When playing with the seamless coop mod, after playing or the game bugs out to where my buddy can't join. We both have to quit the game. Issue being is that he can quit the game with no problems but I always have to force close the game because both the Quit Game and Return to Desktop options are both greyed out.

### Steps to recreate the bug

Try to quit the game while hosting a lobby

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
You can't quit the game when hosting a lobby, it's not a bug. Use the separating mist to close your lobby.
