### ISSUE TITLE
[Bug]: Friend Can't Get Steed or Talk to Melina

### ISSUE THREAD

**Issue by link38110** [LukeYui/EldenRingSeamlessCoopRelease#165]
### Discord Username

linkhearo#8870

### Describe the issue in detail

I'm playing with 2 others, so 3 total in a game. Friend 1 touched the bon fire and friend1 and 2 both got the cinematic cutscene for meeting Melina for the first time, but I never got the cutscene. I was able to talk to her though and accepted her as my maiden for the mount same with friend 2, but friend 1 didn't have the option to talk to Melina to get the mount. Friend 1 can level up but doesn't have the mount whistle, and when he dies, he can't retrieve his runes. 

### Steps to recreate the bug

Grabbed sites of grace and got the cinematic on the site of grace at Agheel Lake South. Grabbed Cave of Knowledge, then  Stranded Graveyard, thenThe First Step, then Seaside Ruins, then last Agheel Lake South.

### Version

1.2.4 (Latest)

**Comment by claudiurazlet** [comment]
I deleted the mod files from the "GAME" folder, redownloaded the mod and extracted it. I didn't set the password though. I entered the game immediatly and went to watch the clip. After watching the clip, I closed the game and changed the password. Hope it helps.
