### ISSUE TITLE
[Bug]: Nightime bosses won’t spawn

### ISSUE THREAD

**Issue by Jnokes18** [LukeYui/EldenRingSeamlessCoopRelease#170]
### Discord Username

JoMama#8950

### Describe the issue in detail

Simply every time we tried to fight a nighttime boss, it doesn’t spawn. For example, knight Bernahl doesn’t despawn to spawn the Bell bearing hunter. Tried a few others can’t remember exactly which ones, but enough to assume all of them don’t work, haven’t tried since the 1.12.1 update

### Steps to recreate the bug

Try to fight any nightime boss

### Version

1.2.1

**Comment by shervlak** [comment]
I think the host needs to be the one to pass the time while sitting on a grace. Thats how we fixed that when trying to fight the night's cavalry
