### ISSUE TITLE
[Bug]: Multiple Bug Report.

### ISSUE THREAD

**Issue by R4VO** [LukeYui/EldenRingSeamlessCoopRelease#171]
### Describe the issue in detail

bug1: Melina keeps bothering the wanderer about the giant in the mountains after killing morgott. Everytime after sitting at ANY site of grace.
bug2: Everytime wanderer joins he has to listen to Melina about testing the wanderer and going to roundtable hold.
bug3: Cannot fast travel to any site of grace after doing lyendell assasination quest for the volcano manor.

### Steps to recreate the bug

I do not know how to recreate the bug1 and bug2. However to recreate the bug3 you have to get the assassination quest from Knight Bernahl then go to lyendell rountable hold. Then the host would need to activate the invasion, wanderer should do nothing and sit still near the host. When the invasion starts and ends successfully (without dying) the players would still get a chance to vote on fast travelling but they would not see each other. When restarted the game the wanderer wouldn't have the luxury of teleporting to any site of grace on his own world (without joining). When tried the message displays (Cannot fast travel to any site of grace right now.) I think the game still thinks I'm invading the host of finger from the quest (i was the wanderer).

### Version

1.2.4 (Latest)

**Comment by 626954261** [comment]
bug1 and bug2 will do not happen again when Melina is burned in the snow mountain，I had this problem before
