### ISSUE TITLE
[Bug]: Varre Questline

### ISSUE THREAD

**Issue by DieselRulez** [LukeYui/EldenRingSeamlessCoopRelease#173]
### Discord Username

Diesel#0683

### Describe the issue in detail

Part of the Varre Questline involves invading other players.

he then gives you an item to teleport to the Dynasty Mausoleum Entrance. the only other way to get here is through the storyline.

Is there anyway to get Varre to drop the item on death or something to that effect?

Sorry I'm not sure if its really a bug per say but figured I'd post this anyway.

Diesel

### Steps to recreate the bug

Follow Varre Questline.

### Version

1.2.4 (Latest)

**Comment by Zabedz** [comment]
This isn't a bug. Should be closed.

**Comment by LukeYui** [comment]
Yep, once he gives the items just reload the area and he'll act as if you've done the invasions.

**Comment by DieselRulez** [comment]
Ah Spot on! thanks lads! @NeoConker2k22 @LukeYui!! <3
