### ISSUE TITLE
Failed to load save data

### ISSUE THREAD

**Issue by Tumbleweeb** [LukeYui/EldenRingSeamlessCoopRelease#175]
### Discord Username

Tumbleweeb #5526

### Describe the issue in detail

My friend and me were downloading the mod and it worked just fine for me. But as soon as my friend started the game it just said corrupted save data. His normal game works and we downloaded exactly the same files. I send him what i downloaded but for some reason he just cant start it and we have no idea what to do. And when he started the game i think he also got banned from multiplayer.

### Steps to recreate the bug

Simply start the game with the launcher.

### Version

1.2.4 (Latest)

**Comment by sauceleawesome** [comment]
You have to go to %appdata%/roaming/eldenring, backup then delete the .sl2 files then verify your game, that seemed to work for my friend.
