### ISSUE TITLE
Empty roundtable

### ISSUE THREAD

**Issue by TorchTheo** [LukeYui/EldenRingSeamlessCoopRelease#18]
I don't know what triggers this. When I go back to roundtable, there is no npc and the tp is banned. And there is a barrier on the way to the hall. It's just like I am invaded but no one appear. Please fix this.

**Comment by LukeYui** [comment]
Hi, this should be fixed in 1.2.0 and was caused by an NPC invasion event triggering but the NPC not spawning.
