### ISSUE TITLE
[Bug]: Melinia

### ISSUE THREAD

**Issue by Forerunner187** [LukeYui/EldenRingSeamlessCoopRelease#180]
### Discord Username

Forerunner The Interloper

### Describe the issue in detail

when joining the host, the other players will receive the message of enemy felled or greater enemy felled and receive runes and items but no bosses have been actually been slain.

### Steps to recreate the bug

see description

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Duplicate of #38
