### ISSUE TITLE
[Bug]: 4 Belfries Varre Quest Chapel Of Anticipation

### ISSUE THREAD

**Issue by dashlock21** [LukeYui/EldenRingSeamlessCoopRelease#182]
### Discord Username

dashlock21#0173

### Describe the issue in detail

Trying to do the Varre Questline where you soak the maiden blood on the cloth- used a key to open the second portal that takes me to the chapel of anticipation; once there i can cross the bridge but the boss room yellow portal is impassible, does not give the option to enter to fight the boss.

### Steps to recreate the bug

get the cloth to soak with maiden's blood from Varre at the Rose Chapel. go to 4 belfries and open the portal that lets you go to chapel of anticipation, open portal, go through it and across the bridge, go to the yellow port that puts you against the boss; it will not let you enter.

### Version

1.2.4 (Latest)

**Comment by SimonasBanys** [comment]
seen in 1.2.5 as well, not sure if its true in the case of @dashlock21 but I joined a friends world before going through chappel of anticipation boss fight so might be relevant to that
