### ISSUE TITLE
non host gets all the items they are missing compared to the host on join

### ISSUE THREAD

**Issue by jayyyin** [LukeYui/EldenRingSeamlessCoopRelease#183]
### Describe the issue in detail

My friend and I have 2 characters and due to a miscommunication he joined my main character ( really far into the game) with a character we were playing with another friend of ours (much further behind) and it gave him tons of items on join even a talisman pouch.  The items were kept after he disconnected.

### Steps to recreate the bug

have anyone with lower progress join someone with higher progress.

### Version

1.2.4 (Latest)

**Comment by BosForPresident** [comment]
That is a feature of the mod. This makes it so that you don't miss any story related items or quest items.

**Comment by jayyyin** [comment]
are they supposed to keep the items though?

**Comment by BosForPresident** [comment]
To my knowledge they do.
