### ISSUE TITLE
[Bug]: I can not connect to online

### ISSUE THREAD

**Issue by Batman14053** [LukeYui/EldenRingSeamlessCoopRelease#185]
### Discord Username

Beyond#0117

### Describe the issue in detail

My friend and I have the same password but can not join each other at first I could not try to get online at all without crashing immediately then I updated to the new file and now it just keeps saying no sessions found. 

### Steps to recreate the bug

I just start the game and try using the effigy of Melina once my friend uses the tiny great pot

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Ensure you both have the same password files, and the same mod and game version to connect with each other.
