### ISSUE TITLE
[Bug]: Rykard's second phase kicks everyone out of the game

### ISSUE THREAD

**Issue by Foxlass** [LukeYui/EldenRingSeamlessCoopRelease#188]
### Discord Username

Lainey#3077

### Describe the issue in detail

I was fighting Rykard with three other people, the 1st phase goes smoothly but once his cutscene starts for his 2nd phase, everyone but the host is kicked from the game (disconnected.)

### Steps to recreate the bug

Start the fight with Rykard in Volcano Manor, beat his 1st phase, and then at the start of the second phase (during the cutscene) all players will be disconnected from the session, essentially making Rykard unbeatable in co-op.

### Version

1.2.4 (Latest)

**Comment by TemplarIRL** [comment]
Can confirm.
As a 'work around' we simply rejoined and finished the fight...
Granted, this caused Rykard to focus on only the Host and left the traveler to whomp on him. Heh
