### ISSUE TITLE
[Bug]: Malenia fight crashes when I get to second phase

### ISSUE THREAD

**Issue by Peachkid90** [LukeYui/EldenRingSeamlessCoopRelease#192]
### Describe the issue in detail

Malenia takes a quick nap after me throwing skulls at her for 2 minutes and I get booted to desktop

### Steps to recreate the bug

Phase Malenia and prepare to cry/crash

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Sorry to hear this, can you try verifying your game files with Steam and seeing if that resolves the problem?
