### ISSUE TITLE
[Bug]: Game Crashes at Dectus Lift

### ISSUE THREAD

**Issue by Red-Skelly-Man** [LukeYui/EldenRingSeamlessCoopRelease#194]
### Discord Username

red skelly man#9512

### Describe the issue in detail

I attempted to hoist the medallion and after the screen fades to begin cutscene, the game suddenly closes as though force-quit. 

Currently on Version 1.2.4, and notably two of my friends have successfully hoisted the medallion on the same version. 

### Steps to recreate the bug

Get both halves of the Dectus medallion, go the the lift and hoist away. 

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Hi, sorry to hear you're having trouble. Have you tried verifying your game files with Steam? Crashing in cutscenes is usually as a result of an incorrectly installed game update, and this should fix the problem.
