### ISSUE TITLE
[Bug]: Cannot Quit or Exit to Desktop

### ISSUE THREAD

**Issue by AbbyRose13** [LukeYui/EldenRingSeamlessCoopRelease#195]
### Describe the issue in detail

Could not properly quit or exit to desktop.

![286978461_1025646624992458_1543207201092487911_n](https://user-images.githubusercontent.com/15872281/173737860-2be33b85-e562-4ae4-9ff4-b54051a8d9fc.jpg)
 

### Steps to recreate the bug

My friend and I started a new game, messed around for about an hour - went from first steps through the trap chest in the dragon ruins to sellia tunnel, etc. We didn't go through any boss doors, but we did get whooped by the Night Calvary out past the Gatefront Ruins. We decided to get off, so he did the Separating Mist but then both of us could not exit the game correctly. I attached an image, but I don't really know if there is a specific way to recreate this.

### Version

1.2.4 (Latest)

**Comment by KentGrigo** [comment]
Minimal case:
- Start game
- Use _Tiny Great Pot_
- Try to quit the game

Expected: The button is clickable
Actual: The button is unclickable

**Comment by LukeYui** [comment]
It's not a bug, you just can't quit the game whilst you're in a party. Use the separating mist to end the session
