### ISSUE TITLE
[Bug]: crashing in Nokron

### ISSUE THREAD

**Issue by AlienThrower434** [LukeYui/EldenRingSeamlessCoopRelease#196]
### Discord Username

AlienThrower434#0933

### Describe the issue in detail

I disconnected from the world of my friends in Nokron and spawned there after I left. But once I spawned in the area became unstable and started to crash to desktop everytime I loaded the save. I can no longer play on that save. 

### Steps to recreate the bug

Play with two friends and then lose connection. After that you should spawn where you were with them and if you move further into Nokron the game will skip a frame and kick you to desktop.

### Version

1.2.4 (Latest)

**Comment by henrymaaaa** [comment]
I also crash immediately going to Mistwood Nokron entrance

**Comment by SDFarias** [comment]
My friend experienced this as well. No amount of teleporting out and re-loading Norkon fixed it. Persisted between closing game and rebooting PC
