### ISSUE TITLE
[Bug]: Game Save Corrupt at Raya Lucaria Academy

### ISSUE THREAD

**Issue by AwayFromServer** [LukeYui/EldenRingSeamlessCoopRelease#199]
### Discord Username

AFS#2040

### Describe the issue in detail

I was running around inside Raya Lucaria's Academy, and after passing by a bunch of undead, I entered a room that crashed my game to desktop. Now I can't load my game, it always crashes to desktop again. Happy to provide my save file if that helps.

### Steps to recreate the bug

Go to Raya Lucaria Academy, run through the area with undead rising from their graves, get crashed to desktop, try to reload your save repeatedly.

### Version

1.2.4 (Latest)

### Relevant Crash log

```shell
Faulting application name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Faulting module name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Exception code: 0xc0000005
Fault offset: 0x0000000000234619
Faulting process id: 0x20a8
Faulting application start time: 0x01d8807f62685a0a
Faulting application path: D:\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: D:\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Report Id: 91c6da3b-f135-4941-b6a3-b573afa571d0
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by LukeYui** [comment]
Hi, sorry to hear you're having trouble. Have you tried verifying your game files with Steam? If this doesn't fix the issue, feel free to upload your save here and I'll take a look.

**Comment by TrophyCoyote** [comment]
Same issue.
When returning to raya lucaria to respec, once loaded, the game chrashed and keeps crashing while loading.

Attempting to verify game files now. Will provide an update after if that doesn't fix it.
Latest patch.
