### ISSUE TITLE
Trapped Transporter Chests

### ISSUE THREAD

**Issue by dconns1** [LukeYui/EldenRingSeamlessCoopRelease#2]
The trapped transporter chests can be used by only 1 player in the multiplayer game.  The secondary player can use it once sitting at the site of grace.  That being said prior to sitting at the site of grace when the chest cannot be used the player who "went on ahead" spawns in front of the user left behind in random spots.  If you look at the attached photos the player who used the transporter chest appeared on the ceiling (TransporterChest_02) and could be seen running around and performing actions.  Additionally, as I was running for the site of grace the player would continue to spawn in random spots on the map almost as if he was there with me (TransporterChest_03) but he would be running/attacking in place.  To confirm those were the actions he was performing in the area that he was teleported to.

![TransporterChest_01](https://user-images.githubusercontent.com/17128823/170813606-44515307-b743-4e74-bb04-5b55ce3051fa.png)
![TransporterChest_02](https://user-images.githubusercontent.com/17128823/170813608-9f8de0a9-86d1-4d78-a0a5-056fa043f124.png)
![TransporterChest_03](https://user-images.githubusercontent.com/17128823/170813609-79828677-e1d4-424e-af8a-8c5696e3b5f3.png)

**Comment by WysockiBartek** [comment]
It still happens. I had a similar issue with transporter chest in Dragon Burnt Ruins. The exact same resolution.
