### ISSUE TITLE
[Feature Request] Release source code?

### ISSUE THREAD

**Issue by OkaMoez** [LukeYui/EldenRingSeamlessCoopRelease#20]
Are there any plans to release the source code?

I saw that for your other competitive online mods, you avoided releasing it for stability and security reasons.
Does that apply to this mod too, despite its coop focus? (as opposed to PvP)

**Comment by simonfuhrmann** [comment]
I agree. The community would very much appreciate the source code.

**Comment by Alphaz0r** [comment]
That's a good idea, some people here could help ! But it's up to you at the end, it's your work and I already thank you for that !
