### ISSUE TITLE
[Bug]: Game crashes when entering volcano manor

### ISSUE THREAD

**Issue by BosForPresident** [LukeYui/EldenRingSeamlessCoopRelease#204]
### Discord Username

BosForPresident#9853

### Describe the issue in detail

Whenever i enter volcano manor the game crashes. Every time I try to enter the game on that save file it immediately crashes again. It happened on 2 save files allready and i lost a total of 32 game hours to this. downgrading on the version mod or reinstalling the newest version of the most doesn't work.

### Steps to recreate the bug

Enter volcano manor (area)

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Verify your game files with Steam then try again. It's a bug with the vanilla game where the game doesn't update correctly

**Comment by BosForPresident** [comment]
Thanks man, it works now.
