### ISSUE TITLE
[Bug]: free runes

### ISSUE THREAD

**Issue by IClark56** [LukeYui/EldenRingSeamlessCoopRelease#208]
### Discord Username

FastBird#3976

### Describe the issue in detail

Getting free runes when a player joins a world maybe from past boss fights. Mainly happens when sitting at grace.

### Steps to recreate the bug

Join world, get runes, sit at grace, get more runes(anywhere from 5,000- 10,000) and cant level up after this. 

### Version

1.2.4 (Latest)

**Comment by loki2236** [comment]
Duplicate of #56
