### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by KizaKip** [LukeYui/EldenRingSeamlessCoopRelease#214]
### Discord Username

.KizaKips.

### Describe the issue in detail

Was playing coop with a mate and when we made it to ranni's castle she wasnt there for me but appeared on my friends game, he talked to her  and agreed to be her servant and the npc's appeared everywhere for both of us, but because i have no way of speaking to ranni we are unable to leave the castle.

### Steps to recreate the bug

2 people, get to rannis castle, if shes only there for one person let said person speak to her and agree to be her servant, you will now both be stuck in the castle

### Version

1.2.0

**Comment by Yoni0040** [comment]
Hey, The game made it that if you went to Radahn's festival before coming to Ranni's rise then she wouldn't be there until you beat Radahn
