### ISSUE TITLE
[Bug]: Game crashes whenever i use the tiny great pot or effegy of malenia

### ISSUE THREAD

**Issue by Monthhom** [LukeYui/EldenRingSeamlessCoopRelease#215]
### Discord Username

monthom90#5741

### Describe the issue in detail

exactly as the title describes. the game crashes when ever myself or a friend used the tiny great pot or effegy of malenia (the other multiplayer item im not sure if it does the same, i didnt test).  its not our pc's because we both have pretty powerful computers and mine worked perfectly fine until i updated the game to 1.05.  also there is no lag or any other issues with the game at all UNTIL we used those items, then it game just glitched and crashed

### Steps to recreate the bug

to be perfectly honest i dont know a proper fix, i think it might just be a mix up in the code or something

### Version

1.0.1

### Relevant Crash log

```shell
i dont know how to access this properly, sorry...
```

**Comment by 626954261** [comment]
Why not update to 1.2.4

**Comment by LukeYui** [comment]
You must be playing on the latest version (1.2.4) to play on game version 1.05
