### ISSUE TITLE
[Bug] Issue with Ranni at Church of Elleh

### ISSUE THREAD

**Issue by tatoyoda600** [LukeYui/EldenRingSeamlessCoopRelease#22]
At the Church of Elleh, Ranni spawns in just fine when you've met the requirements for her, but if another player connects or leaves a loading screen (Basically whenever they can move around the world), Ranni will immediately despawn. We had warped to the church, Ranni showed up for me, but as soon as my friend left the loading screen and showed up at the church, Ranni left mid dialogue.

**Comment by Ed-boye** [comment]
Oh we had this issue with invasions before too... wonder if it's related. Essentially we were trying to get an invading NPC to spawn but in the end only one of us could see them and when my friend died they came back and were unable to see the invading NPC. Interestingly enough, the invading NPC could see them and tried to attack them (no hits landed/damage done iirc)

**Comment by CogentRedTester** [comment]
My friend and I had the exact same issue. Do you know if this impacts your ability to get the spirit calling bell from the Twin Maiden Husks? Ranni isn't respawning and the bell isn't there now, but we haven't gone to Liurnia yet, which is what I've heard triggers the Husks to get it in stock.

**Comment by CogentRedTester** [comment]
An update, upon restarting the game and returning to the church Ranni showed up again. We did it in single player to avoid the same thing happening again, but this bug doesn't permanently break anything.
