### ISSUE TITLE
[Bug]: If an NPC summon dies, it heals a portion of boss' health.

### ISSUE THREAD

**Issue by ManaforceStudios** [LukeYui/EldenRingSeamlessCoopRelease#222]
### Describe the issue in detail

When you summon a NPC cooperator, it adds health / removes it to boss when they die.

### Steps to recreate the bug

Fight Godrick with Nephali Loux, or Margit with Rogier

### Version

1.2.4 (Latest)

**Comment by AlaskanBeard** [comment]
I experienced the same bug with both Godrick and Margit.

**Comment by LukeYui** [comment]
They don't get healed, their maximum health just reduces as a result of the NPC cooperate leaving.
