### ISSUE TITLE
[Bug]: Boss fell through floor

### ISSUE THREAD

**Issue by jjburke-code** [LukeYui/EldenRingSeamlessCoopRelease#224]
### Discord Username

Yoesph

### Describe the issue in detail

Blood hound evergaol. WHen starting my coop partner fell through the floor and so did the boss. Killing him and the boss

### Steps to recreate the bug

Fight the boss perhaps. Might just be a random issue 

### Version

1.2.4 (Latest)

**Comment by SafetyTheFlameWolf** [comment]
Guess your friend took the boss to the Shadow Realm along with himself lol
