### ISSUE TITLE
[Bug]: Trapped chest dont teleport everyone

### ISSUE THREAD

**Issue by jjburke-code** [LukeYui/EldenRingSeamlessCoopRelease#225]
### Discord Username

Yoesph

### Describe the issue in detail

Friend went into trapped chest and I didnt go too. Caused me to be trapped and un able to teleport

### Steps to recreate the bug

Trapped chest

### Version

1.2.4 (Latest)

**Comment by shervlak** [comment]
Only solution we found is to let the host open the chest just leave the world and reconnect again to the host. Its annoying but easily avoided

**Comment by LukeYui** [comment]
It's not a bug, transporter chests can only teleport one person at a time and the chests will only reset when you rest at a site of grace. I'll note this down as a QoL issue and close the bug report.
