### ISSUE TITLE
[Bug]: Friend cannot load seamless coop. Says "Can't find eldenring.exe"

### ISSUE THREAD

**Issue by Russsman** [LukeYui/EldenRingSeamlessCoopRelease#226]
### Discord Username

Russman#9918

### Describe the issue in detail

My friend and I tried seamless co-op one day an it worked fine. Next time we tried there was an update. After his update the mod would not launch. His screen would go white an say "cannot find eldenring.exe" . He tried loading the elden ring normal and it worked, but he got the “Inappropriate Activity Detected”. He doesn't care about base game co-op so if hes banned thats ok. He deleted the file and app, added them back, same thing. Anyone know the issue? Also if it gets fixed and he is banned, will the mod still allow us to play together?

### Steps to recreate the bug

Not sure, I did the same steps as my friend an my game is fine. All we did was update an launch the mod.

### Version

1.2.4 (Latest)

**Comment by kagurazaki8472** [comment]
Check the properties of the updated launch_elden_ring_seamlesscoop.exe and make sure its not blocked by smartscreen and run it as administrator. 
This has mostly fixed the "cannot find eldenring.exe" issue in the past.

**Comment by Starzilla29** [comment]
also, I had to make sure my normal elden ring was up to date on steam to get mine working.
