### ISSUE TITLE
[Bug]: Steam forcing no connection while playing modded game

### ISSUE THREAD

**Issue by M4J0RFR33Z3** [LukeYui/EldenRingSeamlessCoopRelease#227]
### Discord Username

M4J0R_FR33Z3#9883

### Describe the issue in detail

Every time I am hosting a game with my friend, they keep getting disconnected and steam shows as no connection. Once this happens, then an error occurs trying to reopen the session saying that session timed out, and on my friend's world it was saying no sessions found.

Once I click off the game, Steam immediately goes back to normal.

I have confirmed that it was not an internet issue by resetting my internet and not a steam issue as my friend was using steam as well and both on the same version. Also, It is not a windows issue as there has no updates or firewall errors appearing, and Steam is allowed through the firewall.

### Steps to recreate the bug

Recreation is random as connection will be stable and then randomly drop while playing. It happens both in and out of combat.

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
I haven't been able to recreate this issue. The mod uses Steam as the normal game would and doesn't make any modifications to how the connection functions.
