### ISSUE TITLE
[Bug]: game crashes at Palace Approach Ledge-Road

### ISSUE THREAD

**Issue by ore9** [LukeYui/EldenRingSeamlessCoopRelease#228]
### Discord Username

Ore #8153

### Describe the issue in detail

Any time I fast travel to Palace Approach Ledge-Road my game keeps crashing. Now that my character is there every time I load into that save file the game crashes 1 second after the zone loads in. I tried leveling a new character too and when I fast traveled to that grace with the new character it also caused my game to crash

### Steps to recreate the bug

Any time I fast travel to Palace Approach Ledge-Road my game keeps crashing. Now that my character is there every time I load into that save file the game crashes 1 second after the zone loads in. I tried leveling a new character too and when I fast traveled to that grace with the new character it also caused my game to crash

### Version

1.2.4 (Latest)

### Relevant Crash log

```shell
Faulting application name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Faulting module name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Exception code: 0xc0000005
Fault offset: 0x0000000000234619
Faulting process id: 0x3a58
Faulting application start time: 0x01d881e5f5cf9d86
Faulting application path: D:\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: D:\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Report Id: e49f2efc-c4e3-4fd8-a7ff-d721eaf0c1f4
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by LukeYui** [comment]
Hi, sorry to hear you're having trouble. Have you tried verifying your game files with Steam? If this doesn't fix the issue, feel free to upload your save here and I'll take a look.
