### ISSUE TITLE
[Bug]: Picking up item gives a bunch of tiny great pots 

### ISSUE THREAD

**Issue by jjburke-code** [LukeYui/EldenRingSeamlessCoopRelease#229]
### Discord Username

Yoesph

### Describe the issue in detail

friend hit y to get item on chest and got 90+ rows of tiny great pots in his inventory. Previous to this he hit Y to sit at bonfire and got one. 

### Steps to recreate the bug

2 people at southern castle opened chest

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Duplicate of #71
