### ISSUE TITLE
[Bug] Melina won't stop asking if I want to go to Roundable hold

### ISSUE THREAD

**Issue by Ed-boye** [LukeYui/EldenRingSeamlessCoopRelease#23]
Unsure how to reproduce exactly except that my friend and I started coop together and played through the first time she asks this together. Now at random intervals when (usually as joiner) I sit at grace she'll ask if I want to go. Saying yes just takes me back to the grace menu and then I won't see her for some time. Join again or later in the game session she'll ask again.

**Comment by packcc** [comment]
I can confirm this issue as well, only the wanderer will experience it.

**Comment by antisandwichman** [comment]
Happens to myself and my buddy as well. Only happens to player joining and not the host.

**Comment by WillCConceptSoftworks** [comment]
Can confirm, only happens to wanderer. I have only tested this with 1 wanderer.

**Comment by Corosar** [comment]
Get it as well. Only happens the first time you sit at a grace. 

Heads up. Do not accept her teleport to the roundtable hold while sitting at the roundtable hold table. It will soft lock your character till you force quit Elden ring. Have not tested if the host misting will revert the lock.

**Comment by Ed-boye** [comment]
She seems to do this pretty much for all times she chats with you at a grace as you progress on the main story

**Comment by Ed-boye** [comment]
Looks like this is pretty much a duplicate issue of this: https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/16

Closing this one so only one is tracked.
