### ISSUE TITLE
[Bug]: Inappropriate activity detected

### ISSUE THREAD

**Issue by anonymouseht973** [LukeYui/EldenRingSeamlessCoopRelease#230]
### Discord Username

anonymous973ehtnamuh#8619

### Describe the issue in detail

Immediately upon launching game I get the error message of inappropriate activity being detected, and as such the multiplayer is not at all functional near as i can tell.

### Steps to recreate the bug

[should be noted this is done on linux, i am well aware this is not intended, but i am going to note this issue anyway]
Installed everything as normal, double and triple checking. Launched the executable and got the error of: "Failed to find "SeamlessCoop//elden_ring_seamless_coop.dll" I attempted to remedy this by adding the executable to my steam library and running it through Proton. At this point, the game did launch, but I ran into the mentioned error.
I have heard of others getting this mod working on Linux using similar steps, so I am unsure of the minutia and circumstances of this issue, as well as the validity of said stories.

Please don't just respond to this by saying you don't support Linux.

### Version

1.2.4 (Latest)

### Relevant Crash log

```shell
[log details are from using: "sudo wine 'launch_elden_ring_seamlesscoop.exe'" in terminal]
0070:fixme:wineusb:add_usb_device Interface 1 has 7 alternate settings; using the first one.
0070:fixme:wineusb:add_usb_device Interface 1 has 2 alternate settings; using the first one.
0070:fixme:wineusb:add_usb_device Interface 2 has 3 alternate settings; using the first one.
Failed to find "SeamlessCoop//elden_ring_seamless_coop.dll"
Press any key to continue... 0124:fixme:heap:RtlSetHeapInformation 0000000001C00000 0 000000000011F6C0 4 stub
0124:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000011FD70

[strangely enough this was longer the first time i ran it?]
```

**Comment by LukeYui** [comment]
There's a detailed linux installation guide on the discord, have you read that?

**Comment by anonymouseht973** [comment]
I have and it did not work

**Comment by anonymouseht973** [comment]
I tried that. It didn't work.
