### ISSUE TITLE
[Bug]: Fringefolk Hero's Grave Chariot did not drop loot for all players

### ISSUE THREAD

**Issue by Fyresparxx** [LukeYui/EldenRingSeamlessCoopRelease#231]
### Describe the issue in detail

When clearing Fringefolk Hero's Grave, we finally killed the (bugged out) chariot that is supposed to drop the Erdtree Greatbow, but only the wanderer who shot the arrow got the item, the host that did not shoot the arrow got nothing. Chariots do not respawn. We did have to go rest and reset the pots twice.

### Steps to recreate the bug

Two players in Fringefolk Hero's Grave, one shoots a pot down at the end of the hidden area and it hits the chariot, which blows it up and gives loot, never to respawn again. 

### Version

1.2.4 (Latest)

**Comment by kagurazaki8472** [comment]
Please edit your post to include a bug description in the topic name. (it really helps)

**Comment by Fyresparxx** [comment]
My bad, missed that field. Fixed!
