### ISSUE TITLE
[Bug]: After turning off PVP, players can still harm the Host, but the host can't harm the Cooperators

### ISSUE THREAD

**Issue by ManaforceStudios** [LukeYui/EldenRingSeamlessCoopRelease#233]
### Discord Username

JJManaforce#4300

### Describe the issue in detail

After deactivating Judicators Rulebook, cooperators can still attack you.

### Steps to recreate the bug

- Activate Judicators Rulebook.
- Deactivate Judicators Rulebook.
- Have friend attack you.
- Notice you are unable to attack them, but they are able to attack you.

### Version

1.2.4 (Latest)

**Comment by Mic601** [comment]
Yes it a half bug because they are set to neutral not frendly. So it's basically playing with friendly fire on. All you need to do is to activate the rulebook again to go back to friendly. What's not working is that you should indeed be able to attack them.

**Comment by LukeYui** [comment]
I've failed to recreate this issue, and as the above post mentioned the rulebook cycles between 3 types of PvP:

- PvP off
- PvP on (hostile)
- PvP on (neutral)

So you have to use the book multiple times to get to different game rules. It's not ideal, and it's planned to be changed in the future. Note that with the neutral PvP, you cannot target or start aggression with other players - you can only hit them.

With that being said I'll close this issue for now.
