### ISSUE TITLE
[Bug]: Bosses completely freeze and stop fighting when Host dies

### ISSUE THREAD

**Issue by nobbinss** [LukeYui/EldenRingSeamlessCoopRelease#237]
### Describe the issue in detail

Happened both when fighting Morgot and Renala, once the host dies the bosses just stop moving and attacking giving you a free kill. Sometimes they wake up for an attack or two but then go back to doing nothing.

### Steps to recreate the bug

Host dies when fighting the boss

### Version

1.2.4 (Latest)

**Comment by Gh057-D3V** [comment]
Can confirm this is happening to me as well. With the exception that it has happened regardless of what player died. My sister and I are currently fighting malenia, and if one of us dies she simply ignores the other player. She only responds when you attack her several times and in that scenario she will hit you a few times and freeze again. Also happened with both versions of Mogh.
