### ISSUE TITLE
[Bug]: Bloody Finger Nerijus

### ISSUE THREAD

**Issue by peteryg96** [LukeYui/EldenRingSeamlessCoopRelease#238]
### Discord Username

YULidDat#7076

### Describe the issue in detail

Playing with 3 players, Nerijus can heal multiple times. Reduvia dagger does not drop after defeat.

### Steps to recreate the bug

Fight Bloody Finger Nerijus at Murkwater River.

### Version

1.2.4 (Latest)

**Comment by BrienneEmyr** [comment]
Commenting to not create a duplicate bug report but same issue/bug here. Playing with one other person, defeated Nerjus, no Reduvia drop. Version 1.2.5 [BETA]
