### ISSUE TITLE
[Bug]: Game Stuck at 100% loading after voting

### ISSUE THREAD

**Issue by humam2104** [LukeYui/EldenRingSeamlessCoopRelease#239]
### Discord Username

Dr. Smoke#3469

### Describe the issue in detail

Whenever we vote to teleport to a grace, my game loads up to 100% then gets stuck after. My friends continue while I just get stuck there.

### Steps to recreate the bug

Vote to teleport to a grace, then this happens.
Update: this only happens if there are 3 players in the session. The second player would have no issues, it's just happening with the third.

### Version

1.2.4 (Latest)

**Comment by thephenixer** [comment]
this is happening to me too in the previous updates (1.2.2 ) this might be an issue after the 1.05 update
