### ISSUE TITLE
[Bug]: Game stuck at loading screen

### ISSUE THREAD

**Issue by 3majed** [LukeYui/EldenRingSeamlessCoopRelease#245]
### Describe the issue in detail

We are 3, so when we join together and do a boss fight and wipe, the host and one of us will load back but the 3rd guy will get stuck at the loading screen and needs to ALT+F4. Not only that but also the host needs to close the session and reopen it again so the guy who ALT+F4 can rejoin again.

### Steps to recreate the bug

None as I know

### Version

1.2.4 (Latest)

**Comment by 3majed** [comment]
Also, we already passed Margit but Mellinia still show up every time we use a grace, even thou we already talked to her and went to the table multiple times

**Comment by humam2104** [comment]
> Also, we already passed Margit but Mellinia still show up every time we use a grace, even thou we already talked to her and went to the table multiple times

It's better practice to talk about this in another comment.
Also, I've just talked about this same problem here:
https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/239
