### ISSUE TITLE
[Bug]: "Failed to save game Save data is corrupted"

### ISSUE THREAD

**Issue by Tweakiel** [LukeYui/EldenRingSeamlessCoopRelease#247]
### Discord Username

Nyquielz#1067

### Describe the issue in detail

Not me but a friend is trying out this mod its saying "Failed to save game Save data is corrupted". verified files, reinstalled mod, vanilla elden ring is working fine 
![image](https://user-images.githubusercontent.com/107739190/174421054-9275ed59-ec0c-4a6b-9d4d-b13372afb319.png)

### Steps to recreate the bug

no idea, mods including class talisman and seamless coop were installed multiple times and still no progress

### Version

1.2.4 (Latest)

### Relevant Crash log

```shell
Faulting application name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0x1c88
Faulting application start time: 0x01d882c2c4bc2462
Faulting application path: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 3ecea142-29ea-4748-815f-fe00e0af2e1d
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by BosForPresident** [comment]
Don't know if this wil help. but this is a video about this kind of problem. maybe just try it? https://www.youtube.com/watch?v=6Kha_xpAQMM&t=33s

**Comment by Tweakiel** [comment]
hmm maybe but it wouldnt make sense to fix a "corrupt save file" when there hasnt been a save file made yet for the coop mod. However, Elden Ring with no mods seems to run fine even after creating characters and loading previous saves. maybe ill give it a try.

**Comment by sdo91** [comment]
I am having the same issue

**Comment by Tweakiel** [comment]
hopefully we can find a fix soon but heres a list of fixes that we have tried:

- Clean installation of elden ring and versions 1.2.4 & 1.2.5 for seamless Coop mod.
- Tried using Mod Engine 2 to install Seamless Coop
- Deleting saves for vanilla elden ring and turning off steam cloud saves
- Using HxD (hex editor) to manually change lines of code to fix "corrupted" save files of Elden ring.

**Comment by Spacarar** [comment]
+1 same issue. Deleting all the saves I have in my save folder didn't solve this issue, and neither did editing the .co2 file as described in the video.

**Comment by Spacarar** [comment]
to add to my specific issue. I was trying to use the `class talismans` mod as well. for some reason my friend (who literally had an exact copy of my `regulation.bin`) had no issues, but whenever I launched the game with the modded regulation.bin I had this issue. with the default regulation.bin everything worked fine.

so in the end we decided to just play without the class talismans mod, but I wonder if the two are correlated somehow

**Comment by Tweakiel** [comment]
so we found a solution for those having this bug. we disabled steam cloud on the Elden ring properties AND disabled steam cloud completely. now, if you want to save your vanilla saves, I recommend making a backup of them because in our case we just deleted ours (they are located in C:\Users\*username*\AppData\Roaming\EldenRing) everything in the folder with a bunch of numbers will contain your save files with some steam cloud stuff and a backup file.

Once you've backed up/deleted everything in your save file folder, you need to disable the steam cloud on Elden Ring by unchecking the box shown in the picture below.
![image](https://user-images.githubusercontent.com/107739190/175659925-5b8af1ce-c369-4b72-a30f-27770cdb6d97.png)

Then, go to steam settings by clicking the steam text in the top left of the steamapp, then settings, then cloud and uncheck the first box. 
![image](https://user-images.githubusercontent.com/107739190/175660711-ae22e0bd-a50c-4574-9bed-299a12ccec0c.png)

This solution worked with and without the _class talisman _mod__. Try Launching the game normally (no mods, vanilla regulation.bin) first, then check your savefiles. if they are still there, try deleting them (IF YOU ALREADY HAVE THEM BACKED UP or you don't care about your vanilla saves). After, try launching with seamless coop (and class talisman mod if you are using) and this should be okay as long steam cloud isn't trying to backup your saves. 

*this worked for my entire group of 5 as we eventually got this exact bug/error over time* and HOPEFULLY IT WORKS FOR YOU GUYS TOO. I won't close this thread in the case someone finds a better solution or cant get it to work even after trying this method. GLHF with seamless Co-op
,
