### ISSUE TITLE
[Bug]: Game crashing in solo play on save load after going to Renalla with Co-Op

### ISSUE THREAD

**Issue by ThePandaBadger** [LukeYui/EldenRingSeamlessCoopRelease#256]
### Describe the issue in detail

I went to Renalla's grace in Co-op as a wanderer for my friend to re-spec. Before he opens to menu to commit to re-specing my game crashes to desktop. From then on whenever I load the save (Never making it to co-op again) it crashes as soon as it loads in to the game. Unable to play that save whatsoever.

### Steps to recreate the bug

Start game, join co-op, go to Renalla post fight and post Radahn, have host talk to Renalla, wanderer game crash, save bug.

### Version

1.2.4 (Latest)

### Relevant Crash log

```shell
Faulting application name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Faulting module name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Exception code: 0xc0000005
Fault offset: 0x0000000000234619
Faulting process id: 0xbd04
Faulting application start time: 0x01d883686b35b0b0
Faulting application path: C:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: C:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Report Id: b4e2c367-a5d8-470a-9b35-597047f679ab
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by beeofdoom** [comment]
I've encountered this as well.  Oddly it affects my wife's save only.  My save is unaffected.  
I have been hosting, she has been a Wanderer.

**Comment by beeofdoom** [comment]
I was able to work around this by restoring a working save from my account, and instead of warping to the Renalla site of grace, starting from the Debate site of grace, running over and resting.  No more crashing on startup.
