### ISSUE TITLE
[Bug]: Enemies highly resistant to bleed. Boss health scaling also overtuned

### ISSUE THREAD

**Issue by Kiruna** [LukeYui/EldenRingSeamlessCoopRelease#257]
### Discord Username

Aragil#8074

### Describe the issue in detail

With two players, using uchigatanas or other early bleed weapons, players are unable to bleed bosses (e.g. Margit, Tree Sentinel). Due to increased health scaling vs base Elden Ring, gameplay could be seen as even harder rather than easier or as-intended. 

Opinion: If intentional, for scaling or balance, recommend changes be communicated via patchnotes or in mod description, or left to other mods/player choice for modification. Implementation of an INI or similar config file for player to access these values would greatly improve the player experience. Values can still default to dev-preferred levels for balance but leaves room for individual experience tuning.

### Steps to recreate the bug

Fight any early game enemy (e.g. Margit, Tree Sentinel) with an applicable early game bleed weapon (e.g. Bandit's Knife, Uchigatana, Reduvia) during 2p coop. Players will experience high bleed resist from the enemy. Players will also see abnormally high health pools compared to official game coop.

### Version

1.2.4 (Latest)

**Comment by GregoryChekjin** [comment]
Upon my own personal investigations into the matter, I find similar issues with the current balance of enemy scaling. Would recommend looking into the issue.

**Comment by LukeYui** [comment]
Hi, hope you're well. For 2 players, the scaling is greater than that of the base game but not by a lot. 

For only 2 players, I didn't change status effect resistance of bosses at all. Their health was increased, but only by a minimal amount (~20% more than 2 player co-op in vanilla).

I'll mark this as more of a QoL issue as the scaling is working at intended. Once the mod is stable I may add customisable scaling in the future.

**Comment by thedearbluejay** [comment]
Any update on the custom scaling options? It would be fun to customize this.
