### ISSUE TITLE
Sites of Grace not in correct locations, sometimes not there at all for Wanderer.

### ISSUE THREAD

**Issue by packcc** [LukeYui/EldenRingSeamlessCoopRelease#26]
While playing with 1 wanderer, going to a site of grace shows the grace, but there is no activation. Sometimes you can move around and find that the grace is not exactly where it should be, 3-10 meters away. Sometimes they cannot access the grace at all.

**Comment by notshux** [comment]
This is related to a previous reported bug with going to the Roundtable hold, the best way the cooperator to avoid this bug is just by not going to the Roundtable Hold with the host (I recommend having them go to the Roundtable in their session if they need to and rejoining host session after)

**Comment by Neofaucheur** [comment]
I've encountered this bug several during regular gameplay (and twice with the mod). So I don't think that's related to the mod specifically, that's just a bug in the base game.

In case the mod actually has a relation with this bug, I've only ever encountered it on Grace that spawn after defeating a boss. Makar Wyrm and Haligtree Promenade (Loretta) sites in solo, and Morne Moangrave (Leonine Misbegotten) and Margit, the Fell Omen with the mod.

**Comment by simonfuhrmann** [comment]
We had this issue yesterday while playing. We even restarted the game and the issue persisted, i.e., not necessarily just caused by being in the roundtable hold? We couldn't get rid of the issue. Grace was always shifted by 3 to 10 meters for the wanderer only, not the host.
