### ISSUE TITLE
[Bug]: Lock on stops working sometimes during a boss fight

### ISSUE THREAD

**Issue by Tolnin** [LukeYui/EldenRingSeamlessCoopRelease#261]
### Discord Username

Tolnin#0509

### Describe the issue in detail

Sometimes when you're fighting a boss, you lose the ability to lock on and you don't get it back

### Steps to recreate the bug

Fight bosses and try to lock on

### Version

1.2.4 (Latest)

**Comment by Starzilla29** [comment]
This might be related to the other target lock bug. Is it during horseback riding?

**Comment by Tolnin** [comment]
I never paid attention to if I was on horseback while it happened but you
might be right, I'm not sure

**Comment by finncelta** [comment]
it was on horseback during the radahn fight for me, seems a likely reason

**Comment by Inverness** [comment]
I've been having the same issue myself. I notice it happening when on horseback. This time the 4 of us were fighting the Glintstone Dragon.

This is a really killer bug that cripples our ability to fight bosses sometimes.
