### ISSUE TITLE
[Bug]: 3/4 players entered an evergaol

### ISSUE THREAD

**Issue by SirDifferential** [LukeYui/EldenRingSeamlessCoopRelease#263]
### Discord Username

Gekko#7652

### Describe the issue in detail

With 4 players, when the first player started the vote to enter an evergaol, suddenly 3 out of 4 players teleported inside the evergaol without the vote taking place and 1 was left to roam the outside. In middle of the fight, everyone suddenly respawned at the starting positions in the evergaol and the fight restarted, but the 4th player was still outside. After this bug, all players had issues with the map teleport system saying there were votes going on for locations we weren't voting for.

### Steps to recreate the bug

Unsure. With 4 players, have one try entering an Evergaol.

### Version

1.2.4 (Latest)

**Comment by Sonicus** [comment]
One addition: one of the three players who got in was permanently stuck in a kneeling position at the center of the Evergaol, could only spin around and was invulnerable. That player was forced to Alt+F4 out of the game.
