### ISSUE TITLE
[Bug]: Invalid network message: ?NetworkMessage?

### ISSUE THREAD

**Issue by SirDifferential** [LukeYui/EldenRingSeamlessCoopRelease#265]
### Discord Username

Gekko#7652

### Describe the issue in detail

With 4 players connected, occasionally the guest players get a message on their screen with "?NetworkMessage?" as the message string. For the host player the messages show properly. These appear to be any messages (players joining, dying, leaving, etc.).

### Steps to recreate the bug

* Have 4 players connected
* Produce some kind of message that shows for all players. Occasionally happens.

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Hi, thanks for the report. This bug occurs when you're in a party of > 2 players, and one of the guest players dies for the first time. I'd forgotten to correct it, so thank you for reminding me. I'll fix this for the next version.
