### ISSUE TITLE
[Bug]: Coop partner becomes invisible when on Torrent

### ISSUE THREAD

**Issue by Blindfury11** [LukeYui/EldenRingSeamlessCoopRelease#269]
### Discord Username

Blindfury#4916

### Describe the issue in detail

When either of us uses Torrent, our character stays stuck in place in a running motion while the player actually become invisible. The player's name flickers at the location they actually occupying. Moving and getting off Torrent will make the character reappear in the place where the player dismounted.

### Steps to recreate the bug

Get on Torrent and move around

### Version

1.2.4 (Latest)

**Comment by zimablue666** [comment]
My friend and I also faced this problem. The following happened: 
1. we walked together from the chapel of anticipation 
2. we received Torrent from Melina 
3. after that, we straddled Torrent and for each other we were stuck in one place and were invisible. 
5. The problem disappeared after restarting the session

latest mod version: 1.2.5

**Comment by Ginnel** [comment]
This is game breaking for me and my online buddy, existing game save, everything worked fine with previous versions now when either of us get onto Torrent it looks like the other player is running in place on torrent and also a flickering appearing version of where we should be. Tested in Liurnia lakes south had initially logged in from roundtable hold.

**Comment by Blindfury11** [comment]
> My friend and I also faced this problem. The following happened:
> 
>     1. we walked together from the chapel of anticipation
> 
>     2. we received Torrent from Melina
> 
>     3. after that, we straddled Torrent and for each other we were stuck in one place and were invisible.
> 
>     4. The problem disappeared after restarting the session
> 
> 
> latest mod version: 1.2.5

That's exactly how it happened to us. We got Torrent at the same time and immediately tried to ride it, which caused the strange bug.  And just like you, we tried again tonight and it was fine. We didn't think of restarting the client since we were already calling it a night.

**Comment by Blindfury11** [comment]
> This is game breaking for me and my online buddy, existing game save, everything worked fine with previous versions now when the person hosting the game gets onto Torrent it looks like they are running in place on torrent and also a flickering appearing version of where we should be. Tested in Liurnia lakes south had initially logged in from roundtable hold.
> 
> mod version 1.2.5

Yes, that was the problem. But seems a restart fixed it for us? I will report back if the bug re-appears on subsequent play time.

**Comment by NeoBlizzard** [comment]
My friend and I also experience this from time to time (latest mod ver). 
When it happens I'm left following a flickering nameplate at ground level while his body and torrent are riding in the air above the nameplate. 
Sometimes ending the session (host included) and reopening/rejoining fixes it, sometimes not.

It seems to happen more frequently in some areas than others for me though. E.g.:  Nokron and some parts of Siofra River.
The only thing I can see in common between areas it tends to happen in is the areas have a lot of different levels (heights) to them.
Will see if I can get my buddy to help me test if it has something to do with mounting while at different heights on the map and/or far apart.

**Comment by majineko** [comment]
I noticed this happening when my friends mount died and required a flask to revive. Every time he mounted up I heard the mount die again, and he would go invisible. Not sure if it was the actual cause or not.

**Comment by DannyDarth** [comment]
This issue happens for me and my friends all the time. Mainly to the host i believe. Where the horse disappears and then the other players look like they are riding in place until they get off torrent.

**Comment by prrawls** [comment]
Having this same issue as well as host I cannot see my friend they can see me.. can’t coordinate mounted combat due to issue.

**Comment by nrardin** [comment]
My dad and I are having the same problem in 1.3.0. We've been playing on the same network with a 20-30ms ping. 

1. Both players get on horse, one or more freeze in place and the other player can't see you riding around.
2. Getting off the horse will make you reappear to the other player. 
3. This can happen to the host or the wanderer. 
4. Restarting will sometimes fix the issue.
