### ISSUE TITLE
[Bug]: Unable to exit the game if hosting and wanderer leaves

### ISSUE THREAD

**Issue by NeoBlizzard** [LukeYui/EldenRingSeamlessCoopRelease#273]
### Discord Username

NeoBlizzard#8377

### Describe the issue in detail

After opening the game for a wanderer to join, if the wanderer leaves it can lead to a scenario where the host needs to alt+f4 to exit the game as the "exit game" or "exit to desktop" options are greyed out.

### Steps to recreate the bug

Load into game.

Use grey pot to open game for wanderers to join.

Play for some time after wanderer joins.

Have wanderer exit using severed finger.

Host hits esc and goes to system, then checks exit game or exit desktop options (they are not available).

### Version

1.2.4 (Latest)

**Comment by LukeYui** [comment]
Hi, you must use the separation mist (then wait a few seconds) even as a host to disband your party. You cannot quit the game whilst in a session.
