### ISSUE TITLE
[Bug]: Receiving boss souls repeatedly

### ISSUE THREAD

**Issue by th3d4v1d** [LukeYui/EldenRingSeamlessCoopRelease#274]
### Discord Username

The Underking#0949

### Describe the issue in detail

Playing with a party of 3, and it happens mostly to only me (not the host). We killed Radahn a couple of days ago. When I join the host, I get Demigod Felled event and receive 84000 souls. If I sit on a grace, or my friends do, I get the event again, and start amassing hundreds or souls. At one point I had a million souls lol.

It doesn't just happen with Radahn, that was just an example. Happens with some other bosses to, Enemies and Greater Enemies too.

### Steps to recreate the bug

Not sure how it's recreated. Maybe every time a boss is killed, I was spectating, and wasn't alive. Maybe that's the reason? Maybe if I stay alive when a boss dies, it doesn't cause the issue with that boss's soul receiving mechanic?

### Version

1.2.4 (Latest)

**Comment by NorbertoDc** [comment]
Part 2; Cant level up....
https://youtu.be/fe4x0aZJYwI
