### ISSUE TITLE
[Bug]:Guardia Real Loretta (infinite runes bug)

### ISSUE THREAD

**Issue by NorbertoDc** [LukeYui/EldenRingSeamlessCoopRelease#278]
### Discord Username

Norby#2369

### Describe the issue in detail

In loretta's first confrontation, when defeating her in co-op with 2 people (own experience), the host can only sit in grace, reciting the death of the boss and giving the guest the runes when defeating the boss every time the host sits in grace.

### Steps to recreate the bug

1.- Deffeat loretta in co-op (2players or more)
2.- the host sits in grace first .
3.- done .

https://youtu.be/6ZtfqpWN_Uw

### Version

1.2.5 (Latest)

**Comment by NorbertoDc** [comment]
Part 2 : Cant level up... my friend go outside the boss arena to the next grace, and teleport us to Ranni's tower and still bug wining Loretta souls 10k runes per sitting in the grace and cant level up. like the first time you meet Malenia . 
https://youtu.be/fe4x0aZJYwI

**Comment by haydenhayden011** [comment]
This can happen with every boss, especially if someone crashes right after a boss is killed. Happened with borealis, and the tree knight for me
