### ISSUE TITLE
Can't quit game

### ISSUE THREAD

**Issue by KentGrigo** [LukeYui/EldenRingSeamlessCoopRelease#28]
While using the mod, the button for quitting the game is not usable.

**Comment by LukeYui** [comment]
You can't quit out while you're in a party. Everyone has to use the separating mist (even the host) before quitting out, have you tried this?

**Comment by KentGrigo** [comment]
No, not yet. We'll try it out the next time that we play co-op. 
Would you like me to close this issue when I've confirmed it or just close it now?

**Comment by LukeYui** [comment]
If you're still having problems let me know, otherwise feel free to close it!

**Comment by ansharzero** [comment]
I'm also still having this issue. I thought to try using separating mist, but that doesn't work for the host. The person joining the game is able to quit when separating, but the host stays unable to quit normally even after using mist, and teleporting around and sitting at different saves. I've seen the quit game button become usable again after this glitch going off, but not sure what triggered it to correct itself.

**Comment by WillCConceptSoftworks** [comment]
I have this issue. I can quit out before I use the "tiny great pot". Once I use the "tiny great pot", I am unable to quit.
