### ISSUE TITLE
[Bug]: DC after Radahn victory

### ISSUE THREAD

**Issue by maraudah** [LukeYui/EldenRingSeamlessCoopRelease#281]
### Describe the issue in detail

During the Radahn fight, the host survived and killed Radahn, The other person died during the fight. When the fight ended, the falling stars cutscene played only for the host. The other person was stuck spectating the host while the host viewed the cutscene. After the cutscene ended, the host was awarded the normal loot from Radahn + runes. The other person got kicked from the session, and received no reward or runes, even upon rejoining.

### Steps to recreate the bug

2 Players. 

The friend died during phase 1.
Host survived to the end of the fight. Finishing blow dealt by summoned NPC. Host was on horse during victory.

### Version

1.2.5 (Latest)

**Comment by Rebel1713** [comment]
+1 on this, also bugged when host dies. Both parties receive loot, but host is not rewarded runes
