### ISSUE TITLE
[Bug]: Friends not able to join my world after the latest update (June 19th)

### ISSUE THREAD

**Issue by Tolnin** [LukeYui/EldenRingSeamlessCoopRelease#282]
### Discord Username

Tolnin#0509

### Describe the issue in detail

My friend tried loading into my game, and it would go through the loading screens and all that, but it didn't put him in my world

### Steps to recreate the bug

Go into the game and have your friend try to join you

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment]
can confirm that's a big problem.
it always takes like 3 tries to get to the host's world and after like 10 minutes (or when someonw dies) it just kicks them like what the hell

**Comment by Tolnin** [comment]
> 

Yeah this only started happening to me and my friends after updating the mod to 1.2.5, no other factors changed

**Comment by LukeYui** [comment]
Matchmaking is done via Steam, as is forming the peer-to-peer connections. If you're having connection problems, try adjusting your firewall settings.

Unfortunately there's very little I can do if your connection is unstable.
