### ISSUE TITLE
[Bug]: Ranni disappears from the church of Elle

### ISSUE THREAD

**Issue by zimablue666** [LukeYui/EldenRingSeamlessCoopRelease#284]
### Describe the issue in detail

My friend and I are faced with the following problem:
We moved to the Church of Elle through fast travel. For the session host, Ranni appeared in the church, at that moment there was still a loading screen for me. As soon as I also appeared at the site of grace, Ranni disappeared for both of us, and the pillars of the church collapsed. So we could not talk to her and get the Spirit Calling Bell. My friend tried to have time to talk to ranni while I was still on the load screen after choosing a site to tp. This is how he managed to get a bell, and then item appeared in place of Ranni for me as well. There was no dialogue with ranni for me

### Steps to recreate the bug

1. Move to the Church of Elle through voting for the site for tp. 
2. Wait for the second participant of the session to appear at the site of grace. 
3. Ranni disappears.

### Version

1.2.5 (Latest)

**Comment by finncelta** [comment]
Ranni won't be at the church of elleh once you've reached roundtable hold, one of you was already there and because of elden rings consensus mechanism she won't appear at the church anymore.

**Comment by zimablue666** [comment]
Thank you for your reply! None of us have been to the round table yet, we traveled together from the chapel of anticipation, received Torrent and then returned to the church of elle

idk how important this is, but due to a bug with invisibility on a horse, we restarted the session. At first I was the host, and then my friend. We got Torrent in the session when I was the host and then returned to the church of elle in a new session

**Comment by nacitar** [comment]
This happened to me yesterday; neither character had been to round table hold, started at the same time and traveled together the entire time.  Host loaded, saw Ranni, cooperator loaded slowly and pillars broke and Ranni disappeared.  We had simply fast traveled back to the church after getting torrent from the gatefront and then riding over to free Boc from the bush.

**Comment by brettberger** [comment]
My friend and I also experienced this yesterday.  His system uses an HDD and I a SSD so he always spawns a bit after me.  We had both just obtained Torrent and headed back to the church at night (needs to be night to spawn Ranni).  It also seems that you have to fast travel in to spawn her but I'm not completely certain.  We had trouble spawning her so tried a few things.  We went a ways away and fast travelled in to the church and then she spawned for me when I appeared.  When my friend loaded I was in conversation with Ranni but she immediately despawned before I had a chance to get the bell.  We ended session and tried again... this time I made it through the dialog before she despawned and I get the bell.  My friend never saw her but the bell was available for pickup in the spot that Ranni spawns.

**Comment by AlbanMarku** [comment]
I too get this bug. Haven't got to the roundtable yet. When my partner loads in after me, (slower load times because of specs) Ranni despawns even during a conversation.
