### ISSUE TITLE
[Bug]: spell damage behaves strange

### ISSUE THREAD

**Issue by finncelta** [LukeYui/EldenRingSeamlessCoopRelease#285]
### Discord Username

speedowagon#0001

### Describe the issue in detail

Using spells as a wanderer is currently less than viable. A lot of damage during comet azure gets represented in the damage numbers and subtracted from the boss healthbar but once the spell ends, part and sometimes all of the damage gets reset. This occurs on almost any spell that does tick damage and on some that don't.

### Steps to recreate the bug

Try to damage any boss using comet azure as a wanderer.

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment]
Happened to our party aswell!
Seems like there was some desync between us- we fought the same enemy( some kinda miniboss that doesn't respawn) and i saw him at a difference place but near it's nest while the host and the other wanderer could see him in it's right place.
The outcome was that the host and the other wanderer could inflict damage like usual, but when i inflicted damage the boss would just regenerate back it's lost HP from my attacks.
