### ISSUE TITLE
[Bug]: Wanderer run in place

### ISSUE THREAD

**Issue by Hagure32** [LukeYui/EldenRingSeamlessCoopRelease#286]
### Describe the issue in detail

during fight with boss general Radhan player that play as wandered seen walk in place by the host and if the character got hit at the host side the wanderer will also take damage from their side even though the character position is so far away from the boss.
i test it by reverting the mod to the previous version the problem is gone . . 

### Steps to recreate the bug

just initiate the fight normally

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment]
Actually this bug can occur anywhere really, usually though when the wanderer gets too far away from the host or when someone goes AFK

**Comment by Hagure32** [comment]
really ? i dont know if its a common bug coz i never encounter this problem on the previous version and i been using the mod since day one . . lol

**Comment by Hagure32** [comment]
> Actually this bug can occur anywhere really, usually though when the wanderer gets too far away from the host or when someone goes AFK

really ? i dont know if its a common bug coz i never encounter this problem on the previous version and i been using the mod since day one . . lol

**Comment by Yoni0040** [comment]
The first time I encountered this was when me and the host investigated the divine tower of caelid while our 3rd guy went AFK (he does this a lot) after about 10 minutes we were already inside the tower while he was outsite on a grace really far and he said he saw us beneath him running around on the ground- which means he sees us ruuning in place and the 2 factors i can see is that either he was AFK which made this desync or maybe he was too far away from the host that he stopped syncing with us.

**Comment by LukeYui** [comment]
As above, known issue that occurs when players are far away. Visual bug because the game needs to keep the player loaded even when far away.
