### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by grandflumul** [LukeYui/EldenRingSeamlessCoopRelease#287]
### Describe the issue in detail

I was hosting the game (2 players).

We entered Raya Lucaria academy and after taking the elevator to enter, my camera displayed a visual glitch (the one where you can't see anything, as though your camera was stuck in a wall).

We fast traveled to the previous site of grace, and my game crashed.

Now, when I try to load my save file, the loading is extremely slow, and it stops at roughly 80% of the progression bar.

I can still navigate through tips in the loading screen, so the game must not be frozen.

If i start a new game, it works correctly. Perhaps something wrong with my save file ?

### Steps to recreate the bug

no idea.

### Version

1.2.5 (Latest)

### Relevant Crash log

```shell
Fault bucket 2181498661119218345, type 5
Event Name: AppHangB1
Response: Not available
Cab Id: 0

Problem signature:
P1: eldenring.exe
P2: 1.5.0.0
P3: 6295c83c
P4: 6899
P5: 67246080
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCEA3.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\Critical_eldenring.exe_2fd6396c887d07686b6964b79e04be96271b21b_f69f5cf6_b1ac856f-87fd-4622-ba5f-b600087d2ec8

Analysis symbol: 
Rechecking for solution: 0
Report Id: eb7d18e2-52c5-4f7d-b77e-e6e79b77ce94
Report Status: 268435456
Hashed bucket: 95561c8e67eccb608e463d79660052a9
Cab Guid: 0
```

**Comment by loko-99jkjk** [comment]
Just happned to us as well , the host entered Raya Lucaria and got this bug.

**Comment by grandflumul** [comment]
> Just happned to us as well , the host entered Raya Lucaria and got this bug.

Oh ok so it wasn't just me.

Hopefully next patch will fix that.

I believe in you, devs.

**Comment by loko-99jkjk** [comment]
It might or might not be a game bug cuz verefying steam files seems to fix it ?

**Comment by LukeYui** [comment]
This is a bug with the vanilla game. As above, verify your game files with Steam to fix it.

**Comment by grandflumul** [comment]
> This is a bug with the vanilla game. As above, verify your game files with Steam to fix it.

Sorry, my mistake.

Thank you very much for the support, you guys are awesome. Having such a good time with my friend with this mod.

Love you
