### ISSUE TITLE
[Bug]: Sacred tear flask reset

### ISSUE THREAD

**Issue by aliioop** [LukeYui/EldenRingSeamlessCoopRelease#288]
### Describe the issue in detail

My flask is reset to +1, which normally wouldn't be such a big deal for me, it's just me and my boyfriend are at the very end of the game and its making boss fights really really hard! I know people have reported this bug but idk if there's been any solution yet. We updated to the newest version of the mod but it hasn't fixed itself yet.

### Steps to recreate the bug

I noticed my heals not working very well but didn't know something was actually wrong until my bf pointed it out. so i don't know exactly where or when it happened

### Version

1.2.5 (Latest)

**Comment by LukeYui** [comment]
Duplicate of #109
