### ISSUE TITLE
[Bug]: Rya doesn't teleport the player to Volcano Manor

### ISSUE THREAD

**Issue by TinaKropaneva** [LukeYui/EldenRingSeamlessCoopRelease#295]
### Discord Username

Bookish Swearwolf#3721

### Describe the issue in detail

I did Rya's quest (return her necklace) in my world (1.2.2 then), and then we did it again in host's world (ver. 1.2.4, Rya wasn't present for me, only for the other two players, so I didn't get duplicate invitation or something like this). Then I was playing the game in single player mode again on ver 1.2.5, got through mines to Altus Plato and met Rya at Lux Ruins (Erdtree gazing hill site of grace). I talked to her and touched her hand when she offered to teleport me to Volcano Manor, but nothing happened, she just let go of my hand, and I could start the dialogue all over again. Tried this several times, then renewed the location by resting at the site of grace, after that Rya disappeared. 

It may be important: The Grand Lift of Dectus was already opened before I got to the mines or even met Rya for the first time. 

I got to Manor by foot in the end, so after all this is not a game breaking bug, but it was a little upsetting, so I decided to tell you.

Huge thanks for the mod!

### Steps to recreate the bug

1. Start a single player mode 
2. Meet Rya and return her necklace
3. Get invitation to Volcano Manor
4. Go through the mines, kill Makar and reach Erdtree gazing hill Site of Grace
5. Talk to Rya, agree to get teleported to Volcano Manor

### Version

1.2.5 (Latest)

**Comment by PanTheRandomness** [comment]
We also have tha same problem!
Did the same as you and ended up going there by foot.
