### ISSUE TITLE
How to import seamless coop save game files?

### ISSUE THREAD

**Issue by tristan-k** [LukeYui/EldenRingSeamlessCoopRelease#296]
### Discord Username

tristank#0470

### Describe the issue in detail

How do I import save game files from one seamless coop installation to another?

It seems seamless coop can't pick up my save files from another seamless coop installation. The seamless coop versions are the same on both systems. 

Could be related to https://github.com/LukeYui/EldenRingSeamlessCoopRelease/issues/175

### Steps to recreate the bug

I tried copying the folder at `%appdata%/roaming/eldenring/76561198344986887/` but a new folder gets created. I also tried replacing the files `ER0000.co2` and `ER0000.co2.bak` from `%appdata%/roaming/eldenring/76561198344986887/` to the newly created folder but then I'm getting an error saying `Failed to load save data`.

<img width="1298" alt="Bildschirmfoto 2022-06-21 um 19 46 27" src="https://user-images.githubusercontent.com/732025/174867825-1d24573f-db0a-414a-aceb-aece433d5797.png">

### Version

1.2.5 (Latest)

**Comment by LukeYui** [comment]
Sorry I don't understand the question? The long number (76561198344986887) is your SteamID and is unique to your account, I'm not sure exactly what you're trying to do.

**Comment by tristan-k** [comment]
I'm trying to import a save game from a seamless coop installation on PC `ABC` to a new PC `XYZ` with seamless coop. 

PC `ABC` does have the SteamID = `76561199102255298`
PC `XYZ` does have the SteamID = `76561198344986887`

If I copy the folder `76561199102255298` from PC `ABC` at  `%appdata%/roaming/eldenring/76561199102255298` to  PC `XYZ` at  `%appdata%/roaming/eldenring/76561199102255298` I'm unablet to load the Elden Ring character with `Load Game` in the Elden Ring game menu because it's not there.

If I copy and replace the content (`ER0000.co2` & and `ER0000.co.bak2`) of folder `76561199102255298` from PC `ABC` at  `%appdata%/roaming/eldenring/76561199102255298` to  PC `XYZ` at`%appdata%/roaming/eldenring/76561198344986887` I'm then greeted by an error saying `Failed to load save data` and I can't even quit the game in the Elden Ring game menu.

**Comment by tristan-k** [comment]
I found the solution. It wasn't related to seamless coop. Sorry about the noise.
