### ISSUE TITLE
how do i use cheat engine?

### ISSUE THREAD

**Issue by RedAnimationsYT** [LukeYui/EldenRingSeamlessCoopRelease#3]
i have transfered my save file correctly but i just don't have the items, any help would be much appreciated

**Comment by SeanSobey** [comment]
To convert saves over from base game:
1.  Open folder `%AppData%\EldenRing\[Folder with 17-digit number]`.
2. Delete existing *.co2 and *.co2.bak of they exist (created if you have launched the mod already).
3. Copy and rename the *.sl2 and *.sl2.bak to *.co2 and *.co2.bak respectively.

To add the multiplayer items to your save:
1. Download and install [cheat engine](https://www.cheatengine.org/downloads.php) (I had to disable windows defender to install and run).
5. Download and extract [this](https://cdn.discordapp.com/attachments/947957866436894790/968809974098706442/eldenring_all-in-one_Hexinton_v2.00_ce7.4.zip) cheat table (originally from [this](https://youtu.be/y0lsualedu0) youtube video which shows how to use it).
6. Start Elden Ring via the mod launcher and continue your save so you are in game.
7. Open Cheat Engine.
8. Click 'Select a process to open' and select the Elden Ring process.
9. Select 'Open a cheat table' and select the extracted `eldenring_all-in-one_Hexinton_v2.00_ce7.4.ct`.
10. Navigate to the ItemGib script as shown in the screenshot:
![Elden Ring Cheat Engine](https://user-images.githubusercontent.com/6775902/170887951-a51e3bdc-6ca0-4565-a7e0-a06459886b61.PNG)
11. In the `ID` field enter the id for each of the 4 items and press `Gib` (it will look like nothing happened):
  - Tiny Great Pot - 0x40000000
  - Effigy of Malenia- 0x4000000A
  - Separating Mist - 0x4000000B
  - Judicator's Rulebook - 0x40000014
In game it should say you received the items.

**Comment by LukeYui** [comment]
I'll close this for now, thanks for the reply. 

v1.0.1 should make it so the items are given to you automatically if you don't have them on your character.
