### ISSUE TITLE
1.1.0 flagged with virus, probably false positive

### ISSUE THREAD

**Issue by michael-robertson** [LukeYui/EldenRingSeamlessCoopRelease#30]
According to Defender:
```
Detected: Trojan:Script/Oneeva.A!ml
```
Same with the Nexus download and github package.
I expect it's an accidental pattern match, but just making sure something nasty didn't creep into the latest build. 

Has anyone else seen this?

Awesome mod. The wife and I are enjoying it immensely.

**Comment by LukeYui** [comment]
I think it's likely the launcher that's flagging it. It's a branch of the offline launcher (https://github.com/LukeYui/launch_modded_eldenring) and essentially just acts dll injector for the mod

**Comment by michael-robertson** [comment]
That figures. Anyway, I scanned it with Malwarebytes and that one cleared.
