### ISSUE TITLE
[Bug]: when i died all of my stats went down by one

### ISSUE THREAD

**Issue by garntyblue** [LukeYui/EldenRingSeamlessCoopRelease#300]
### Describe the issue in detail

when i was playing as wretch when i died to the tree sentinel all of my stats went down by one and i couldn't weald my club anymore 

### Steps to recreate the bug

die

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment]
This is caused by a feature of the mod to punish those who can respawn and continue fighting.
There are many types of debuffs and you get one by dying while being in a session (shouldn't be possible in solo mode).
You can remove them by resting at any site of grace.
This is not a bug
