### ISSUE TITLE
[Bug]: Deathroot does not sync between singleplayer and multiplayer

### ISSUE THREAD

**Issue by LEEJER** [LukeYui/EldenRingSeamlessCoopRelease#305]
### Discord Username

[ 𝔼𝕔𝕝𝕚𝕡𝕤𝕖 𝕀𝕍 ]#3944

### Describe the issue in detail

I gave one deathroot to the beast clergyman on my friend's world (multiplayer). 
Later, on my own world (singleplayer), i killed a boss and got another deathroot, which i gave to the beast clergyman again.

I expected to receive the bestial sling incantation, since I have the beast clergyman a total of 2 deathroot.

What happened was that I received nothing for the second deathroot (i think it tried to give me the first reward again).

### Steps to recreate the bug

While playing co-op obtain a deathroot and turn it in to beast clergyman. (I was playing with 2 other people).
The deathroot was from Tibia Mariner at Summonwater Village

Then, leave co-op (return to singleplayer), obtain a deathroot and turn it in to beast clergyman.
The deathroot was from Tibia Mariner at East Liurnia of the lake.

### Version

1.2.5 (Latest)

**Comment by Judges331** [comment]
Confirming this bug. I lost out on my second and third received deathroot by the Beast Clergyman only promising to give me the eye and claw, which is a shame, as this character was to be entirely built around these incantations.

**Comment by mmccloud1597** [comment]
Hey there, getting the same issue on our end. We both got the first two items since we got them at the same time, but in our next session we got nothing when giving one (up to three, now).

**Comment by jhyeazy** [comment]
Same issue. Note: I gave my first deathroot to Garanq before downloading the mod. Second afterward, no reward
