### ISSUE TITLE
[Bug]: Broken character after defeating Istvan for the Volcano Manor without host. (And other less game breaking bugs.)

### ISSUE THREAD

**Issue by VoilaTada** [LukeYui/EldenRingSeamlessCoopRelease#307]
### Discord Username

Voila#4111

### Describe the issue in detail

I was in my friend's world and we went to fight Istvan North of the Warmaster's Shack grace for the Volcano Manor quest line. We both invaded Istvan's world and were fighting as usual. My friend died (which gave me a furlcalling finger remedy and a rune arc) while I continued to fight. After winning the fight before my friend returned, I was given a rune arc and a furlcalling finger remedy and booted back to my own world, without my friend, only I was a red phantom. I can not fight my own enemies and I can't use any multiplayer items, modded or otherwise. Dying (by jumping off a cliff) does not make me drop my runes and I always spawn at the invasion sign for Istvan. Quitting can only be done by pressing alt+f4 and re-loading the character does not return the character normal. The character appears to be truly broken since I can't even play through my own world. 

I will provide a copy of my save file in the following link, in case that is helpful. The character is level 89 Jetka. 
[https://drive.google.com/file/d/1nrZhHH3HSNHsuZYxjJmSMi6Ofr8RyHff/view?usp=sharing](url)

### Steps to recreate the bug

1. Join a host using the Effigy of Malenia.
2. Invade Istvan together. 
3. Let host die.
4. Defeat Istvan before the host returns.

If this does not reproduce the bug, try the following more detailed series of steps.

1. Join a host using the Effigy of Malenia.
2. Invade Istvan together.
3. Let host die.
4. Let the host be invaded by Recusant Henricus (near the arena looking building).
5. Defeat Istvan before the host returns or defeats Henricus.
6. Attempt to invade Istvan again immediately. 
This should put the player in an invasion with a non-responsive Henricus instead of Istvan and prevent any sort of return to the normal world, forcing an alt+f4 to reload the game as quitting normally will be locked and multiplayer items will all be impossible to use.

### Version

1.2.5 (Latest)

**Comment by dsxy** [comment]
My friend had the same issue, he killed himself a few times and on the last one, by the grand lift of dectus, he was kicked back to main menu and could log back in again and resume as normal.  good luck
