### ISSUE TITLE
[Bug]: Fallingstar crater and Radahn grace not appearing

### ISSUE THREAD

**Issue by Sarincrow** [LukeYui/EldenRingSeamlessCoopRelease#309]
### Discord Username

Mozu The Boneless#1438

### Describe the issue in detail

During the Radahn bossfight, the host was killed and I was left alone with the boss. I defeated him and was awarded runes (but no remembrance) while the host was awarded the Great Rune and the remembrance, but no runes.
After that happened no cinematic with the falling stars played. This may be because in my own world I already beat Radahn.
The grace did not appear in the boss room after defeating Radahn, and we had to go back there and fight the Misbegotten + Cruicble Knight.
Once we were back into the arena, Blaidd and Alexander were there, but no cinematic played. The sky was still raining blood, no grace was unlocked.
We later went over to the crater and it was absent in the host's world. It is still present in mine.

I will try, as a temporary fix, to host a game as a character who has NOT beaten Radahn, invite the host and beat him together. Hopefully the cinematic and crater shall carry over to his world. I will comment here if the fix works as soon as I can replicate it, so that other people with the same issue may know if it works or not.

### Steps to recreate the bug

-Have a host who has no beat Radahn coop with a summon who has already done so
-Have the host die in the second phase of the bossfight, let the summon kill Radahn
-Check if the grace after the bossfight or the fallingstar crater are present in the host's world; they shouldn't be.

### Version

1.2.5 (Latest)

**Comment by theunholy** [comment]
This happened to me but i was playing solo no summons, the cinematic never played and i was stuck in the arena, had to walk north to reach a dungeon then run back out for my graces to be enabled again, and then i could teleport, but yea the meteor never fell, now i cant complete rannis quest. I was trying to use the elden ring debug program, to see if i can trigger that event but i really dont know were that would be

**Comment by theunholy** [comment]
A fix i found from youtube wrong warp skip works perfectly fine and can continue rannis quest line.


1. unlock The Four Berlfries grace and obtain the key atop of the mountain(be careful its a single use key on the whole run)
2. with the new stone key that you obtained unlock the portal that is right in front of the tower you got your key, you will know you are in the correct one if you read the message on the floor "Night Sky Unseen"
3. Once you unlock the teleport, go to it, now you will be at an alternate hidden path of Nokron City
4. This is the tricky part you have to time it. Next open your map and teleport to Volcano manor , when your loading bar is 3/4 of a way loaded, alt f4 the game.
5.Now reload your game and you should be right in front of the mimic fight arena and now you are able to finish rannys quest.

**Comment by aNewbieProgrammer** [comment]
> This happened to me but i was playing solo no summons, the cinematic never played after i killed radah and i was stuck in the arena, had to walk north to reach a dungeon then run back out for my graces to be enabled again, and then i could teleport, but yea the meteor never fell, now i cant complete rannis quest. I was trying to use the elden ring debug program, to see if i can trigger that event but i really dont know were that would be

I'm in the exact same situation. I've defeat radahn, but the cutscene never load, and the grace never appear. I have to kill myself and respawn in order to play the game, but then my ranni's questline was completely stuck, and I can't get back to the arena anymore.
