### ISSUE TITLE
[Bug]: Can't Reconnect

### ISSUE THREAD

**Issue by jhyeazy** [LukeYui/EldenRingSeamlessCoopRelease#312]
### Discord Username

Jhyeazy

### Describe the issue in detail

When I disconnect as a wanderer from my friend's world, I can not rejoin them unless I first close application. This remains true when he dis/reactivates the jar host item and when I use the item to search for their world.

### Steps to recreate the bug

Described in previous section

### Version

1.2.5 (Latest)

**Comment by intheclouds11** [comment]
My workaround is having everyone use the Seperation Mist. Seems to fix it when we can't reconnect. But still, not having connection issues would be ideal.
