### ISSUE TITLE
[Bug]: game crash phase 3 fire giant  in  Mountaintops of the Giants. 

### ISSUE THREAD

**Issue by AymsJack** [LukeYui/EldenRingSeamlessCoopRelease#316]
### Discord Username

Aymsjack#9495

### Describe the issue in detail

My game crash 5 times in a row just before the phase 3 of the fire giant, just before the cutscene start

### Steps to recreate the bug

Fight giant fire in Mountaintops of the Giants and reach the phase 3

### Version

1.2.5 (Latest)

**Comment by LukeYui** [comment]
Have you tried verifying your game files with Steam?

**Comment by AymsJack** [comment]
I tried and it works now. ty :)
