### ISSUE TITLE
[Bug]: cant lock on

### ISSUE THREAD

**Issue by jjburke-code** [LukeYui/EldenRingSeamlessCoopRelease#318]
### Discord Username

Yoesph

### Describe the issue in detail

Sometimes in boss fights host cant lock on

### Steps to recreate the bug

above 

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment]
Duplicate of #21

**Comment by Mrqozy** [comment]
> Duplicate of #21

Useless reply as always.
