### ISSUE TITLE
[Bug]: RYKARD BOSS FIGHT IS BUGGED

### ISSUE THREAD

**Issue by Fnetra** [LukeYui/EldenRingSeamlessCoopRelease#319]
### Describe the issue in detail

When the boss fight goes to the second phase my teammates immediately get kicked off. 

### Steps to recreate the bug

just get to second phase of rykard with friends

### Version

1.2.5 (Latest)

**Comment by CuriousCorndog** [comment]
Dead or alive, the boss fight bugs and kicks the joining players out during the cutscene. If they rejoin afterwards they get put into a boss arena with a dead Phase one God-Devouring Serpent and cannot assist.
