### ISSUE TITLE
[Bug]: can't summon spirit ashes 

### ISSUE THREAD

**Issue by SkeletonwithEyes** [LukeYui/EldenRingSeamlessCoopRelease#323]
### Discord Username

Skele mellon#8991

### Describe the issue in detail

can't summon any spirit ashes to help on a fight, not even the one you get from ranni at the start of the game

### Steps to recreate the bug

no steps to recreate since it happened ever since I got the first spirit ash it doesn't work

### Version

1.2.5 (Latest)

**Comment by pkajan** [comment]
Its not a bug, "summons" are disabled [hard to balance?].
Imagine party of 3 and everyone summon something (5demis for example = 15summons total....)

**Comment by LukeYui** [comment]
You can't use spirit ashes in multiplayer at the moment
