### ISSUE TITLE
[Bug]: Loading Screen stuck

### ISSUE THREAD

**Issue by Lexcellent** [LukeYui/EldenRingSeamlessCoopRelease#327]
### Discord Username

Lexcellent#3842

### Describe the issue in detail

When I join a session with my friend.This happens a lot.Versions after 1.2.3 are very common.We tried firewalls and virtual lans.But it happens occasionally

### Steps to recreate the bug

I've noticed that there are a lot of network related bugs that you can't replicate.Maybe it has something to do with the Internet environment in different countries?

### Version

1.2.5 (Latest)

### Relevant Crash log

```shell
错误应用程序名称: eldenring.exe，版本: 1.5.0.0，时间戳: 0x6295c83c
错误模块名称: unknown，版本: 0.0.0.0，时间戳: 0x00000000
异常代码: 0xc0000005
错误偏移量: 0x00000136a6ac17e0
错误进程 ID: 0x69cc
错误应用程序启动时间: 0x01d887e0f0111aeb
错误应用程序路径: e:\steam\steamapps\common\ELDEN RING\Game\eldenring.exe
错误模块路径: unknown
报告 ID: 75420f22-90b7-4508-b250-7c7ba2280a19
错误程序包全名: 
错误程序包相对应用程序 ID:
```

**Comment by Lexcellent** [comment]
Maybe this log is not for this bug.I'm not sure.

**Comment by Fenlig** [comment]
I've found that sometimes when a player dies, the host does not recognize it and goes out of sync, so they player cannot rejoin until the host kicks everyone out of their game.

**Comment by Lexcellent** [comment]
> 



> I've found that sometimes when a player dies, the host does not recognize it and goes out of sync, so they player cannot rejoin until the host kicks everyone out of their game.

Or the host open world again
