### ISSUE TITLE
[Bug]: mod item no response after use

### ISSUE THREAD

**Issue by Lexcellent** [LukeYui/EldenRingSeamlessCoopRelease#329]
### Discord Username

Lexcellent#3842

### Describe the issue in detail

I can reuse mod item and get no response.This has happened in previous versions as well.But in version 1.2.5 this is the first time.The same goes for restarting the game.Later, it was solved by virtual LAN.

### Steps to recreate the bug

Because it only happened once.I don't know how to trigger it

### Version

1.2.5 (Latest)

**Comment by LukeYui** [comment]
Sorry I don't understand the report. Which item did you use and what happened when you used it?

**Comment by Lexcellent** [comment]
> Sorry I don't understand the report. Which item did you use and what happened when you used it?

"Effigy of Malenia" and "Tiny Great Pot",nothing happened when I used it.Maybe it's because of my Internet?

**Comment by Aylaria** [comment]
This seems to happen to me, where I will be playing with my friend and disconnect (usually for npc quest related things), then I can't reconnect until they open the world again. It doesn't give me the usual "no sessions found" message, it just times out and doesn't appear to do anything (until their world is closed and reopened, in which case it joins me to them as normal)
