### ISSUE TITLE
Windows Defender flags mod zip with Trojan:Script/Oneeva.A!ml

### ISSUE THREAD

**Issue by mtgibbs** [LukeYui/EldenRingSeamlessCoopRelease#33]
Version: `BETA 1.1.0`

Windows Defender flags the mod as `Trojan:Script/Oneeva.A!ml`.

Alert level: Severe
Status: Active
Date: 6/4/2022 1:01 PM
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Affected items:

   file: `~\Downloads\betareleaseercoop1.F0fb7_16.1.0.zip.part`

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aScript%2fOneeva.A!ml&threatid=2147729349

Some research into this shows a few other games having this issue, but since there isn't any source available to review (#32) we need to know if there's an issue.

**Comment by LukeYui** [comment]
It's the mod launcher that has been flagged. I've submitted it to them as a false positive and it should be resolved within the next few days I'd expect
