### ISSUE TITLE
[Bug]: Texture bug?

### ISSUE THREAD

**Issue by cartenchansl1** [LukeYui/EldenRingSeamlessCoopRelease#333]
### Discord Username

_CooCooLong#7288_

### Describe the issue in detail

[https://youtu.be/XdMzxYkCQkM](url)

I played with my friend, then we encountered this bug.
He wants to restart the game and try it again, but he cannot go into the game again when he chooses that character.

### Steps to recreate the bug

I don't know the english name of the area, but you can see the map in the video.
The same bug in Single or  Multiple player.

![image](https://user-images.githubusercontent.com/108167991/175759615-ec8c2ad4-eb8a-4408-9331-a082e225955f.png)

### Version

1.2.5 (Latest)

### Relevant Crash log

```shell
失敗的應用程式名稱: eldenring.exe，版本: 1.5.0.0，時間戳記: 0x6295c83c
失敗的模組名稱: unknown，版本: 0.0.0.0，時間戳記: 0x00000000
例外狀況代碼: 0xc0000005
錯誤位移: 0x0000018362d917e0
失敗的處理程序識別碼: 0x46c0
失敗的應用程式開始時間: 0x01d8884dedd7255d
失敗的應用程式路徑: E:\SteamGAMES\steamapps\common\ELDEN RING\Game\eldenring.exe
失敗的模組路徑: unknown
報告識別碼: 2bd94f81-abff-459a-8939-633465666b84
失敗的套件完整名稱: 
失敗的套件相關應用程式識別碼:
```

**Comment by LukeYui** [comment]
Try verifying your game files with Steam, it looks like the 1.05 game update corrupted your files
