### ISSUE TITLE
[Bug]: Sacred tear flask reset to 1

### ISSUE THREAD

**Issue by madmaxx11** [LukeYui/EldenRingSeamlessCoopRelease#334]
### Describe the issue in detail

Sacred tear flask reset after i upgraded was at +6 then reset to 1

### Steps to recreate the bug

just upgraded my flask like normal and it reset it was +6

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment]
Duplicate of #134

**Comment by GeneralZain** [comment]
this also happened to me! after I got to just before the fire giant, with a +11 flask I picked up the upgrade mat at the church, upgraded from 11 to 1 no idea how to fix...im so late in the game and idk if there's any more places I get get flask charges...
