### ISSUE TITLE
[Bug]: great runes disapear when joined

### ISSUE THREAD

**Issue by Erebos2000** [LukeYui/EldenRingSeamlessCoopRelease#337]
### Discord Username

Erebos#0518

### Describe the issue in detail

I wanted to go acivate a Godricks great rune but when i got to the tower i did not have the great rune but my friend did. My friend and i did not know why so we continued playing and killed Rennala and we both got the rune for that and it stayed that way for some time. But after we killed Radahn we both got the rune. Before i did the Cealinian Tower i looked for it and it had disapeared as well. So we tried me joining my friend. Thats when his runes from godrick and radahn suddenly disapeared from his inventory. So we think the rune of the host disapear when the other joins. We think only the great rune that have not been activated disapear.

### Steps to recreate the bug

Kill Godrick and the demigods together then leave and rejoin. We did it with just two of us. disapearence might have happened when joining someone who is on the roundtable hold. 

### Version

1.2.5 (Latest)

**Comment by Shinjoku** [comment]
It happened to my party too, it can happen for every rune in the game.

### Version
1.0.1
