### ISSUE TITLE
Random items granted sometimes

### ISSUE THREAD

**Issue by antisandwichman** [LukeYui/EldenRingSeamlessCoopRelease#34]
Usually happens when I join my buddy or he joins me. The frequency that this happens seems to have decreased the longer we've played together. The first time, though, that one of us tried joining the other, the one who joined probably was granted 15+ weapons/items.

**Comment by justn1** [comment]
Yep, happened to me. Also sometimes when joining the host the player sees that the enemy fell and receives runes (sometimes this happens multiple times and you receive a lot of runes)

**Comment by Arclesis420** [comment]
Same here. Though for me it happens when we disconnect after we voted on warping somewhere. I have around 5 of each talisman right now and every time we get extra swords and even remembrances.

**Comment by Cameron-Gressett** [comment]
weird thing happened to me, friend gave me a roar medallion to give to his other character he swaps characters to one that hasn't even touched it, I join his game and get a copy of it.
