### ISSUE TITLE
[Bug]: Round Table Hold NPC keep randomly reset

### ISSUE THREAD

**Issue by NelFromHell** [LukeYui/EldenRingSeamlessCoopRelease#341]
### Describe the issue in detail

Each time we come back to the Round Table Hold, some NPC are reset, either for the host or the invited player (but it is worst for the invited player).
For exemple, Corhyn has forget the book and the quest advancement so it is not possible to buy some incantation. The same with D, Rogier, etc.
Roderika and Hewg arre not in the same room anymore for the Host, so it is not possible to lvl up the ashes.
Fia don't give the benediction when the host hug her.

However, quitting the multiplayer seams to solve the progression of the quests and give back the books and incatations to the NPCs inventory:
After quitting the multiplayer, the host had Roderika and Hewg came back at the normal states, Fia gave the benediction propertly.

For the invited player, D, Rogier, Corhyn and all other NPC came back to the normal states has well. Corhyn had even back the incatations.

But once we play back together, the NPC forget everything again. It seams like there is a state of the game different from our respective solo games (solo using the SeamlessCoop.exe of course).

### Steps to recreate the bug

recreating the bug is quite complicated since it does not forget the same things for each players.

maybe a sync problem between host and other players ?

### Version

1.2.5 (Latest)

**Comment by Sythys** [comment]
I experienced this bug in 1.4.5
