### ISSUE TITLE
[Bug]: bosses freeze when one player dies

### ISSUE THREAD

**Issue by elderhaz** [LukeYui/EldenRingSeamlessCoopRelease#343]
### Describe the issue in detail

If either players die, host or joined player, during a boss fight in any boss room; such as Malenia, Godfrey or literally any other boss room boss, the boss will bug out and freeze for the other player, whilst the dead player spectates. 100% consistently happens. The boss will occasionally give off an attack here or there if triggered by running in to them a lot or by starting their second phase, but will stay not moving or giving aggression. 

### Steps to recreate the bug

Go to Godfrey or Malenia, at any point have one (of two people), die during the boss fight, the boss will then instantly bug and barely move and only very occasionally attack for the rest of the fight.

### Version

1.2.5 (Latest)

**Comment by AkuseruGH** [comment]
exactly the same thing happens to me with godrick and margit
