### ISSUE TITLE
[Bug]: Calid divine tower cooperator randomly gets runes as if demigod is killed

### ISSUE THREAD

**Issue by jjburke-code** [LukeYui/EldenRingSeamlessCoopRelease#345]
### Describe the issue in detail

In divine tower coop player (not host) gets message demi god killed and gets runes. Happened three times while fighting godskin. 

### Steps to recreate the bug

random

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment]
Duplicate of #56
