### ISSUE TITLE
[Bug]: Giant doesn't land on me 

### ISSUE THREAD

**Issue by unifermon** [LukeYui/EldenRingSeamlessCoopRelease#348]
### Discord Username

uni#3372

### Describe the issue in detail

https://user-images.githubusercontent.com/108242788/175837325-23da3986-d4eb-4ea1-90d3-1f668ba9229c.mp4

### Steps to recreate the bug

Enter the gate after the soldiers village (start of the game) 

### Version

1.2.5 (Latest)

**Comment by ErisyaleLancaster** [comment]
This is actually just Elden Ring itself being weird.

This happened to me and a Friend on our first day playing together in the normal Game through normal Co-Op, my Giant would jump down, having us engage in battle against him while getting invaded.
Hers didn't jump down.

So yeah, not a bug with the Mod, just Elden Ring itself.
