### ISSUE TITLE
Activating great rune in multiplayer only grants it to the person who touched it

### ISSUE THREAD

**Issue by antisandwichman** [LukeYui/EldenRingSeamlessCoopRelease#35]
Title. Was playing with my buddy and went to activate Morgott's great rune. I touched the rune on the holy tower to activate it, and was able to select it at a site of grace to equip it. However, my buddy doesn't have the ability to equip it and it isn't showing up for him to touch either.

**Comment by Arclesis420** [comment]
Can confirm this has happened to me but with Godrick's great rune. We were in their world and I didn't get the rune.
