### ISSUE TITLE
[Bug]: Getting on Torrent causes 1 player to become invisible while their model rides in place

### ISSUE THREAD

**Issue by LogicalChocolate** [LukeYui/EldenRingSeamlessCoopRelease#354]
### Discord Username

LogicalChocolate#3006

### Describe the issue in detail

Friend and I started playing, torrent worked for both of us until we rested at a grace - after that any time he got on Torrent his character model would run in place and I wouldn't be able to see him move. He would be moving fine on his end and could interact with and attack enemies. Enemy AI seemed to respond to his client-side position, not where I could see him running in place. If he got off Torrent his character would teleport to his actual location and I could see him move again.

We tried changing hosts and only he was affected still - he could always see me move on torrent and I could never see him move - regardless of host

### Steps to recreate the bug

Run straight to grace where you get Torrent and then teleport to Elleh, seemed to happen immediately after that. Can't get it back to how it was

### Version

1.2.5 (Latest)

**Comment by Fnetra** [comment]
it happens to me and my friends sometimes too. Closing and opening the session again doesn't change anything. You always have to close the "game" to get rid of the bug.

**Comment by LukeYui** [comment]
Will be fixed in 1.3.0

**Comment by 66Fkn** [comment]
Hi there! First of all, really great mod. Second, I'm still having this issue, did 1.3.0 fix this?

**Comment by Chris-Peterson444** [comment]
+1 to this issue on 1.3.0. 

In my case, there are 3 players, and only one player is bugged while the other is fine. The other two players strangely don't have this issue though. 

Appears to be consistent regardless of host and join order.

**Comment by deroguerre** [comment]
+1 same issue on 1.3.0.
