### ISSUE TITLE
[Bug]: After a boss fight the guest gets more rune than the host. 

### ISSUE THREAD

**Issue by Joqtomi** [LukeYui/EldenRingSeamlessCoopRelease#358]
### Describe the issue in detail

We killed several bosses today, and some of them granted the same amount of runes to both players, and some didn't. The guest was always the one receiving around 25 % more.

### Steps to recreate the bug

Fight different bosses and compare runes gained between players.

### Version

1.2.5 (Latest)

**Comment by ErisyaleLancaster** [comment]
Can confirm this, not sure if one of the players being dead is a trigger as me and a friend aren't far into the game yet.
But we noticed this with Margit the Fell and Godrick the Grafted.

My friend was Host for Margit and i died during the Fight with her killing him, she got less Runes than me.
Then, yesterday, we went against Godrick with me as host, i died again (greedy) and she got more runes than me.

So we concluded that at best it had something to do with one of us being dead when the Boss dies, but surely not the effect of the Rot that reduces Rune-Gain.
