### ISSUE TITLE
[Bug]: golems at the dectus lift will agro even if you used the medallion

### ISSUE THREAD

**Issue by LEEJER** [LukeYui/EldenRingSeamlessCoopRelease#363]
### Describe the issue in detail

My friends and I used the dectus medallion to go through the dectus lift. Normally, the golems at the top do not agro if you use the medallion. But no matter what we did, the golems would agro anyways. 

I expected for the golems to remain passive if we took the lift. 

### Steps to recreate the bug

Grab both halves of the dectus medallion. 
Join multiplayer, and take the dectus lift. 

### Version

1.2.5 (Latest)

**Comment by Ginnel** [comment]
They always aggro maybe you weren't near enough to aggro the first time
