### ISSUE TITLE
[Bug]: Players can respawn during boss fights if they get the “Defeat” message. 

### ISSUE THREAD

**Issue by LEEJER** [LukeYui/EldenRingSeamlessCoopRelease#364]
### Describe the issue in detail

Friends and I were fighting the nights Calvary in Altus plateau on the highway outside of the dectus lift. I got one shot and died. 

I expected to go into spectator mode where I would have to wait for the fight to end in order to respawn. 

Instead, I got the “Defeat” death message (instead of “you died”), the screen faded to black and I respawned after a few seconds. 

### Steps to recreate the bug

I do not know how to cause the bug, but (as far as I remember), every time I saw the “defeat” banner, I would respawn as normal. 

### Version

1.2.5 (Latest)

**Comment by cabiste69** [comment]
this is a common bug and happens only for the host

**Comment by LEEJER** [comment]
> this is a common bug and happens only for the host

It happened to everyone on the world a few times. Not just the host.
