### ISSUE TITLE
[Bug]: Enemy Felled, crash, repeat

### ISSUE THREAD

**Issue by manner1275** [LukeYui/EldenRingSeamlessCoopRelease#365]
### Discord Username

FlyGod#3173

### Describe the issue in detail

Ok, this bug is not happening to me in particular but my friend. I have already defeated Rennala, and summoned my friend into my world at the Schoolhouse Classroom SoG, while in my game, he received items I happened to pick ip around the open world despite him never visiting places like Altus and specific dungeons, and then he crashed. When he attempted to boot up again and start the game on the same character he crashed to desktop again. Rinse and Repeat.

### Steps to recreate the bug

I have no clue how the bug was created but I'm guessing you can try having a lower leveled, further behind player, join another player that's higher level and further ahead in the game. (EX: {level 30, has only defeated Godrick}, joins a {level 68,defeated 2 of the 10 main bosses} in Schoolhouse Classroom Site of Grace. 

### Version

1.2.5 (Latest)

### Relevant Crash log

```shell
Log Name:      Application
Source:        Application Error
Date:          6/27/2022 1:44:47 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-Q733N25
Description:
Faulting application name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Faulting module name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Exception code: 0xc0000005
Fault offset: 0x0000000000234619
Faulting process id: 0x3ab8
Faulting application start time: 0x01d88a0207bf9979
Faulting application path: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Report Id: 1b730f84-df31-4a4e-bd0d-ad8737267357
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event%22%3E
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-06-27T08:44:47.2967112Z" />
    <EventRecordID>180168</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-Q733N25</Computer>
    <Security />
  </System>
  <EventData>
    <Data>eldenring.exe</Data>
    <Data>1.5.0.0</Data>
    <Data>6295c83c</Data>
    <Data>eldenring.exe</Data>
    <Data>1.5.0.0</Data>
    <Data>6295c83c</Data>
    <Data>c0000005</Data>
    <Data>0000000000234619</Data>
    <Data>3ab8</Data>
    <Data>01d88a0207bf9979</Data>
    <Data>D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe</Data>
    <Data>D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe</Data>
    <Data>1b730f84-df31-4a4e-bd0d-ad8737267357</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by cabiste69** [comment]
i sort of experienced the same bug but without the crashing part, basically sometimes when i or my friends join a session we will get the drops of bosses that the host killed even if we never fought those bosses and another bug is that we'll keep getting "enemy felled" or a message like that and keep getting the amount of runes that's given by the last boss the host has killed (just yesterday my friend had this bug and got about 1 million runes)

**Comment by loki2236** [comment]
Raya Lucaria has been buggy since 1.05 update came out because of the update process, most of the users verified their game files on steam and it has solved it for them, have you tried that?

Getting the items that the host has received is normal, but the crash could be related to the raya lucaria corruption on the 1.05 patch.
