### ISSUE TITLE
Repeatedly recieving 3200 souls.

### ISSUE THREAD

**Issue by Nuddlr** [LukeYui/EldenRingSeamlessCoopRelease#38]
Only happens to me when joining my friends session

**Comment by GuiCoppini** [comment]
Had it happen to me as well, everytime I die, I lose the runes I was carrying but spawn with a fixed number of runes.

**Comment by Madjai** [comment]
Same here. Everytime I join I get 5,000 runes and a message that says something like "A new draconic power is available..." so I think it's a boss that's constantly dying.
