### ISSUE TITLE
[Bug]: Rya's teleport to Volcano Manor starts an infinite loading screen

### ISSUE THREAD

**Issue by JoaoRicardo70** [LukeYui/EldenRingSeamlessCoopRelease#385]
### Discord Username

J.R.#4506

### Describe the issue in detail

I was playing with a friend normally, we had started to explore the Plato and found Rya (we gave her pendant back in Liurnia) so we were going to teleport to the Manor. Firstly, me (the host) couldn't speak to her but my friend yes, however, the teleport failed. After that we tried to do it in our separate worlds, since I was the host, it was easier for me to talk to her (Rya) before my friend loaded his world. When I spoke to her the teleport initiated a loading screen, BUT this loading is ETERNAL and I can't load my character anymore (50 HOURS CHARACTER), I just got an infinite loading screen.

PLEASE HELP!!!!

### Steps to recreate the bug

1. The guest tries to teleport to the Manor (*Fails*)
2. The host can't talk to Rya until the guest leaves
3. When the guest goes out, the host talks to Rya (I needed to restart the game)
4. The host accepts her offering to go to the Manor
5. Infinite Loading Screen
6.  Pain and Suffering

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment]
First: Verify your game files through steam.
Second:

1) Dowload Elden Ring Debug Tool by Nordgaren (should be here on github)
2) Run the debug tool from anywhere while having the game open.
3) While loading the character that is  'stuck' go to the misc tab on the debug tool and set Flag 105 (Disabled or Enabled I can't remember)
4) That should solve the infinite loading screen
