### ISSUE TITLE
[Bug]: can't summon spirit  

### ISSUE THREAD

**Issue by DragonFireWestMSG** [LukeYui/EldenRingSeamlessCoopRelease#387]
### Discord Username

DragonFire

### Describe the issue in detail

when in boss fight i cant summon spirit like mimic and the others

### Steps to recreate the bug

.........

### Version

1.2.5 (Latest)

**Comment by Yoni0040** [comment]
You can't summon spirits in co-op in general. So, the mod owner hasn't implemented this yet.

**Comment by Myheartdies** [comment]
It's not a bug, spirit summon is disabled

**Comment by LukeYui** [comment]
As above
