### ISSUE TITLE
Hardstuck in Ranni's Rise

### ISSUE THREAD

**Issue by PurpleGentleman** [LukeYui/EldenRingSeamlessCoopRelease#39]
After reaching Ranni's tower for the first time, my friend and I both accepted her questline. However my friend jumped off her tower and died and would not respawn until after a reset, and I spoke to the ghost's in the tower and then to Ranni to proceed. When he came back he did the same, and we were able to leave the tower normally. After going to the mage dude he noticed he could not teleport, so we went back to the tower to touch the grace and see if it would fix itself but now I can't teleport either, and we can't leave the tower area as if we hadn't spoken to the ghosts but they aren't there anymore and Ranni only says "...". Reseting game, speaking to Ranni, teleporting, nothing helps and we can't leave the tower. Would really like not having to start a new game since we already invested 30+ hours into this playthrough, so any help would be welcomed.

**Comment by 9Ennea** [comment]
Exactly the same

**Comment by PurpleGentleman** [comment]
Issue has not been solved, why was this closed?

**Comment by OhLazarus** [comment]
My friend is also softlocked by this and can't teleport. Really demoralizing to our playthrough.
