### ISSUE TITLE
[Bug]: Crash to desktop in Limgrave Misty Forest area

### ISSUE THREAD

**Issue by hypertexthero** [LukeYui/EldenRingSeamlessCoopRelease#391]
### Discord Username

HyperTextHero#9319

### Describe the issue in detail

I was playing alone using the Seamless Coop Mod version 1.2.5 and the game crashed continuously whenever I walked further into the Misty Forest in Limgrave.

Video of the crash: <https://www.twitch.tv/videos/1521552206>

Thank you!

### Steps to recreate the bug

1. Load game
2. Walk to Misty Forest and head south.

### Version

1.2.5 (Latest)

### Relevant Crash log

```shell
Level	Date and Time	Source	Event ID	Task Category
Error	2022-07-03 03:46:25 PM	Application Error	1000	(100)	"Faulting application name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Faulting module name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Exception code: 0xc0000005
Fault offset: 0x0000000000234619
Faulting process id: 0x3b88
Faulting application start time: 0x01d88f1196b45b47
Faulting application path: F:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: F:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Report Id: 79dbfa75-d0c2-4b45-8c43-82fad6ecdfd2
Faulting package full name: 
Faulting package-relative application ID: "
```

**Comment by Valvega1984** [comment]
I'm having this same issue, but even further centralized to the Minor Erdtree in the area (either that, or the Minor Erdtree seems to be a cutoff point for the CTD issue). This makes it night impossible to access the goodies at the base of the tree.

**Comment by loki2236** [comment]
Sounds like corrupted game files, did you try to verify your files through Steam?

**Comment by Valvega1984** [comment]
This worked for me as well.
