### ISSUE TITLE
[Bug]: Academy of Raya Lucaria Game Crash

### ISSUE THREAD

**Issue by xSeaLily** [LukeYui/EldenRingSeamlessCoopRelease#392]
### Discord Username

DeadlyIndicaa#0128

### Describe the issue in detail

My character is located at the Academy of Raya Lucaria, that is where i left off at. I recently I tried continuing and every time it kicks me off the game. My mouse cursor also is flickering. I have already tried redownloading the launcher and redownloading the dll file. 

### Steps to recreate the bug

Go to Academy Raya Lucaria and then log off and try logging in. By the first dungeon area. 

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment]
Verify your game files through steam, It's been known to happen because file curruption during the update on the 1.05 patch
