### ISSUE TITLE
[Bug]: Unable to join host and the host is also not able to exit the game without using alt-f4

### ISSUE THREAD

**Issue by Max-Carnevale** [LukeYui/EldenRingSeamlessCoopRelease#394]
### Discord Username

TheCarrot#2193

### Describe the issue in detail

At seemingly random times whenever I try to disconnect and reconnect to my friend it will say "you are joining another player" twice and then not say "joining another player as a wanderer". It might be important to note that most of the time when I disconnect and reconnect to him this happens before and after we fight a boss as we like to fight it separately. The bug only happens when the host is unable to exit the game as shown in the screenshot.
![image](https://user-images.githubusercontent.com/49702635/177222124-d5426cb0-9727-4faa-ad50-2089c8bf3582.png)

### Steps to recreate the bug

disconnect from host using separation mist
if host is unable to quit game normally then when using the effigy of malenia to reconnect it will not work

### Version

1.2.5 (Latest)

**Comment by Max-Carnevale** [comment]
Just figured out how to fix it, if the host uses the separation mist himself then he is able to exit the game. Unsure if this is meant to be how this works but it was not very intuitive if so.

**Comment by LukeYui** [comment]
Yeah this is how it's meant to be. As soon as you use the tiny great pot you are hosting a party so cannot quit the game.
