### ISSUE TITLE
[Bug]: Game breaking loading screen loop + 4 minor glitches

### ISSUE THREAD

**Issue by gnieBehT** [LukeYui/EldenRingSeamlessCoopRelease#396]
### Discord Username

dioV ehT#0803

### Describe the issue in detail

1 - I tried loading my character. I won't even be able to spawn in. Every time it finishes loading the obscured screen lights a little for a few frames, then gets back to black screen. afterwards the clock that appears when you change the time of the day also appears for few frames, last but not least a new loading screen appears and the whole thing repeats.
2 - While in my friend's world we explored a tomb and the chariots are messed up, following almost randomic movements that sometimes make them clip through walls or disappear entirely from the area until reloaded
3 - Sometimes when getting on your horse the other players won't be able to see its model
4 - Rarely when a player gets an item in their host's world the host won't be able to see that item anymore (not sure if it can happen when roles are inverted)
5 - When you summon somone against the grafted scion's first encounter the summoned player will be invincible, staying at 1 hp until he dies by falling off the map

### Steps to recreate the bug

1 - I opened a trap chest in the host's world. I got teleported, he didn't. we turned off our games.
5 - Summon, die (probably only works as a host). The shion is supposed to make the cutscene start once you reach 1 hp, so the remaining player will never die from the scion's attacks and the cutscene will never start.

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment]
Fix for number 1:
1) Dowload Elden Ring Debug Tool by Nordgaren
2) Run the debug tool from anywhere while having the game open.
3) While loading the character that is  'stuck' go to the misc tab on the debug tool and set Flag 105 (Disabled or Enabled I can't remember)
4) That should do it.

Number 2, 3 & 4 are duplicates of other issues, try making only one report per bug next time. But they have been adressed already. Will be fixed.

5) Thanks for the report.

**Comment by gnieBehT** [comment]
It worked, Thanks for your support

Il ven 8 lug 2022, 16:09 Loki ***@***.***> ha scritto:
