### ISSUE TITLE
Password Length

### ISSUE THREAD

**Issue by ObscuraInc** [LukeYui/EldenRingSeamlessCoopRelease#4]
Mod fails to read password when set to 1024 characters then crashes

Edit: This is the password causing issues

```V3YnYt4^_H9YG25H7fPC?#ax&wd7BM5NNZheCS9KS^Nj?k^e6sQBQjeA4PZt3H%q?m^&FSJx^Ap?xjb=2CMRNs2dbn8u9wpX5F!GLBaNgbK397ERDw&V+__Y7&VHk!@EGm2GasMH8?w6Z#bXLFACDEq@J#ZH4E9Euh!etBh833D5njx6m9KqKYhjFRwm5P_xA89m%PvsqmVuE53?p9Us8wXx6BujYNe3T!24EHz+rJZBP5v5hbw3WDB5W5^79qt#xDUh@cK%VG4w^Kmru9Q!KW#smCjE22AqgR?e2TbZzUCrWUv5pbKzbjSD?rP2+h2SdQ$mKkNWWFzSYfNw!Y^UFjvKHw+?9q^RZCNvRxXtkhQw$bP9Nz^7k43cuypYmeN$xL=9#485Z?ZHt+@v5#%BP2&GbC$r-bmBKZUL?P5ZurM_CN#a%wYP3a?Ye4vnM6vXn3tNuXcUSYxajf?tB$6uk2f$HsRkS!AUZ9wpX=?4-8q#+YHhEnNLsSrp#dDJAzRdNnsmcKR&dvqa_qqeW5rz9S^waYRAeMRQT+BPm4F@55ar4&n-TT@_L%QbSf^8Pb#dW&_gHamxP2Um27F$+d%^bv*HGtt^D+8@+up?sjRHBx$?37u^2LURA8MHRyqrhp%qQyU%6m??EYHd%jZSrXwf2$HV7!te9c2+&bnp&BxEDD%AY=nFrGkADQct%2SX#3naeBB8my7V#%Lw@Z?3K&CK!%g!Tv%5^x-NdnsJc$CetYJUTD!htML8e#T+V!g?fZxFXbrwPdk?ULk&dzK#mkUY#RCcPu%_TmJ8Yr9SFy6E5$kP$!exQ?sBLV9+YBTm#4J4m+zu^!X+tLQ9Jas@L?gFABPKvzq-nwvnCL+5#-avN!pJcr9&E%@YC%JL6whH336CD-WAg8PHgqZxx_pzXqCB-WVGL@Fgbf2CGY5AW9ZXz+#eU6HzDf6EyhcMbtVrA8AU2M#mtN_EqXKBgLe!U3&J%u5Q55pT&u&Naq5?Tzv?zHm3q?R+V2Mt```

**Comment by Alphaz0r** [comment]
This is a very long password sir
