### ISSUE TITLE
[Bug]: Softlock in Ranni's rise after host died.

### ISSUE THREAD

**Issue by LEEJER** [LukeYui/EldenRingSeamlessCoopRelease#401]
### Describe the issue in detail

During Ranni's questline where you are unable to leave the rise, the host of jumped off the cliff and died. He was unable to respawn (or open the menu), and the rest of us were unable to leave or progress the quest.

The host force quit the game, and when the world reopened, Iji, blaidd, and selivus's phantoms were not in the rise. Ranni was unresponsive, and we could not teleport or leave the area. The same happened in our own individual worlds too if we teleported to Ranni's Rise. 

Our characters are completely softlocked.

### Steps to recreate the bug

Events leading up to the softlock:

3 players went up to rannis rise, one player (not host) had completed ranni's entire quest before. 
All 3 of us talked to ranni and offered to enter into her service. Two of us went down below and talked to Iji's and blaidd's phantoms. 
The host jumped off a cliff before talking to any phantoms. The host did not respawn. The host alt-f4'd the game and re-opened the world.
The game softlocked.

### Version

1.2.5 (Latest)

**Comment by Ead0n** [comment]
I found a way to un-softlock the tower.  I ended up having to create a new character, progress to Ranni's Rise, got the phantoms that you need to talk to to spawn, had the buddy that was softlocked join while I spoke to all NPC's and returned to Ranni.  After completing this the tower unlocked for both of us and when he returned to his game he was no longer trapped in the tower.  Took less than an hour.  (Worth it if the characters are important enough or have a large amount of time on them).
