### ISSUE TITLE
[Bug]: Rune dupe

### ISSUE THREAD

**Issue by devindani** [LukeYui/EldenRingSeamlessCoopRelease#406]
### Describe the issue in detail

Sometimes when joining a host I will receive "Great enemy felled" or "Enemy felled" and get in the range of 12-14k runes while he receives none and me the wanderer receives about 25-50% more runes on boss kill.  

### Steps to recreate the bug

not sure how to repeat the gaining runes, but its consistent that i get more runes on boss kill, have wanderer kill boss along with host to see diminishing return for host.

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment]
Duplicate #56
