### ISSUE TITLE
[Bug]: Second player does not receive Torrent summon item. 

### ISSUE THREAD

**Issue by AlbanMarku** [LukeYui/EldenRingSeamlessCoopRelease#408]
### Discord Username

albanshqiptar#3272

### Describe the issue in detail

During the cutscene for Malenia giving the item for Torrent, my partner hit a load screen, disconnected from my session and teleported to the start of the game. Couldn't reconnect until we restarted. The player also was not given the item to use Torrent.

### Steps to recreate the bug

Player one rested at grace and entered cutscene for Malenia.
Player two gets kicked out of session.

### Version

1.2.5 (Latest)

**Comment by loki2236** [comment]
Melina*

The other player should get the item for the horse while playing solo. Does it work?

The 'Couldn't reconnect til we restarted' its normal behaviour, you have to close the session (white mist) and open it again (tiny pot)
