### ISSUE TITLE
[Bug]: Desynch Issues on NPC Questlines and Disconnects; "Enemy Felled" & Runes Rewarded

### ISSUE THREAD

**Issue by McDragz** [LukeYui/EldenRingSeamlessCoopRelease#409]
### Discord Username

McDragz

### Describe the issue in detail

My friend and I are running into massive desynchronization issues when playing together, to the point where we can no longer continue to play and have moved on to other games.

We've played our characters together since inception, and never played them separately, but often times the NPC dialogue each of us receives is vastly different from one another. I will be able to push a quest forward, even as a guest in his game, but the NPC will not allow the same dialogues for him. Some NPCs will appear for me but not for him, and vice versa.

We are disconnected from each other's game pretty frequently, at least once every twenty minutes, and it only happens when we are fast traveling to another grace. It will kick me from his game, and many time we are unable to rejoin each other unless we completely quit out of our games.

There are many times that I can't level at a Site of Grace that we are both resting at as well. I will sit down at the grace, there will be no option to level up, but there will be an option to talk to Melina. I try this option, Melina begins to walk in as if she is entering dialogue, but as soon as the animation finishes she immediately backs up and vanishes, and there is still no option to level.

The latest weird thing to happen is at the Church where the Turtle Pope is (where you can use the Dew to reset NPCs) I randomly get an "Enemy Felled" or "Great Enemy Felled" message as a Wanderer in his game, and am then awarded between 7500 and 10,000 runes.

My friend will also frequently appear invisible, or his horse will be invisible, or both.

### Steps to recreate the bug

As stated above, the issue is overall stability. These bugs happen randomly in any location besides the final glitch I mentioned which always happens at the Church.

### Version

1.2.5

**Comment by McDragz** [comment]
Great Enemy Felled 6 times in a row, and I can't leave the Magma Wyrm Makar boss room. Disconnected three times in ten minutes on top of it. I'm sorry but I've run out of patience, the mod is unplayable for me and our friend group at this time. I'd rather be invaded than run into this deluge of bugs and glitches for one more night, we're just not wasting any more time on this.

**Comment by McDragz** [comment]
After commenting on the Discord, it may be that these issues are due to our connection. Will test this and report back.

**Comment by loki2236** [comment]
Most of this bugs can be avoided if doing NPC quest solo, the flag sync issues are a know thing that's why it's recommended to do NPC quest while playing solo, otherwise flag triggering may have unintended/erroneous effects.

The "no option to level up" sounds like you never went to the RTH with melina, playing solo (that's also recommended to do!). I might be wrong, but I've only see that bug in those cases.

The enemy Felled bug it's a known one and it's been reported already, thank you.

And the disconnections, are weird, sounds like connection issues. You can (both) try to open steam settings -> In-Game -> Steam Networking, and set it to "Always" it usually helps.

**Comment by McDragz** [comment]
Hey Loki,

Thank you for taking the time to respond on this, we really appreciate your insight into this.

That makes sense regarding the npc questlines; we were interested in pursuing multiple endings which is why we were so gung-ho about talking to the npcs, but they seem to get testy when both players are talking to them in the same game. This really came to a head in Volcano Manor specifically, where I (guest) was able to move the assassination quest lines forward by talking to Tanith, but the host would be stuck in the same dialogue with Tanith essentially forever.

You're comment on going to the RTH is accurate, but in a roundabout way. I went to RTH with the host automatically when Melina spoke to them, however I never technically told Melina, on my character, to bring me there. Now that option is gone, but at some sites of grace (seems to be specific to instances like Raya Lucaria, or anywhere a great enemy is), the option to level up is gone, and I can only speak to Melina, where she disappears again after no dialogue. Magma Wyrmm Makarr was the worst by far; green doors never came down, awarded 20k runes with the "Great Enemy Felled" six times in a row, and the grace disappeared from my screen entirely.

I will certainly try what you have suggested and some of the other tips provided in the Discord. Thank you again for your time, I genuinely appreciate the guidance!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
