### ISSUE TITLE
[Bug]: hud don't switch automatically on joystick

### ISSUE THREAD

**Issue by eparisio** [LukeYui/EldenRingSeamlessCoopRelease#410]
### Discord Username

Dekron#1790

### Describe the issue in detail

hi using the joypad don't switch automatically to joystick in hud, i need to set manually in the options

### Steps to recreate the bug

v1.05 er
start the game
use the joystick to navigate and interacts with menu
hud key don't switch to joystick and remains on keyboard inputs

### Version

1.3.0 (Latest)

**Comment by LukeYui** [comment]
Change it in the settings menu
