### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Xenkore** [LukeYui/EldenRingSeamlessCoopRelease#411]
### Discord Username

Xenkore#0045

### Describe the issue in detail

Frenzied Burst and The Flame of Frenzy incantations are not always doing their damage for my friend. He is the guest player. They do still seem to do stagger damage, however.

### Steps to recreate the bug

I am the host, my friend is the only guest player. We were in Volcano Manner, and the bug seemed random per cast. Mobs we fought were the snake men, the magma wyrm mini boss, Bats, an abductor virgin, and some albinaurics.

### Version

1.3.0 (Latest)

**Comment by LukeYui** [comment]
It's not a bug, sounds like latency
