### ISSUE TITLE
[Bug]: After defeating Elden beast, friend game crashed when choosing an ending

### ISSUE THREAD

**Issue by VeryTrustworthy** [LukeYui/EldenRingSeamlessCoopRelease#412]
### Describe the issue in detail

We defeated the elden beast and chose the Ranni ending, as soon as cutscene was initiated, one of my friend's game crashed, when he reloaded, he was locked in roundtable and unable to interact with anything or fast travel out, nobody was there either. Me and another friend who were playing had no issues, and could initiate NG+

### Steps to recreate the bug

Unsure, beat elden beast and crash game? 

### Version

1.2.5

**Comment by loki2236** [comment]
Maybe to solve your friend issue, he could use Elden Ring Debug Tool by Nordgaren (can find it here con github, just search), to teleport out of RTH.

**Comment by LukeYui** [comment]
Crashing is almost always related to corrupted game files. You could try asking your friend who crashes whether they have tried verifying their files with Steam.
