### ISSUE TITLE
[Bug]: My brother gets more runes from a boss then me

### ISSUE THREAD

**Issue by ToTo-12** [LukeYui/EldenRingSeamlessCoopRelease#414]
### Discord Username

ToCaToi#9144

### Describe the issue in detail

Just like the title says, he also went from +12 to +1

### Steps to recreate the bug

I don't know 

### Version

1.3.0 (Latest)

**Comment by loki2236** [comment]
Duplicate of #358

**Comment by loki2236** [comment]
Also, to fix the flask, use Nordgaren's Elden Ring Debug Tool, to give yourself more sacred tears, but do it while playing solo.

**Comment by LukeYui** [comment]
Getting lower runes as the host should be fixed in 1.3.0. Please add more specifics about this and if you're still having the problem in the latest version.
