### ISSUE TITLE
[Bug]: Respawn at noon, at the grace 'the first step'.

### ISSUE THREAD

**Issue by Hansiriver** [LukeYui/EldenRingSeamlessCoopRelease#415]
### Describe the issue in detail

Hello,sir. When using co-op, I'm finding that i can only respawn at noon at the grace "the first step", in other case i just respawn in the moring. I want to make a mod that allows players respawn in different time, like noon or evening,and even , making it always pass 8 hours when players die. I cant figure it out from event codes. But I found a difference in co-op mod.And I just dont know how to open a .dll file and dont know how this is happening. So please, offer some help.

### Steps to recreate the bug

die at 'the first step'

### Version

1.2.5

**Comment by LukeYui** [comment]
The mod doesn't do anything with time passed since death, sorry I can't help you
