### ISSUE TITLE
[Bug]: Locking on mechanics break after summoning Torrent

### ISSUE THREAD

**Issue by Pav-Osmolski** [LukeYui/EldenRingSeamlessCoopRelease#417]
### Describe the issue in detail

The scenario is with 2 players PvPing at Ordina Liturgical Town.

I am the host, and after using the Judicator's Rulebook/enabling PvP, I should be able to lock-on and fight my friend without interruption.

After summoning Torrent for a short time, R3 lock-on will eventually stop working, but I can still damage my opponent.

The Judicator's Rulebook can also sometimes break, preventing me from restoring neutral mode.

### Steps to recreate the bug

- Summon torrent (as the host)
- Lock-on to opponent and fight whilst on the horse for approx 15-20 seconds
- Toggle R3 locking on and off
- Jump off the horse and try to lock-on again
- The lock-on should then start to act erratically and only locks on for 1-2 seconds at a time
- Eventually it completely breaks and it is no longer possible to lock-on

I have been able to replicate this multiple times after summoning Torrent.

### Version

1.3.0 (Latest)

**Comment by Mrqozy** [comment]
I can confirm this happened to me as well many times.
It doesn't have to be PVP. It happens with normal enemies as well.

**Comment by robbyravioli** [comment]
This has also happened to me and my GF while we were fighting Radahn, Nightrider Calvalry, and the Fallingstar beast.

**Comment by LukeYui** [comment]
Please stop posting duplicate bug reports. #145
