### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by YukishiroEnishi1984** [LukeYui/EldenRingSeamlessCoopRelease#418]
### Describe the issue in detail

Character file is stuck in loading screen while traveling to round table. unable to access character to choose different load location

### Steps to recreate the bug

I was in another players game and loaded in the round table before unlocking the location. When I progressed to the point of unlocking the round table, during the loading screen the game crashed and now the save file is stuck in loading screen loop.

### Version

1.3.0 (Latest)

**Comment by LukeYui** [comment]
Please add a title to your bug report in the future. Also download Nordgaren's debug tool and set flag 105 when you're in the loading screen to fix the issue. (https://github.com/Nordgaren/Elden-Ring-Debug-Tool).
