### ISSUE TITLE
[Bug]: Great enemy felled/Great enemy blind!

### ISSUE THREAD

**Issue by CedricBeaulac** [LukeYui/EldenRingSeamlessCoopRelease#421]
### Describe the issue in detail

Hi, there are a few minor bugs here and there that we can live with (crash etc). But I guess the two main *game-breaking bugs* are the following:

First, the major bosses (Godrick, Rellena) are not functioning properly, simply put they only see one player. They only detect and attack a single player, the one that started the cutscene and when that player dies they stand still until the other players kill them.

Second, the wanderer randomly gets *Great Enemy Felled* prompt and the souls with that. It can happen multiple time in a single session,  in the case of Rellena it would happen basically non-stop, thus re-teleporting the wanderer to Rellena's room (the library every single times).

Both of these have been bug since version 1.1 and are still happening in 1.2 and 1.3.

### Steps to recreate the bug

For the first bug, just fight a major boss in coop and watch him being stupid.

For the second bug, it happens every play session for us unfortunately, I was not able to identify what triggers the issue.

### Version

1.3.0 (Latest)

**Comment by loki2236** [comment]
Duplicate of #64

**Comment by loki2236** [comment]
Also, please report one bug per issue.
Both bugs are known bugs but I doubt I can mark it as duplicate of both
