### ISSUE TITLE
[Bug]: Dualshock 4 controller doesn't work at all in menus or in game.

### ISSUE THREAD

**Issue by RandomBazac** [LukeYui/EldenRingSeamlessCoopRelease#427]
### Discord Username

RandomBazac#0156

### Describe the issue in detail

When opening up the game using the .exe, my dualshock 4 controller instantly disconnects/turns off (using a wired connection). The icons remain for mouse and keyboard evern after pressing a button on my controller. Unplugging and plugging back in the controller makes it have a dim orange light for a second but then turns off immediately after. The controller works on vanilla Elden Ring and other games.

### Steps to recreate the bug

Run .exe, plug in controller, controller does nothing.

### Version

1.3.0 (Latest)

**Comment by loki2236** [comment]
Just tested this with a DS4 and a wired connection, and it works as it should.

Remember to have Steam Input enabled and controller configuration set in Steam.
(I couldn't make it work with DS4Windows unless I set the emulation as an Xbox Controller)
