### ISSUE TITLE
[Bug]: Max HP, FP, and Stamina all get reduced by half when joining or hosting a co-op session.

### ISSUE THREAD

**Issue by BigLoage** [LukeYui/EldenRingSeamlessCoopRelease#429]
### Discord Username

BigLoage#8243

### Describe the issue in detail

I joined my friends session with the effigy of meleina at the site of grace just before the Margit arena, and after getting smoked by Margit a couple times, I realized that my max HP, FP, and Stamina were all half of what they should be. Upon leaving the co-op session via the separating mist, I saw my max HP, FP, and Stamina levels double, returning to their proper stat. When I use the tiny great pot and effigy, without fail all three stats get halved. When I use the separating mist to return to my solo world, they always return to normal levels. I don't have any debuffs, and the same effect happens when I unequip all equipment. My friend is not having this issue, and after searching through what feels like all of google, I think I'm the only person on earth with this issue. Also I am running the current mod version. Thanks for any help that can be provided

### Steps to recreate the bug

Use the tiny great pot or effigy of meleina. It probably won't work for anyone but me, but that's all it takes.

### Version

1.3.0 (Latest)

**Comment by JDoyle64** [comment]
Just to double check, are you higher level than the person you're joining? Default behavior is to scale phantoms down to the level of the host, it doesn't say on the mod page that this has been changed so I'd assume it to be true in the mod too.
