### ISSUE TITLE
1.2.0 not work

### ISSUE THREAD

**Issue by DarkIzuku** [LukeYui/EldenRingSeamlessCoopRelease#43]
version 1.2.0 error when joining the session

**Comment by LukeYui** [comment]
Hi, sorry to hear this. Please try to give as much detail as possible about the issue you're having:

- Do you receive any error messages - If so, which ones?
- Is everyone in your party using v1.2.0?
- How many people are in your group?
- Did you have any problems in 1.1.0 with connections?

Thanks.

**Comment by DarkIzuku** [comment]
> Hi, sorry to hear this. Please try to give as much detail as possible about the issue you're having:
> 
> * Do you receive any error messages - If so, which ones?
> * Is everyone in your party using v1.2.0?
> * How many people are in your group?
> * Did you have any problems in 1.1.0 with connections?
> 
> Thanks.

hello thanks for answering what happens is that when I use the object to create no message comes out and when joining it stays for a while and then it says error when joining the session
