### ISSUE TITLE
[Bug]: Godrick's AI being damaged after one person dies

### ISSUE THREAD

**Issue by EdgarSwann** [LukeYui/EldenRingSeamlessCoopRelease#434]
### Describe the issue in detail

I myself, along with two other friends, were fighting Godrick but after one of us died, Godrick began to "get distracted" and sit or walk towards where that person had died, making the boss become more passive. They were able to hit Godrick a couple of times before threw back some attacks of his own, but he would still go to the spot where the other person had died and become passive once again.

### Steps to recreate the bug

Go to Godrick's fight while in coop. Allow one or more person to die. At least one person needs to stay alive.

### Version

1.3.0 (Latest)

**Comment by Resok** [comment]
I saw this behavior playing vanilla earlier today. Don't think this has anything to do with the mod.

**Comment by Spark-NV** [comment]
Me and my brother have also ran into this one. this bug has caused us to cease our playthough for the time being for the mod to mature some as after 1 person dies you can kinda cheese any boss during the time the boss is distracted trying to focus the dead player.
