### ISSUE TITLE
[Bug]: issue with picking up last sacred tear

### ISSUE THREAD

**Issue by BooBooDaFoo** [LukeYui/EldenRingSeamlessCoopRelease#436]
### Describe the issue in detail

My buddy picked up the last scared tear, and it reset his health and mana potions to 0. Just wondering if there is a fix because we were on Elden beast. Thank you!

### Steps to recreate the bug

pick up last sacred tear.

### Version

1.3.0 (Latest)

**Comment by Xarishark** [comment]
hack it i guess. with cheat engine and the cheat table on nexus mods
