### ISSUE TITLE
Torrent Bugging

### ISSUE THREAD

**Issue by vetterlinj** [LukeYui/EldenRingSeamlessCoopRelease#44]
Torrent has been nearly consistently bugging for us, where one rider will appear to not move (though still animated as if moving) from the other player's PoV. As they move, their name and heath bar flashes back and forth between the location they mounted and their actual location from the PoV of the other player. The player who appears as bugged to the second player sees everything as fine and sees the other player as normal. This has happened to both host and wanderer, though more consistently to the wanderer on 1.2.0 We always saw this bug with just one Wanderer.

**Comment by AranaiRa** [comment]
I can confirm that this is happening to another person I've been playing with.

**Comment by 0m3ga4** [comment]
Me and my partner are also having this issue, both using the latest version of the game and mod as of today.

**Comment by Ginnel** [comment]
This still happens as of today on 1.2.5
