### ISSUE TITLE
[Bug]: "Host's" game crashes after the first phase of Rennala fight

### ISSUE THREAD

**Issue by MikaelL01** [LukeYui/EldenRingSeamlessCoopRelease#442]
### Describe the issue in detail

In two player co-op, after defeating Rennala's first phase, hosts game crashes to desktop. Co-op partner stays in game and the cutscene plays and the fight continues normally.

### Steps to recreate the bug

Rennala fight, game crashes after the first phase in two player co-op game.

### Version

1.3.0 (Latest)

**Comment by LukeYui** [comment]
Verify game files with Steam
