### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by scratch1000** [LukeYui/EldenRingSeamlessCoopRelease#443]
### Discord Username

scratch#8012

### Describe the issue in detail

The game starts with a white screen and the elden ring mouse cursor is there but the game quickly crashes and i have to force close it. 

I found a solution before on the nexus mods page but that is gone now and no one has posted a solution on this page. The vanilla game runs perfectly fine. please help

EDIT: update! i was wrong !!!!! i apologize it just takes 3 minutes and 40 seconds to start  up so not broken  but still a bit frustrating, i might have to  just deal with it. ill leave this thread open just incase someone has a further solution

### Steps to recreate the bug

launch the game through the seemless co-op exe file

### Version

1.3.0 (Latest)

### Relevant Crash log

```shell
The program eldenring.exe version 1.5.0.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 4e828
 Start Time: 01d89ba947415ef3
 Termination Time: 13
 Application Path: D:\steam games\steamapps\common\ELDEN RING\Game\eldenring.exe
 Report Id: c4ac5e66-be36-4cb0-bb22-ab3d197b7403
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Unknown
```

**Comment by LukeYui** [comment]
Is it actually closing or is it just freezing? The mod can take some time to start sometimes

**Comment by 777henley** [comment]
> Is it actually closing or is it just freezing? The mod can take some time to start sometimes

I'm having this same problem, starting through the .exe file, getting a white screen, then it closes.

**Comment by 777henley** [comment]
> > Is it actually closing or is it just freezing? The mod can take some time to start sometimes
> 
> I'm having this same problem, starting through the .exe file, getting a white screen, then it closes.

Ok after deleting the files and trying to just play normally, I'm having the same issue. So I think it's an elden ring/steam thing and not an issue with the mod!

**Comment by 777henley** [comment]
> update! i was wrong !!!!! i apologize it just takes 3 minutes and 40 seconds to start up so not broken but still a bit frustrating, i might have to just deal with it.

oh weird, I was having the problem u described - so I verified the elden ring game files on steam and now the mod launches and loads within a minute!
