### ISSUE TITLE
[Bug]: Elden Ring Rune Glitch

### ISSUE THREAD

**Issue by SickDuck666** [LukeYui/EldenRingSeamlessCoopRelease#452]
### Describe the issue in detail

We defeated a boss in the world then used a grace. My friend received 5k again and made it seem as if a boss was defeated again with "Enemy Felled". Every time he uses a grace he gets another 5k. Every time I use the grace he also gets 5k. Every time he spawns in my world, he gets another 5k.

Quite the bug...

### Steps to recreate the bug

We fought the knight cavalry and he fell off the horse. The horse got glitched in the world, Every time either me or my friend uses a grace, the coop partner gets 5k.

https://www.youtube.com/watch?v=u-Ry69PISBA
https://www.youtube.com/watch?v=Mw_em12YPOQ

### Version

1.3.0 (Latest)

**Comment by LukeYui** [comment]
Please avoid duplicating bug reports #208
