### ISSUE TITLE
[Bug]: Can't enter Forlorn Hound Evergaol

### ISSUE THREAD

**Issue by PHW1234** [LukeYui/EldenRingSeamlessCoopRelease#46]
### Discord Username

PHW#4194

### Describe the issue in detail

I was playing the mod singleplayer to catch a new character up to where my friend left off. When I tried to enter the Forlorn Hound Evergaol it gives me the prompt to enter it but when I click yes or hit E on yes it does nothing.

I was able to do the Forlorn Hound evergaol on my first character in the previous session with my friend.

### Steps to recreate the bug

Go to Forlorn Hound Evergaol in singleplayer go to portal get prompted to enter hit yes nothing happens.

### Version

1.2.0 (Latest)

### Relevant Crash log

```shell
1. Press Win+R
2. Type "eventvwr", and run.
3. Go to "Windows Logs".
4. Go to "Application".
5. Crashes are errors, and are sorted from latest to oldest. Select the most appropriate one.
6. Verify that this is at the beginning: "Faulting application name: eldenring.exe"
7. Paste the log here.
```

**Comment by LukeYui** [comment]
Hi, thanks for the report. This is a new issue and it will be fixed in the next version. For now, you can work around this by using the Tiny Great Pot item to create a session then interacting with the evergaol

Let me know if you have any more issues, or if this doesn't fix it for you.

**Comment by PHW1234** [comment]
The tiny great pot worked. Thanks.
