### ISSUE TITLE
Elden Ring Settingchanges (Bleeding)

### ISSUE THREAD

**Issue by Losdragos** [LukeYui/EldenRingSeamlessCoopRelease#462]
### Discord Username

Vipex#5407

### Describe the issue in detail

Is there a possibility to adjust the settings a little bit? My problem is that the bleeding chance is much too low and is almost not triggered let alone makes damage.

I play the seemless co-op Elden Ring mod with another friend. 

The mod runs really well and everything fits except the bleeding chance. I hope you can help me further. 

Thanks in advance

### Steps to recreate the bug

.

### Version

1.4.3 (Latest)

### Relevant Crash log

```shell
.
```

**Comment by LukeYui** [comment]
Hi, thanks for the report. The status effect resistances for 2 players should be the same as in the base game so I'm unsure why it would be a problem. Can you give me an example of an enemy that is causing problem?

From experience of playing a 2 player game, I have been able to proc bleed multiple times on Godrick with a non-upgraded katana (Around 3 times for the entire fight).
