### ISSUE TITLE
[Bug]: Roundtable Transfer

### ISSUE THREAD

**Issue by TheMadVirtuoso** [LukeYui/EldenRingSeamlessCoopRelease#463]
### Discord Username

Dominik#8429

### Describe the issue in detail

Me and my Sister started playing this Mod yesterday and Melina wanted us to touch us but instead getting teleported to the Raoundtable we were stuck on the grace nothing happend we had to alt f4

### Steps to recreate the bug

We sat next to the General in Caelid I think it is the Grace Inner Aeonia we dont know how to recreate but we just wanted her to tocuh to go to the roundtable yeah thats all

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
Hi, this should have been fixed in 1.4.3 which was released late yesterday evening. Did you definitely update?

**Comment by TheMadVirtuoso** [comment]
Yeah we did not play on 1.4.3 bc Update was not out as we downloaded it so sry for wasteing your time if it happens with our next playthrough i let you know

**Comment by LukeYui** [comment]
No worries
