### ISSUE TITLE
[Bug]: 1.4.3 version doesn't launch correctly

### ISSUE THREAD

**Issue by Re-style57** [LukeYui/EldenRingSeamlessCoopRelease#464]
### Discord Username

Re-style57#1701

### Describe the issue in detail

My friend and me did update to version 1.4.3 by replacing the dll file and the launcher. The mod launch work just fine for my friend. But when I launch the game with the seamless coop launcher  I have the base game with my base save who launch instead. I tried lauching the game without a save file and it create a base game save file. I also tried to launch the game with the 1.4.2 version afterwards and it work just fine.

### Steps to recreate the bug

Replacing the dll file and the launcher of the 1.4.2 version by the dll file and the launcher of the 1.4.3 version and lauching the game via the seamless coop launcher.

### Version

1.4.3 (Latest)

**Comment by ecsos** [comment]
It works for me maybe you have it blocked by windows. Right click on folder and open terminal
Get-childitem -recurse | unblock-file

**Comment by Re-style57** [comment]
Thank you for helping me. I tried and it doesn't work unfortunately. I tried to launch with Elden mod loader as well and it says "Failed to load elden_ring_seamless_coop.dll". I add the log of the mod loader if it can help. And again if I replace the dll with the 1.4.2 version it works perfectly.
[mod_loader_log.txt](https://github.com/LukeYui/EldenRingSeamlessCoopRelease/files/10470751/mod_loader_log.txt)

**Comment by HarleyDoom** [comment]
Me and my brother experienced this exact bug but with an additional note, when updating to the new version I forgot to enter a password and the game launched correctly but was obviously unable to begin co-op, as soon as I updated the .ini with a password the above mentioned bug began for both of us

**Comment by Re-style57** [comment]
I got the solution ! I did make an exeption for the Elding Ring folder in my antivirus and it worked. Turning off the antivirus doesn't work.
