### ISSUE TITLE
[Bug]: Round table warp stuck

### ISSUE THREAD

**Issue by TheShadowOfLynx** [LukeYui/EldenRingSeamlessCoopRelease#465]
### Discord Username

TheShadowOfLynx#5582

### Describe the issue in detail

I was sitting at a site of grace. I clicked on the button "go to round table" or sth. after ive done that, i got into a loading screen that loaded me in and 1 second after out again again and again and again. i restarted my game, loaded my safe and was stuck again. Updating to ver. 1.4.3 didnt help either.

### Steps to recreate the bug

.

### Version

1.4.3 (Latest)

**Comment by TheShadowOfLynx** [comment]
do i have to do this while i am in loading screen?

**Comment by TheShadowOfLynx** [comment]
wait can u just explain me how to use this excactly? i am a bit confused haha

**Comment by TheShadowOfLynx** [comment]
nvm got it, thank you for helping <3

**Comment by LukeYui** [comment]
Glad it's resolved
