### ISSUE TITLE
[Bug]: Torrent causes other players to become invisible 

### ISSUE THREAD

**Issue by MarleyLO1** [LukeYui/EldenRingSeamlessCoopRelease#467]
### Describe the issue in detail

Summoning torrent often causes you to become invisible for your coop partners. 

Getting off of torrent will make you reappear.

Using latest update from Jan 19 at 6:00pm (1.4.3).

### Steps to recreate the bug

Summon torrent.

### Version

1.4.3 (Latest)

**Comment by cjbottaro** [comment]
I'm not sure if this is related, but we have the kinda the opposite problem in our game: Torrent is sometimes invisible, but the player isn't. Remounting him usually fixes it though.

**Comment by Emtews** [comment]
same

**Comment by Kertit** [comment]
Can reproduce as well. playing with my wife we're becoming invisible when moutning Torrent and get back to normal when dismounting. 
BUT we can still fight normally, just that we cannot see each other.
