### ISSUE TITLE
[Bug]: Targeting problems when on Torrent (horse / mount)

### ISSUE THREAD

**Issue by cjbottaro** [LukeYui/EldenRingSeamlessCoopRelease#470]
### Discord Username

cjbottaro#8236

### Describe the issue in detail

First off, thanks for the incredible mod!

Being mounted on Torrent causes targeting issues. When I engage enemies on Torrent, I lose the ability to target them. Dismounting Torrent _does not_ fix the issue; they are still not able to be targeted. The bug happens with normal enemies out in the overworld as well as field bosses.

The workaround is that all players dismount before engaging enemies.

I'm not sure if this affected by party size; we only play in a party of 2.

I'm unsure, but I think this might only affect non-host players. Edit: No, it definitely affects the host player too.

### Steps to recreate the bug

I think the most simple way is to have the entire party engage in mounted combat. Pretty quickly, you will lose the ability to target the enemy.

### Version

1.4.3 (Latest)

**Comment by Nightrose2016** [comment]
I have had it happen when in dungeons so its not just torrent causing it.

**Comment by cjbottaro** [comment]
Release 1.4.5 fixed this for me! Thank you sooo much!
