### ISSUE TITLE
[Bug]: Losing Dragon Incantation Unlocks

### ISSUE THREAD

**Issue by magicjakester** [LukeYui/EldenRingSeamlessCoopRelease#471]
### Describe the issue in detail

My friend is hosting a world and we killed dragons that unlock the different communion incantations. Upon separating from their world and then coming back later, all incantation unlocks are unavailable for purchase at the communion. 

### Steps to recreate the bug

Join friends world.
Kill dragon that unlocks incantation.
Leave world. 
Rejoin world. 
Incantation is no longer available for purchase. 

### Version

1.4.3 (Latest)

**Comment by rober188** [comment]
Similar thing happened for me with the Turtle pope. (thankfully I purchase everything as soon as I hand over the book/scroll just in case)... I should go get all of the dragon incants I want... brb.
