### ISSUE TITLE
[Bug]: Unable to take Rya's hand

### ISSUE THREAD

**Issue by CentPapi** [LukeYui/EldenRingSeamlessCoopRelease#473]
### Discord Username

Cent#2035

### Describe the issue in detail

When I went to talk to Rya so that she could take me to volcano manor I exhausted her dialogue and when I went to take her hand for some reason my character began to walk but they never took her hand and I was not able to access volcano manor. I have tried talking to her multiple times, Resting at graces, Re launching the game and a bunch of other things but I still have not found a way to make her work. This glitch has also been happening to a couple of my friends and we are kind of stuck.

### Steps to recreate the bug

Go to the Grand lift of Dectus and talk to Rya when she asks you to take her hand accept, the character will begin to walk forward and then nothing will happen. The player is supposed to be teleported into volcano manor but in this case they just walk forward a little and are not teleported anywhere.

Below is a video of what happened when I took her hand.
https://user-images.githubusercontent.com/123428967/214193215-945372ec-ed97-4f78-aac5-58429944062f.mov

### Version

1.4.3 (Latest)

**Comment by melladh** [comment]
Same issue. I was then unable to control my character or interact with my inventory or the Quit Game button, forcing me to hard kill the game.
I was at the Erdtree-Gazing Hill, with one more coop party member

**Comment by ketsuban** [comment]
Our group had a similar problem to this: the host could complete the animation successfully but wasn't teleported to Volcano Manor, while the guests walked off and were softlocked. We ended up doing it in solo and then rejoining one another afterwards. The same thing happened when hugging Fia in the Roundtable Hold.
