### ISSUE TITLE
[Bug]: Died as soon as Godrick died, was unable to respawn

### ISSUE THREAD

**Issue by JustinM318** [LukeYui/EldenRingSeamlessCoopRelease#475]
### Discord Username

ultra_beaman#5134

### Describe the issue in detail

I was fighting Godrick with my friend. I died about 1-2 seconds before he killed Godrick. The game gave me the correct items and souls but never spawned me back into the game. I assume this is some weirdness with how boss fights work with the mod. The only way to spawn back in was to trigger a loading screen.

### Steps to recreate the bug

- Fight Godrick (or probably any boss) with a friend
- Die around the same moment Godrick is killed
- Stuck spectating with no hud spectator message

### Version

1.4.3 (Latest)

**Comment by cjbottaro** [comment]
This exact same thing happened to us. Gf died pretty much at the same time the killing blow landed on Godrick. I had to rest at site of grace to trigger her "You Died" screen.

This seems to happen on all bosses though. Spectator mode is supposed to be a feature. Problem is we don't know how to exit spectator mode and trigger respawn.

**Comment by LukeYui** [comment]
Sitting at a site of grace will allow spectating players to respawn.
