### ISSUE TITLE
[Bug]: Warp voting unreliable after update 1.4.3

### ISSUE THREAD

**Issue by MadMick96** [LukeYui/EldenRingSeamlessCoopRelease#476]
### Describe the issue in detail

After updating today, warp voting seems to work very unreliably. It seems votes are not being registered properly a lot of the time for the other player. Both players (2 players in world) will see "you have voted to warp to x", but the warp never happens.
Eventually, the vote will cancel, and then either it will work or a repeat of the bug will happen. 

Anecdotally, it seemed that the host voting first worked more reliably.

This did not happen for us even once in 20 hours on 1.4.2, but now happened like ten times during two hours on 1.4.3

### Steps to recreate the bug

Caelid warps mostly, maybe has to do with voting to warp at the same time, seemed to be more unreliable anecdotally.

### Version

1.4.3 (Latest)

**Comment by M3n4p** [comment]
Same here.
It seems to be completely independent of timing. We tried doing it immediately and waiting for nearly the entire duration of the vote. Still happening. But it's also more or less random.

It didn't happen if we (2 players) alternated who started the vote after it happened once, starting with the one that didn't start the very first vote.

**Comment by HarleyDoom** [comment]
Also experienced this bug, was intermittent but the second vote would always work for me and my co-op partner

**Comment by Muramas** [comment]
Same, I wish there was a setting for just host warps and joiners do a majority vote

**Comment by LukeYui** [comment]
I haven't experienced this bug but I'm aware.

**Comment by andreycout** [comment]
Also happening to me. Used to happen once in a while before 1.4.3, but became way more frequent after updating. Would also enjoy an option to force warp as I'm just playing with my wife and the voting is unnecessary and a bit annoying.

**Comment by cjbottaro** [comment]
Same issues as everyone else. We also experimented with the timing to see if that changed anything, but no. It does seem to happen randomly.

> Would also enjoy an option to force warp as I'm just playing with my wife and the voting is unnecessary and a bit annoying.

In the exact same boat and would also love that option!

**Comment by jujulogey** [comment]
Can confirm that warping is unreliable (2 players.)  First warp fails 75% of the time when the host initiates it.  Only noticed this as of 1.4.3.

I know LukeYui is aware.  Just putting these here to let everyone know its not just one person!

**Comment by LukeYui** [comment]
I've rewritten the voting systems in 1.4.4, so it should be resolved when that is released.
