### ISSUE TITLE
[Bug]: Coop-Partner's Player model stuck while riding Torrent after moving on Mausoleum.

### ISSUE THREAD

**Issue by M3n4p** [LukeYui/EldenRingSeamlessCoopRelease#477]
### Discord Username

M3n4p#3630

### Describe the issue in detail

After moving on top of a Mausoleum while on Torrent and then moving off the Mausoleum, the model of the coop-partner gets stuck. It plays all the correct animations (moving, healing, etc.) but doesn't move along with the actual player position leading to the other player being invisible but still being able to interact with everything. For the other person, their game behaves as normal.

The HUD jumps constantly between the model and the actual position the coop-partner is at. After demounting, the player model jumps to the actual position. After mounting Torrent again the problem persists but the model now is stuck at the position where you remounted Torrent. Gameplay is not affected by this. Everything is still synced up as always, only the model is stuck at the mounting position.

If the other person jumps back onto the Mausoleum, the model gets properly realigned as long as they are on the Mausoleum.

The bug persists throughout sessions. Closing a session and then reopening and reconnecting, the bug still occurs. It gets fixed after warping to a Site of Grace. Resting does not fix it. So a total reload of the models probably fixes the bug.

### Steps to recreate the bug

Coop-partner gets onto a Mausoleum and then gets off it while on Torrent.

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
I remember this bug way back in the alpha version. I'm not sure how you're still experiencing it as I was pretty sure I'd fixed it. I'll look into it again.

**Comment by LukeYui** [comment]
Fixed in upcoming 1.4.4

**Comment by M3n4p** [comment]
BTW, this also happens in Nokron. At the ruins where you find the Ancestral Infant's Head. I don't know if the fix also encompasses this. I'm not sure what exactly triggers the glitch there, as it only happened to one player.

**Comment by LukeYui** [comment]
Should be fixed. Feel free to post again if it's still causing problems
