### ISSUE TITLE
[Bug]: Ulcerated Tree Spirit (Fringefolk Hero's Grave Boss) mod 1.4.3

### ISSUE THREAD

**Issue by Xenowest** [LukeYui/EldenRingSeamlessCoopRelease#480]
### Describe the issue in detail

My friend (the host) and I were fighting the boss (Ulcerated Tree Spirit) and when my friend gave the final blow, everything was normal for him he had the normal animation after defeating a boss etc.
But for me the boss froze with a very low hp bar and then a loading screen teleported me back to a previous site of grace...and disconnected me from coop, i had to reuse Effigy of Meleina to get back together then the I got the achievements of defeating the boss and the item and skill that come with it BUT I didn't get the runes...

Thank for this mod and the great work behind , regardless of the bugs its very fun to play it in coop !!

### Steps to recreate the bug

A party of 2 players.
One player is the host and everything is fine, the bug appears on the joining side.
The host Defeats Ulcerated Tree Spirit
The non host player will see the boss frozen then will get a loading screen.

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
Unless you've experienced this before it sounds like your internet cut out briefly, or you lost connection to the host. I don't think it's specific with that boss in particular it just sounds like bad timing.

Feel free to correct me if you continue to experience this.
