### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tanerkennedy** [LukeYui/EldenRingSeamlessCoopRelease#481]
### Discord Username

annem de öyle diyordu#2224

### Describe the issue in detail

When me and my friend wants to teleport our first attempt always result with fail we have to vote 2 times and after our first attempt time we have to wait for failed notification and vote again.

### Steps to recreate the bug

me and my friend want to teleport and always first one result with fail

### Version

1.4.3 (Latest)

**Comment by HarleyDoom** [comment]
Duplicate of #476

**Comment by LukeYui** [comment]
As above, thank you
