### ISSUE TITLE
[Bug]: leveling issue?

### ISSUE THREAD

**Issue by zeldalinkgeek** [LukeYui/EldenRingSeamlessCoopRelease#482]
### Discord Username

zeldalinkgeek#1412

### Describe the issue in detail

I downloaded this mod yesterday and was running through the game with my sister and my cousin. We were having an awesome time with this mod even with knowing some of the provided bugs! But there is a bug I can't seem to find anyone else struggling with, every time they have tried to lvl up vigor their red bar doesn't increase but in the Stat menu they are still getting more hp. Is this a known problem?, is there anyway to go about fixing it?

### Steps to recreate the bug

1.) aquiring runes
2.) leveling up vigor
3.) checking the health bar

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
I'm not sure what you're describing, but this isn't a bug with the mod. Even if the HP bar doesn't increase in size too much, it doesn't necessarily mean that the HP isn't going up, it just might be more condensed.

I'll close this for now.
