### ISSUE TITLE
Fast traveling not working[Bug]: 

### ISSUE THREAD

**Issue by Moobykin** [LukeYui/EldenRingSeamlessCoopRelease#484]
### Discord Username

Moobykin

### Describe the issue in detail

When my husband and I are playing and we are trying to port somewhere, it is not working. We will have to wait till one of us fails and then we try again. This can sometimes take up to 3 mins of trying and gets very frustrated. It does not matter if he is the host or if I am, it still bugs. This is a recent bug.

### Steps to recreate the bug

Go to map, select a grace to port to, click it and hit yes, and it fails and we just stand there.

### Version

1.4.3 (Latest)

**Comment by cjbottaro** [comment]
I think this is a dup of #476

**Comment by Moobykin** [comment]
I’m sorry. I didn’t realize I’d put in two bugs that had already been sent in.

Devon Butner

Educational Assistant

“When I dare to be powerful – to use my strength in the service of my vision, then it becomes less and less important whether I am afraid.”
-Audre Lorde
________________________________

**Comment by LukeYui** [comment]
No worries, I'll close this as a duplicate for now.
