### ISSUE TITLE
Horse targeting broken[Bug]: 

### ISSUE THREAD

**Issue by Moobykin** [LukeYui/EldenRingSeamlessCoopRelease#485]
### Discord Username

Moobykin

### Describe the issue in detail

When fighting horseback and target something, suddenly the targeting is messed up and the enemy will not stay targeted. When we get off of the horse it is still broken until we port to a grace.

### Steps to recreate the bug

Get on horse. Target an enemy. Cast. Enemy becomes untartgetable and we die. 

### Version

1.4.3 (Latest)

**Comment by cjbottaro** [comment]
I think this is a dup of #470

**Comment by LukeYui** [comment]
> I think this is a dup of #470

As above, thank you.
