### ISSUE TITLE
[Bug]: Cannot Rest at Sites of Grace

### ISSUE THREAD

**Issue by rmbwashere** [LukeYui/EldenRingSeamlessCoopRelease#49]
### Discord Username

robbie papa#4878

### Describe the issue in detail

I was playing with two other friends when we were all going to rest at the Church of Elle. Ranni appeared and repeated her dialogue about Torrent. After that, I could no longer rest at any Sites of Grace, or discover new ones. I can, however, still fast travel to all of the ones I've previously discovered. I can also rejoin the same friends, and I can rest at their Sites of Grace. I've tried dying, resetting, shutting down and relaunching, yet the problem persists. Any help would be appreciated!

### Steps to recreate the bug

Go to any Site of Grace and try to rest, a pop up appears stating that I can't rest at this time.

### Version

1.2.0 (Latest)

**Comment by LukeYui** [comment]
Hi, thanks for the report.

I'll look into it
