### ISSUE TITLE
[Bug]: eldenmodloader > failed to load elden_ring_seamless_coop.dll

### ISSUE THREAD

**Issue by Sylverix** [LukeYui/EldenRingSeamlessCoopRelease#490]
### Discord Username

Sylver#4307

### Describe the issue in detail

elden_ring_seamless_coop.dll cannot be found/played by Mod Loader or Mod Engine 2. There's also an issue where only following basic installation instructions for SeamlessCoop works half the time.

My apologies if this doesn't seem like a bug, but I feel like I've discovered an issue that people are discussing but not with what I've been currently experiencing. When trying to play with the SeamlessCoop mod, these are the issues that occur for me:

1. When following the basic installation instructions on the Discussions Page:
     a. The mod seems to boot up properly for the first dry run. I've created my character, started the game, and promptly quit to desktop because there are other mods I enjoy playing with that I wish to add.
     b. When loading it up again (without adding Mod Loader nor any mods), there is a 50% chance that the mod will work and 50% chance that I get "_inappropriate activity detected_". If I get the "_inappropriate activity detected_" message, the mod will no longer work no matter how many times I rerun the game. I'd have to remove the mod, verify game files, and reinstall the mod.

2. When adding Elden Ring Mod Loader:
     a. If the SeamlessCoop mod works and hasn't given me the "_inappropriate activity detected_" message, I then try to install the Mod Loader mod along with Mod Engine 2 in order for me to keep mods separate from the Elden Ring Game folder.
     b. This is where the main issue comes in. Once I've added the "_mods_" folder along with the Mod Loader .dll files and followed MintedTea's Guide to use Mod Engine 2, the SeamlessCoop mod stops working entirely. From my troubleshooting efforts, it appears that there is some sort of conflict going on with how the SeamlessCoop .dll and .ini need to be placed, as well as maybe some sort of conflict with the dinput8.dll.
     c. When adding the Mod Loader contents to the game folder and putting the SeamlessCoop .dll and .ini within the mods folder, running the SeamlessCoop .exe shows that it failed to find "_SeamlessCoop//elden_ring_seamless_coop.dll_". This tells me that it's strictly looking for the folder SeamlessCoop before it looks for the .dll. So, if I add the folder (with the contents) into the mods folder, I get the same error, which tells me that it can only find the folder and contents within the root Game folder. Adding it back somehow conflicts with the Mod Loader contents and will no longer work. By removing everything and verifying integrity of the game will return things to normal, but I may encounter the SeamlessCoop mod working half the time as suggested in the first section.
     d. Since I still have my coop save file, if I put the Mod Loader contents in first and then throw the SeamlessCoop contents into the "mods" folder and attempt to launch Elden Ring using ModEngine2's _launchmod_eldenring.bat_, I get error "_failed to load elden_ring_seamless_coop.dll_" on startup and then get the "_inappropriate activity detected_" message.

No matter what I do, SeamlessCoop cannot be played using Mod Loader and Mod Engine 2. I have tried my best troubleshooting this issue by following everyone's suggestions within the "Posts" section, as well as in other mods' "Posts" section. What I've done:

1. I've followed the basic installation instructions "To a T". Meaning I've followed every detail and have done it numerous times.
2. I've followed the instructions for "Using Seamless Coop with Mod Engine 2" by MintedTea numerous times.
3. Elden Ring has been whitelisted within my Antivirus Program (I use Avast). I've even turned off my anitvirus software for further troubleshooting.
4. I've ran the SeamlessCoop .exe and _launchmod_eldenring.bat_ as admin
5. I've modified the Mod Loader .ini to point to the _elden_ring_seamless_coop.dll_ and had set it to "1" in the [loadorder] section. I've even modified the load_delay parameter.
6. I've followed troubleshooting advice on the "_Posts_" Section of SeamlessCoop dating from the release of 1.4.3 till now. I've even utilized Google and came across other mod pages with posts relating to SeamlessCoop issues.
7. I've deleted the mod(s) and verified the integrity of Elden Ring's game files countless times.
8. I've tried placing the SeamlessCoop folder in every folder location (Game, mods (Mod Loader), and mod (ME2)). I've also tried having the SeamlessCoop folder with the Game folder and putting the .dll and .ini in the mods folder (Mod Loader) and the mod folder (ME2).

The mod is only functional for me if that is the only thing I touch when installing it, and even then, like I said in the beginning, it works 50% of the time. I even tried looking through your GitHub Mirror to try and get version 1.4.2 since that was last version I played on that worked but cannot find the downloadable files to play it.

I apologize if I sound rude, or come off as passive aggressive or anything, I'm just frustrated with the extent of troubleshooting that I have done with this mod. The mod is fantastic and I appreciate the work you've done!

If this is not a something you're willing to deal with as it is not an in-game bug, I understand. Just let me know.

### Steps to recreate the bug

1. I've followed the basic installation instructions "To a T". Meaning I've followed every detail and have done it numerous times.
2. I've followed the instructions for "Using Seamless Coop with Mod Engine 2" by MintedTea numerous times.
3. Elden Ring has been whitelisted within my Antivirus Program (I use Avast). I've even turned off my anitvirus software for further troubleshooting.
4. I've ran the SeamlessCoop .exe and _launchmod_eldenring.bat_ as admin
5. I've modified the Mod Loader .ini to point to the _elden_ring_seamless_coop.dll_ and had set it to "1" in the [loadorder] section. I've even modified the load_delay parameter.
6. I've followed troubleshooting advice on the "_Posts_" Section of SeamlessCoop dating from the release of 1.4.3 till now. I've even utilized Google and came across other mod pages with posts relating to SeamlessCoop issues.
7. I've deleted the mod(s) and verified the integrity of Elden Ring's game files countless times.
8. I've tried placing the SeamlessCoop folder in every folder location (Game, mods (Mod Loader), and mod (ME2)). I've also tried having the SeamlessCoop folder with the Game folder and putting the .dll and .ini in the mods folder (Mod Loader) and the mod folder (ME2).

### Version

1.4.3 (Latest)

### Relevant Crash log

```shell
no crashes. just doesn't work properly.
```

EDIT: Here are links to images as references to the issue:

1. Using Mod Loader and ME2 with SeamlessCoop contents: https://pasteboard.co/d0E6UA6Tjqeg.png
2. After executing the launchmod_eldenring.bat: https://pasteboard.co/5iB2ZfZNbon6.png
3. Current Save files: https://pasteboard.co/AfsW0NysuihA.png
4. After deleting every mod, reverifying game files, re-extracting Seamless mod, and adding it to game folder: https://pasteboard.co/jpFPepmthLmh.png
5. After closing the game, waiting a moment, and relaunching: https://pasteboard.co/zVOE0rD63yoD.png

Once the fifth issue occurs, I will continuously get the activity error until I start fresh again, but then the cycle repeats.

**Comment by Sylverix** [comment]
UPDATE: I've looked around your GitHub Mirror more and finally found version 1.4.2. I've installed it with the Mod Loader and loaded it via ME2. I can confirm that 1.4.2 still works with Mod Loader and ME2.

However, my issue with version 1.4.3 still stands. I will be playing on version 1.4.2 in the meantime.

**Comment by LukeYui** [comment]
Thanks for the report. I'm aware that some users can't use other launchers to load seamless co-op at the moment with 1.4.3.

I've asked some people to test it with 1.4.4 and the issue seems to be fixed in this upcoming version. No idea why it isn't working for 1.4.3 but whatever I've changed seems to have fixed it.

**Comment by Sylverix** [comment]
Hey LukeYui,

Thank you for getting back to me on this! Glad to know that 1.4.4 works and I'm looking forward to its release!

Once again, I apologize if I came off harshly regarding this issue! Thank you for your hard work!

Since it looks like you will be releasing 1.4.4 in the near future, I will proceed to close this issue.

To anyone who came here looking for a resolution to this same issue, please try the above steps first listed in my troubleshooting steps to see if any of those resolves your issue. If not, please use LukeYui's GitHub mirror to install version 1.4.2.
