### ISSUE TITLE
[Bug]: Finger reader Enia missing only when in co-op.

### ISSUE THREAD

**Issue by Drew9140** [LukeYui/EldenRingSeamlessCoopRelease#491]
### Discord Username

Drew9140#9914

### Describe the issue in detail

She is there if using the mod in solo. However, once my friend joins me, she disappears only for me. Once we rest at the round table, she is gone for him a well.

### Steps to recreate the bug

Described in the description, don’t know how it started tho.

### Version

1.4.3 (Latest)

**Comment by jujulogey** [comment]
Round table is very buggy.  It's probably best to only use the RT when you're separated into your own world

**Comment by LukeYui** [comment]
Fixed in 1.5.0
