### ISSUE TITLE
[Temp Fix for Bug]: How to work around the current warping bug in 1.4.3

### ISSUE THREAD

**Issue by justinooncx** [LukeYui/EldenRingSeamlessCoopRelease#492]
### Discord Username

JunoStriker#8114

### Describe the issue in detail

After testing with a friend, we figured out how to get around the bug where warp-voting fails constantly. Using this method, your warp votes should work 100% of the time. Unfortunately, haven't tested with more than 3 players, but in theory, as long as the last person who starts the vote is different every time, it SHOULD work. At the very least, this might give some insight on what's wrong with the code.

### Steps to recreate the bug

1. At the start of the session (upon using the Pot to open up the world), keep note of who was the last person to do a warp. 
   1a. If no warps have been done prior, anybody should be able to start the first warp.
2. When you want to warp a second time, make sure the other person who didn't initiate the last warp starts the vote.
3. From then on, simply alternate between who starts the warp vote, ensuring that the same person doesn't do it twice in a row.
   3a. This works fine with 2 players, but this hasn't been tested with 3 or more. The no-repeat rule should still apply, though.

### Version

1.4.3 (Latest)

**Comment by jujulogey** [comment]
Figured this one out too!  It does work.  Can't wait for the update though.

**Comment by Pwrhngry** [comment]
How do you vote, we have no hit X key to vote message.  we don't know how to vote to travel.

**Comment by ViktorSarkozi** [comment]
> How do you vote, we have no hit X key to vote message. we don't know how to vote to travel.

Everybody needs to select the grace on the map where they want to travel to.

**Comment by cjbottaro** [comment]
Thank you sooooo much for this workaround, it was driving us crazy!

> How do you vote, we have no hit X key to vote message. we don't know how to vote to travel.

Yeah, you "vote" by opening the map and trying to fast travel to the same site of grace as the person who initiated the "vote" (i.e. the first person to initiate fast travel).

It's definitely not as intuitive as a dialog box that let's you say "yes" or "no" to the vote... but why vote at all? We're all (presumably) playing with friends! Why not just let anyone initiate fast travel with no vote?

**Comment by LukeYui** [comment]
Should be fixed. Feel free to post again if it's still causing problems

**Comment by cjbottaro** [comment]
Yessss, thank you! Fixed in 1.4.5!
