### ISSUE TITLE
[Bug]: Post-Radahn Ranni NPC bug

### ISSUE THREAD

**Issue by Glowbaries** [LukeYui/EldenRingSeamlessCoopRelease#493]
### Discord Username

Eien. (MIA)#2715

### Describe the issue in detail

Me and my friend had just grabbed the Nokron Treasure and when we went back to Ranni, we both talked to her. Afterwards, her dialog reset to an older text for my friend and we both got trapped in a Mist Barrier and couldn't teleport out. We have been completely locked in the Mist Barrier and we can't do anything regardless. Me and my friend are currently around level 75 and past the halfway mark through the game. I do NOT want to restart.

### Steps to recreate the bug

Speak to Ranni at the starting area, continue her questline until the Radahn Festival, after Radahn's defeat, explore Nokron and gain the hidden treasure. After gaining the Hidden Treasure, have the original host to the world talk to Ranni and the second player talk to Ranni as well. One player should gain the Carian Inverted Statue. Both players should end up trapped in a Mist Barrier.

### Version

1.4.3 (Latest)

**Comment by flador** [comment]
I was soft-locked in a similar situation.

### Version
1.4.3
### Steps to recreate the bug
In my case, my friend and I spoke to Ranni for the first time after Radahn was already slain, but we had not gone to Nokron. Both of us spoke to her at the same time, accepting all dialogue prompts. The mist barrier appeared to stop us from leaving until we talked to her followers, and when that was done we both talked to her at the same time again and she went to sleep. As this was happening, I fell off the roof and died. When I was dead, the camera stuck to my corpse and did not go to spectating, and I was unable to leave or respawn without Alt-F4ing the game, which I did. After that, the mist barrier is still up in both our worlds and Ranni is asleep. No amount of reloading the game, dying, passing time, or anything else has removed the barrier, so we are both unable to warp or leave.

**Comment by KennethPeen** [comment]
Me and my friend also have this problem please fix we are both over level 90 and dont want to restart

**Comment by wilou525** [comment]
Verified that the problem exists also with version 1.4.4.

**Comment by wilou525** [comment]
We got out from Ranni's tower area by using Elden Ring Debug Tool's teleporting functionality (warp). We were able to complete Ranni's quest line after that as well. Hope this helps.

**Comment by thejiggysaw** [comment]
> 

not familiar with the debug tool is there any help you could provide?

**Comment by thejiggysaw** [comment]
> We got out from Ranni's tower area by using Elden Ring Debug Tool's teleporting functionality (warped to a site of grace outside of Ranni's area). We were able to complete Ranni's quest line after that as well. Hope this helps.
> 
> Elden Ring Debug Tool is a separate application available at: https://github.com/Nordgaren/Elden-Ring-Debug-Tool/releases

lol okay i was able to teleport out but when you get close to  ranni's tower you cant travel to any graces unless you use the debug, going to try the throwaway technique when my buddy is home
