### ISSUE TITLE
password[Bug]: 

### ISSUE THREAD

**Issue by emojackblack** [LukeYui/EldenRingSeamlessCoopRelease#494]
### Describe the issue in detail

When I have saved a password (correctly, with the space and everything), if i try to use one of the online items it says i need to set a password. idk whats wrong.

### Steps to recreate the bug

dont know

### Version

1.4.3 (Latest)

**Comment by ViktorSarkozi** [comment]
1. You may want to upload your seamlesscoopsettings.ini file, so devs can look at what's wrong with your password.
2. I suggest you run launch_elden_ring_seamlesscoop.exe in Administrator mode. This worked for me when I was not able to start a session.

**Comment by LukeYui** [comment]
To improve this report, please upload a screenshot of your Elden Ring/Game folder, and the location of your seamlesscoopsettings.ini file.

**Comment by LukeYui** [comment]
Closed due to inactivity.
