### ISSUE TITLE
[Bug]: Radahn not dropping souls when in death/spectator cam

### ISSUE THREAD

**Issue by M3n4p** [LukeYui/EldenRingSeamlessCoopRelease#496]
### Describe the issue in detail

I died while fighting Radahn and my friend (host) managed to kill him. I didn't get the runes he should drop even after the revival loading screen but my friend did.
I didn't pick up the dropped runes from the last try and after respawning from the successful try they were set to 0.

### Steps to recreate the bug

Die to Radahn. In the next try, die without picking up your lost runes. If coop-partner kills Radahn you should not receive the boss runes and your old runes are gone.

### Version

1.4.3 (Latest)

**Comment by jmueller42** [comment]
Happened to me as well exactly as described.

**Comment by RevanProdigalKnight** [comment]
This just happened in 1.4.5 as well, my friend (who was hosting) died and I killed Radahn. My friend didn't get the souls and was unable to watch the cutscene after the fight.
