### ISSUE TITLE
[Bug]: Player always left

### ISSUE THREAD

**Issue by Aerox93** [LukeYui/EldenRingSeamlessCoopRelease#499]
### Discord Username

Aerox93#2676

### Describe the issue in detail

A player always the same one is automatically thrown out of the session after about 2 minutes

### Steps to recreate the bug

.

### Version

1.4.3 (Latest)

**Comment by Mkeefeus** [comment]
I have a friend also experiencing the same issue. Updated game and mod, no other mods installed. My other friends can all play together fine
