### ISSUE TITLE
Visiting Round Table Hold causes site of grace issues

### ISSUE THREAD

**Issue by toshirohex** [LukeYui/EldenRingSeamlessCoopRelease#5]
Whenever I'm not the host and I visit the round table hold, all the of sites of grace become the hitbox of the roundtables table of grace.  Rejoining fixes this issue but whenever we visit roundtable again it causes it again.

There will also be random times when I'll rest at a site of grace and she'll ask me to come to the round table despite me already visiting it.

**Comment by LukeYui** [comment]
Should be fixed in 1.2.0
