### ISSUE TITLE
[Bug]: Gurranq not giving out rewards to cooperators

### ISSUE THREAD

**Issue by Katarisu** [LukeYui/EldenRingSeamlessCoopRelease#50]
### Describe the issue in detail

I was in a friend's world and turned in a second deathroot to Gurranq, only for him to not give any reward to the cooperators. The first deathroot gave out rewards as expected.

### Steps to recreate the bug

While summoned as a cooperator (not hosting), turn in a second deathroot to Gurranq.

### Version

1.2.0 (Latest)

**Comment by LukeYui** [comment]
Hi, thanks for the report. I believe this is caused by the item being given to only 1 player. I've taken a look and corrected it for the next version.

Can I just confirm that the host gets the items normally, and it's just the co-operators that miss out?

**Comment by Katarisu** [comment]
Yes, that is correct, the host got the item normally.
