### ISSUE TITLE
[Bug]: mod exe opens up unprotected main game, no mod

### ISSUE THREAD

**Issue by Evanogs** [LukeYui/EldenRingSeamlessCoopRelease#501]
### Discord Username

Evanogs#4879

### Describe the issue in detail

My friend just got the game on her new pc and opened the mod and played on it before the main game. she then opened a normal game and now whenever she opens the mod exe it launches an unprotected normal game. re-installing elden ring and the mod did nothing

### Steps to recreate the bug

play the mod before playing the main game, then play the main game

### Version

1.4.3 (Latest)

**Comment by Triskelli0n** [comment]
I have had a similar issue. except I had played the game before installing the mod, but it had been several months since last opening the game. I have tried running as admin or just running the launcher but its a coin toss if it will actually load in the mod.
