### ISSUE TITLE
[Bug]: Quest progress regression, and desync issues.

### ISSUE THREAD

**Issue by rober188** [LukeYui/EldenRingSeamlessCoopRelease#508]
### Discord Username

Lepren#2616

### Describe the issue in detail

So... I think this is really one issue, and I've been seeing it reliably with multiple different people playing with me:

- quest progress for people in the round table will appear to be reset (ex: spirit tuner will go back to being by the fire even though both players have progressed her character to the point where she upgrades spirits) semi-randomly. I tried fixing it by having both me and my friend progress the roudtable characters while separately playing solo, but when we go back to playing together even with all the characters with matching state flags, they will randomly snap back to a previous state.

- This also applies to the finger reader crone next to the two fingers who will just despawn randomly as if at the start of the game, and me and the other players will have to take turns leaving, resetting the game, rejoining, etc in hopes that it updates. 

- Gurranq appears to have a similar issue, but worse, where even if all players are on the same gurranq step (and optionally even if we interact with gurranq separately and only in single-player) after cooperating, Gurranq will get bugged where he no longer gives you any rewards for deathroot because he will constantly be trying to give you the first reward (I found that bit out after deciding to poke around). This looks a little different when you're running the game, but it appears to stem from the same issue.

- The primary questline, Dung Eater, & Ranni questlines **have not been effected** for me (although based on other comments in this bug forum it appears that some people are unable to complete the Ranni ending). 

Oh... Also Greyoll will just randomly die sometimes shortly after you kill the first dragon. No idea why. You'll get the 5 hearts and 70k-ish-I-don't-remember instead of the first dragon rewards. Happened when running a game with both host and cooperator being fresh characters. I don't know if this one is related, but thought I'd toss it in if it helps diagnose at all. 

It appears to be mostly caused due to retriggers where they shouldn't be for some reason in combination with NPC state desync. 

I think it might be something to do with how and what of the gamestate is initially shared (or really replicated) to the cooperator(s) when a player joins a party. 

**This is a wild ask, but is there any way we could get an item to resync worldstates with the host (assuming that initial state is the problem instead of the issues happening when quest progressing)?**  I know this might be an annoying thing to implement as you'd have to kind of drill down what of the gamestate data to force an update for. This would provide an opening to implement solutions for (as example) people who are using characters who are in trapped (no-teleport) states don't get locked into those states in another player's games because they can sync with the host. Maybe also make an option with the item to set your character's single-player worldstate to that of the host as well (just for convenience if the host is technically from an earlier state than where your character is and you want to be able to keep going from back where you and friends left off... that's just a random extra thought though). I have a degree in CS and have dug around in Elden Ring a bit, but I have no idea if  any of what I've recommended is even viable. Just thought I'd just put AN option out there, even if not terribly well researched. 

That being said. This mod still kicks absolute ass, and has made Elden Ring feel more like a good D&D session for me and friends. Keep up the good work. I'll toss another ko-fi when I get a chance :)

Cheers!

### Steps to recreate the bug

NPC state regression for the round table hold happens intermittently, usually coincides with where an update to the round table hold characters would normally happen. Sometimes works properly, and then will change states incorrectly upon re-entering the hold (tested expressly using only ONE player as host to rule out variables, and without making progress separately from the host... I really wanted to nail this one down.). Mostly happens where the spirit tuner and rememberance crone are reset to much earlier character states.

Gurranq progress issue/lack of rewards has happened on sopme character playthrough with a set of cooperators, but not with all.  Not 100% sure where this one stems from, just that if it gets stuck in this state, you will either miss a reward, or get no further rewards if it's the 4th deathroot where Gurranq would normally enrage (to my testing).

### Version

1.4.3 (Latest)

**Comment by cjbottaro** [comment]
> I tried fixing it by having both me and my friend progress the roundtable characters while separately playing solo

Dang, that is literally the last thing we tried before signing off our last session. I had super high hopes that would be a viable workaround... :(

**Comment by Aerron03** [comment]
In my experience with my partner this seems to be an issue with "sanctuary" areas in general. Desync has occurred in our games in both the Round Table and Volcano Manor. As alluded to by others, progressing in our individuals games and then rejoining does not resolve the issue for us either. These are the only areas in the game we've encounter thus far that seem to be irreparably broken with regard to co op progression.

**Comment by minutemaen** [comment]
+1 to this
2 players in total, 1 on PC and another on the steam deck.

- Gurranq progress issue/lack of rewards
Happens to joining player, keeps receiving the seal 

- Greyoll will just randomly die sometimes     
For us it was before killing any dragons, after activating the trapped chest in dragonburnt ruins

Irina quest desynced for joining player as well.
