### ISSUE TITLE
[Bug]: hard stuck melina teleport to roundtable hold

### ISSUE THREAD

**Issue by Ezpurr** [LukeYui/EldenRingSeamlessCoopRelease#51]
### Discord Username

jopphannes#8732

### Describe the issue in detail

I played with one friend when i got invited to roundtable hold, when in loading screen my game crashed and now i am stuck in loading screen forever. i have video. i've tried everything from verifying game files and everything but if i unistall my charakter is gone right?

### Steps to recreate the bug

i dont know my game crashed in loading screen and now im stuck

### Version

1.2.0 (Latest)

**Comment by Ezpurr** [comment]
does my character disappear is if i delete the game?

**Comment by Barophobia** [comment]
> does my character disappear is if i delete the game?

You can backup your save from - C:\Users\USERNAME\AppData\Roaming\EldenRing\ 

It is the .co2 file inside the folder

**Comment by LukeYui** [comment]
Hi, thanks for the report.

I'll look into it, though I can't recreate the bug. Can you please share the video?

**Comment by Ezpurr** [comment]
https://user-images.githubusercontent.com/107214235/173196476-e997a20f-2a08-463c-a97e-82849de91643.mp4

its like that forever

**Comment by Yoni0040** [comment]
hi it happened to a friend of mine and i can recreate it for you.
so it's a known bug that melina will bother you only once everytime you join a seesion.
so basically if you join a seesion and the first site of grace you rest at is at the roundtable melina will trouble you telling to go to the roundtable hold while you're still there causing you to get stuck - he wasn't the host
i also wasn't the host and i did rest at a grace before arriving to the roundtable hold and when i rested (melina didn't bother me) i didn't get stuck so i assume it has something to do with her.

**Comment by Yarvino** [comment]
I have this issue as well.  and also now every time I connect to my hosts game melina makes me go through the whole speech of her wanting me to goto round table hold.  also now that we have gotten past the city boss morgott I get to hear each time I rest at a grace that i need to go find the haligtree lift.

**Comment by tristan-k** [comment]
+1
