### ISSUE TITLE
[Bug]: Undefined patch failure

### ISSUE THREAD

**Issue by essasquared** [LukeYui/EldenRingSeamlessCoopRelease#512]
### Discord Username

essasquared#6969

### Describe the issue in detail

I tried to verify my game files and then re-installed seamless coop but now I keep getting an error when I launch it. "Undefined Patch Error". If I ignore it, I can still enter the game, but the modded coop items turn invisible and don't function properly.

### Steps to recreate the bug

Verify game files and try to launch seamless coop

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
Are you sure that you're using 1.4.3? A patch failure means that your exe isn't what the mod is expecting. This either means that your mod or Elden Ring version is out of date.
