### ISSUE TITLE
[Bug]: Stuck in Ranni's Rise after completing Ranni's questline on Friends world

### ISSUE THREAD

**Issue by hunternsb** [LukeYui/EldenRingSeamlessCoopRelease#514]
### Discord Username

hunternsb#4267

### Describe the issue in detail

I have been playing thru with 2 other friends and we have been interchangeably summoning to each others world for bosses, drops, new sights of grace, etc. We did the Ranni's Questline (I joined my friends world for that playthru that night) and now have beaten the game (in a friends world) and when I came back to Ranni's Rise, I got stuck behind the fog wall (when Blaidd wants to fight you/when you need to talk to the three spirits of Ranni's aids) but Blaidd never agro's me, and I can't teleport out. 

I went to my friends world, killed Blaidd and picked up Iji's bell bearing and came back to my world to find Blaidd gone (which is fine), but I still am unable to teleport away from Ranni's rise or leave because of the fog wall. Iji's spirit is still just stuck in the main level of her Rise and is stuck saying the same voiceline over and over. 

### Steps to recreate the bug

1. Start Ranni's questline while summoned to a friend world (All in Ranni's rise progressing her dialogue)
2. Have a friend talk to her three spirit friends and then exhaust her dialogue so they can then leave the rise. 
3. This may make you leave their world and rejoin if you are not able to talk to the spirits properly since they are.
4. Playthru and complete the Ranni questline to Kill the bad Blaidd summon in Soifra and then finish giving Ranni the ring for the Dark moon greatsword and to end her questline.
5. Return to Ranni's rise in **your world** and go to face Blaidd who is on the front stairs.
6. He should now be bugged and not let you lock onto him and you also can't teleport out.

### Version

1.4.3 (Latest)

**Comment by a0686613** [comment]
The same happened to me when I host the game. I was doing the Rogier questline with Ranni, but my friends didn't. If they talk with Ranni, instead of having an additional Rogier choice, they would continue the quest as normal.But I can only see 2 spirits and my Ranni stuck saying the Rogier voiceline ( ask me to leave), which means I can't teleport or leave the tower.
