### ISSUE TITLE
[Bug]: no roundtable site of grace

### ISSUE THREAD

**Issue by pagey1991** [LukeYui/EldenRingSeamlessCoopRelease#518]
### Describe the issue in detail

since the start of the game I haven't been able to see a site of grace on map for the roundtable hold, i have to join into my friends game while he is in the roundtable for me to access it, have rested there when in but doesn't show in my map in my game, now progressed 3/4 way through game having to do this,

anyone had this and got a fix?

### Steps to recreate the bug

start my own game and it doesn't appear in bottom right of map

### Version

1.4.3 (Latest)

**Comment by Shadow0fd3ath24** [comment]
you have to talk to Melina when you rest at a site of grace, after like the 3rd time she will open an option to let you go to roundtable hold. It can only be accessed this way for the first time. For me i had the option there for almost 10 hours of gameplay not knowing what it was
