### ISSUE TITLE
[Bug]: Increased desync in 1.2.0

### ISSUE THREAD

**Issue by TheNitroExpress** [LukeYui/EldenRingSeamlessCoopRelease#52]
### Describe the issue in detail

I apologize if this was fixed in 1.2.1, but me and my coop partner are experiencing desync in 1.2.0 and not 1.1.0.

The volcano cave beastmen (Specifically the little ones) are in different places for each of us.

The Atlas cave soldiers are all over the place for both of us. 

We reverted to 1.1.0 in the meantime.

Thanks for all the work you put in to this mod!

### Steps to recreate the bug

Install 1.2.0

Play enough that both players will rest at grace. 

Edit: In both cases at least one player had died before the desync occured.

Try to fight with groups mentioned and relay results to partner.

### Version

1.2.0 (Latest)

**Comment by JustAnOkapi** [comment]
Especially in 1.2.1
1.2.1 makes it even worse

**Comment by loki2236** [comment]
Another one

User: Epoq#0125
Version: Older ones.
User says he had desync issues happening a lot of times after activating lifts.

https://discord.com/channels/979042878091329587/984615336454266911

**Comment by LukeYui** [comment]
> Especially in 1.2.1 1.2.1 makes it even worse

1.2.1 for sure didn't change anything related to the networking. The fact that it seemed to get worse for you is a coincidence.

I cannot recreate this bug.

**Comment by ari0824** [comment]
A friend and I have been experiencing desynch issues since 1.1.0. For us it doesn't always happen on lifts, mostly when we're just roaming. But I did record an instance where this occurred on a lift + an instance where Melina give her intro convo again. [clip](https://youtu.be/WH8DSsPljCk)
