### ISSUE TITLE
[Bug]: Chariots glitch out with multiple hosts.

### ISSUE THREAD

**Issue by Strett0** [LukeYui/EldenRingSeamlessCoopRelease#521]
### Discord Username

Strett0#0134

### Describe the issue in detail

We were exploring Gelmir Hero's Grave when the chariots began to glitch out. It was as if they did not know which way to go. I think the issue may be that the chariot tries to kill the host, buts with multiple hosts, which one is right? After the main host died, the chariot de synced and it was in a different spot  for all of us, acting irrationally.

### Steps to recreate the bug

go to gelmir heros grave in coop, the the main host die by the chariot. watch its behavior when players are in different parts of the map.

### Version

1.4.3 (Latest)

**Comment by Crosline** [comment]
We noticed this behaviour too.

**Comment by LukeYui** [comment]
Fixed in 1.5.0
