### ISSUE TITLE
[Bug]: Bloody Finger Hunter Yura

### ISSUE THREAD

**Issue by Voigash** [LukeYui/EldenRingSeamlessCoopRelease#525]
### Describe the issue in detail

While playing coop you're unable to see Yura if you're the one joining a world. if you are the host, you can see her. but you can't start the questline.

### Steps to recreate the bug

Enter coop, go to yura's location. try to find, talk to or start the questline.

### Version

1.4.3 (Latest)

**Comment by achyutde13** [comment]
I had the opposite, I was the host and I couldn't see Yura, but my friend who joined me could see him.
