### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FlippingCacti** [LukeYui/EldenRingSeamlessCoopRelease#528]
### Discord Username

Flipping_Cacti#1671

### Describe the issue in detail

The cooppassword notepad isn't in the SeamlessCoop folder. I've checked and my friends who have the same 1.4.3 update as me have it and I don't. I've tried re-downloading. My game won't even open. It says Failed to find "eldenring.exe"
Press any key to continue . . . and then it closes.

### Steps to recreate the bug

I don't know how to. Nor do I know how to fix it.

### Version

1.4.3 (Latest)

### Relevant Crash log

```shell
Failed to find "eldenring.exe"
Press any key to continue . . .
```

**Comment by LukeYui** [comment]
It's not called cooppassword. It's called "seamlesscoopsettings.ini". You're either using a really old version or not installing it correctly. Please let me know your EldenRing/Game file structure.
