### ISSUE TITLE
[Bug]: Game perma breaks at Ranni's Rise if not everyone talks to the NPCs

### ISSUE THREAD

**Issue by iAzarae** [LukeYui/EldenRingSeamlessCoopRelease#529]
### Discord Username

Azarae#1487

### Describe the issue in detail

This is a bug that seems to happen in single player as well. Three of us got to Ranni's Rise and needed to talk to Iji and Blaid, but one of us left. The other two are now stuck within the fog wall, and cannot teleport or progress. The NPCs are no longer present, and trying to talk to Ranni only brings up the "..." response. There is no getting out of this manually.

We thought that progressing Ranni's questline with someone else would work (the person who left initially and broke everything), and while we were free *in their world*, seperating just teleports us back behind the fog walls, and removes teleporting.

By chance, is there any way to split from a host WITHOUT going back to where you teleported from, and avoid going back into your previous world state? If this is a possibility, then this bug can be resolved. Otherwise, only one of us is applicable as the host, as the other two can't go anywhere.

### Steps to recreate the bug

-Have three people
-Go to Ranni and talk to her to the point where you have to talk to all three NPCs.
-Have someone leave in the middle of talking to the three NPCs.
-The players who didn't leave are now stuck. the third person can still progress their mission normally, and will be able to "re-open" their world to them.
-The other two players can join the third to once again be free and have teleportation open, but upon returning to their own world, are once again stuck.

### Version

1.4.3 (Latest)

**Comment by Ghostdragon1234** [comment]
i have a similar glitch have a bug with rani's rise not allowing me to leave after handing Rani the finger slayer blade after rani disappears. no consumables or teleportation items are be abled to use my friends where fine until my friend hosted and we teleported to rani's rise and they have the issue now  friend number 3 doesn't have the issue probably  because they talked to Rani first.
