### ISSUE TITLE
[Bug]: Mass bug report

### ISSUE THREAD

**Issue by OrginalSh4dow** [LukeYui/EldenRingSeamlessCoopRelease#530]
### Describe the issue in detail

The teleporting function is really bad and sometimes you need to teleport vote twice to actually teleport. The Horse is also not working very well, sometimes it can't be summoned by one of the players. Another problem is that the other players (not the host) will first be spawned invincible at the position he died and then be spawned normally.

### Steps to recreate the bug

Vote for teleport if successful it will say already voted for teleport or something like that. After that it works

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
All duplicates.
