### ISSUE TITLE
[Bug]: LOCKON BUG

### ISSUE THREAD

**Issue by JGMetal17** [LukeYui/EldenRingSeamlessCoopRelease#532]
### Discord Username

THUNDERxKNUCKLES#4525

### Describe the issue in detail

During a boss fight the lock on disables and will not come back. It makes fighting bosses like the star beast literally impossible. it is mainly on horseback. Switching the auto lock and other things in the settings does not fix it. Please help! Thank you!

### Steps to recreate the bug

Go to any boss on horseback. Lock on and wait. It will flip your camera around and you wont be able to lock on.

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
Should be fixed. Feel free to post again if it's still causing problems

**Comment by JGMetal17** [comment]
Sweet thanks man that was quick I really appreciate that. Having a lot of fun with the mod of course. Also question do I need to update it some way or like re download the mod? Sent from my iPhoneOn Feb 20, 2023, at 2:48 PM, LukeYui ***@***.***> wrote:﻿
Should be fixed. Feel free to post again if it's still causing problems
