### ISSUE TITLE
my elden coop crashed 

### ISSUE THREAD

**Issue by unknown303859** [LukeYui/EldenRingSeamlessCoopRelease#533]
### Discord Username

unknown303859#9842

### Describe the issue in detail

I had followed the instructions on youtube but the thing is my elden coop crashed right after i get into the game.

I can't seem to fathom what factor makes it like this, and also I even reinstall 3 times and redo all the same things but the problem keeps goes on

### Steps to recreate the bug

just do the steps on the youtube but it crashes when you open the game

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
What video on YouTube?

**Comment by unknown303859** [comment]
https://www.youtube.com/watch?v=VoWiwUNLsj4

**Comment by nopjmp** [comment]
Friend crash was fixed disabling the Discord Overlay if you are using that or steam overlay.
