### ISSUE TITLE
[Bug]: Game Crash when shooting bow in 1.4.4

### ISSUE THREAD

**Issue by mkin701** [LukeYui/EldenRingSeamlessCoopRelease#534]
### Describe the issue in detail

Using a pulley bow or a long bow in v1.4.4 of the Mod causes the game to crash instantly. Had no issues until updating to the latest.

### Steps to recreate the bug

1. Equip bow.
2. Shoot bow.
3. Game crash.

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
Fixed in 1.4.5
