### ISSUE TITLE
[Bug]: Game Crashes when using a spell. 1.4.4

### ISSUE THREAD

**Issue by tjascension** [LukeYui/EldenRingSeamlessCoopRelease#536]
### Describe the issue in detail

The game immediately crashes when using either a spell or using a special move with my Moon Blade Kitana

### Steps to recreate the bug

1. go to inventory
2. equip wand 
3. leave inventory
4. cast spell

or

1. go to inventory
2. equip Moon Blade Katana 
3. leave inventory
4. use special ability

### Version

1.4.3 (Latest)

**Comment by LukeYui** [comment]
Fixed in 1.4.5
