### ISSUE TITLE
[Bug]: Unable to enter Fias- Deathbed dream while in a party

### ISSUE THREAD

**Issue by Deltorean** [LukeYui/EldenRingSeamlessCoopRelease#539]
### Discord Username

Deltorean¤7705

### Describe the issue in detail

While in a party, I can interact with Fia while shes sleeping, but nothing happens and my character just gets back up instead of entering the Fortissax boss fight. We tried to play around this and join mid fight, but not everyone was able to join and instead timed out on join timer. 

### Steps to recreate the bug

while in a party, interact with Sleeping Fia.

### Version

1.4.3

**Comment by DemiMort** [comment]
I just did the boss fight in coop and it worked. 
In cases fia is not there all players should go back in solo and talk to her and D if they are in the roundtable hold.

I guess you need to update the mod to 1.4.5 to fix your problem.
