### ISSUE TITLE
[Bug]: Bosses get health back when a cooperator dies

### ISSUE THREAD

**Issue by BosForPresident** [LukeYui/EldenRingSeamlessCoopRelease#54]
### Discord Username

BosForPresident#9853

### Describe the issue in detail

I was beating Margit with a friend and we summoned rogier the cooperator. When he died Margit got a part of his health back.

### Steps to recreate the bug

Go to Margit, the fell omen, fight. Summon Rogier. Let Rogier die.

### Version

1.2.0

**Comment by LukeYui** [comment]
Hi, thanks for the report. This isn't actually a bug - the boss just has his max health adjusted as the amount of co-operators has changed. 

In reality what's happening is the boss's maximum health is getting much lower, which makes it appear as if they're restoring health.
