### ISSUE TITLE
[Bug]: Crashing upon skill

### ISSUE THREAD

**Issue by Mattbiozoo** [LukeYui/EldenRingSeamlessCoopRelease#540]
### Discord Username

MattBioZoo#2999

### Describe the issue in detail

Joined up with several of my friends but since the new update everytime we use a bow or use any of the spells or ashes of war the game crashes and closes

### Steps to recreate the bug

Use a spell, ashes of war or use bow

### Version

1.4.5 (Latest)

**Comment by LukeYui** [comment]
Update to 1.4.5
