### ISSUE TITLE
[Bug]: Goldmask quest ending seems impossible.

### ISSUE THREAD

**Issue by GrandW1zardX** [LukeYui/EldenRingSeamlessCoopRelease#541]
### Describe the issue in detail

Problem seems to be that the game fails to update the variables in Capital of ash, such as Gideons moveset not changing when you have defeated Malenia or Mogh or Goldmask not appearing when he is supposed to. 
Gideons moveset not changing isnt really a big issues, because he is a pushover anyway, but unfortunately this prevents the player from getting the Goldmask ending. Strangely enough, Upon completing Nepheli Loux's quest or enheriting the frenzied flame does still trigger the player being able to summon either Nepheli or Shabriri during Godfrey's fight. 

### Steps to recreate the bug

Step 1: do every step in Goldmask quest
Step 2: make your way to Maliketh the Black Blade
Step 3: beat Maliketh whilst all players are alive (this prevents the bug where capital of ash sites of grace fail to update, allowing the spectating players to warp to Leyndell after triggering Capital of Ash.) 
Step 4: go to the place Goldmask is supposed to be found, and find an empty spot instead

### Version

1.4.5 (Latest)

**Comment by toromihearts01** [comment]
Can confirm, my co-op partner and I went through the entire quest only to be met with neither Corhyn or Goldmask anywhere to be found. Pretty disappointing.
