### ISSUE TITLE
Magic crashes my game.

### ISSUE THREAD

**Issue by Jonathon856** [LukeYui/EldenRingSeamlessCoopRelease#544]
### Discord Username

StrangeSpaceman#7387

### Describe the issue in detail

Whenever I use ranged magic like glitstone pebble specifically outside of combat, my entire game suddenly crashes. I have not been able to try any other magics, because I only just started my first game with this mod.

### Steps to recreate the bug

Having any staff and using a ranged, bullet-like spell outside of combat.

### Version

1.4.5 (Latest)

**Comment by LukeYui** [comment]
You're on 1.4.4, update to 1.4.5.
