### ISSUE TITLE
[please check]:please make for cracked one from steam unlock

### ISSUE THREAD

**Issue by heroes5062** [LukeYui/EldenRingSeamlessCoopRelease#548]
### Discord Username

Heroes5062#0012

### Describe the issue in detail

please make this for cracked one from steam unlock, please 

### Steps to recreate the bug

I really want to play with friends 

### Version

1.4.5 (Latest)

**Comment by jbtrystram** [comment]
From the mod FAQ : 
> Q) Does this worked for cracked/pirated games?
> A) No, I'm also not going to be supporting these versions so please don't make bug reports about it

If you like the game, you should buy it to support the devs :)

**Comment by heroes5062** [comment]
If I had the money wouldn't I bought it and not only that we all need to
buy it.

**Comment by LukeYui** [comment]
No
