### ISSUE TITLE
[Bug]: Death as client prevents resummoning horse on respawn, client randomly getting "foe killed" and runes from it

### ISSUE THREAD

**Issue by james5272** [LukeYui/EldenRingSeamlessCoopRelease#550]
### Describe the issue in detail

When fighting a boss (maybe only when on horse), if client dies when they respawn they are unable to resummon their horse until the host closes and reopens the session, and then the client reconnects.

Also client, and only client, sometimes gets "foe killed" message when using or respawning at a grace, which can give several levels worth of runes.  Not sure if this is a bug with the mod or if the main game has this too.

### Steps to recreate the bug

1. As client, die while mounted on horse.

2. For "foe felled" messages, have no idea what's triggering it, and it doesn't always happen, seems random.

### Version

1.4.5 (Latest)

**Comment by H4wK32** [comment]
I can reproduce it.

**Comment by NeosGhost** [comment]
i've gotten this a few times after 1.45 update as well

**Comment by dragossusi** [comment]
I reproduced it while fighting Radahn.

**Comment by cynicalsybill** [comment]
I've reproduced this multiple times at this point, with the solution being consistent - host needs to withdraw from their world, then re-open a session and client can rejoin.

**Comment by LukeYui** [comment]
Fixed in upcoming 1.5.0
