### ISSUE TITLE
[Bug]: Murkwater Catacombs crash

### ISSUE THREAD

**Issue by Konfiskert** [LukeYui/EldenRingSeamlessCoopRelease#551]
### Discord Username

Konfiskert Popkorn#5944

### Describe the issue in detail

Me and a friend (He was the host) entered Murkwater Catacombs, we fought our way to the boss room, and right before the room there's some stairs. When he walked to the top of those stairs, his game crashed instantly. We tried restarting and going back, and the same happened, but this time his game stopped working, possibly due to his character being placed at the top of the stairs. The first time his character started in the hallway before the stairs, so the crash didn't happen when he opened the game.

### Steps to recreate the bug

Go to Murkwater Catacombs in coop (2 players). Open the door to the boss room, and walk through the door. When you get to the stairs the game crash.

### Version

1.4.5 (Latest)

**Comment by LukeYui** [comment]
Did you verify your game files with Steam?
