### ISSUE TITLE
[Bug]: Unable to connect to the SDR

### ISSUE THREAD

**Issue by jerryjealously** [LukeYui/EldenRingSeamlessCoopRelease#554]
### Describe the issue in detail

Like in Title. I cannot join or host a game. I tried to start everything as admin but no changes

### Steps to recreate the bug

Don´t know how to recreate it. My friend´s Version seems to be just fine.

### Version

1.4.5 (Latest)

### Relevant Crash log

```shell
Protokollname: Application
Quelle:        Application Error
Datum:         07.03.2023 01:33:13
Ereignis-ID:   1000
Aufgabenkategorie:(100)
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:      DESKTOP-9CGQ02F
Beschreibung:
Name der fehlerhaften Anwendung: eldenring.exe, Version: 1.8.1.0, Zeitstempel: 0x6396cee8
Name des fehlerhaften Moduls: elden_ring_seamless_coop.dll, Version: 0.0.0.0, Zeitstempel: 0x63f3d352
Ausnahmecode: 0xc0000409
Fehleroffset: 0x000000000010980d
ID des fehlerhaften Prozesses: 0x3f20
Startzeit der fehlerhaften Anwendung: 0x01d9508c66eeb2e5
Pfad der fehlerhaften Anwendung: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Pfad des fehlerhaften Moduls: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\SeamlessCoop\elden_ring_seamless_coop.dll
Berichtskennung: 953c8eaa-fde9-482b-a127-bcbab637f06e
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
Ereignis-XML:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-03-07T00:33:13.9365978Z" />
    <EventRecordID>37200817</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-9CGQ02F</Computer>
    <Security />
  </System>
  <EventData>
    <Data>eldenring.exe</Data>
    <Data>1.8.1.0</Data>
    <Data>6396cee8</Data>
    <Data>elden_ring_seamless_coop.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>63f3d352</Data>
    <Data>c0000409</Data>
    <Data>000000000010980d</Data>
    <Data>3f20</Data>
    <Data>01d9508c66eeb2e5</Data>
    <Data>D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe</Data>
    <Data>D:\SteamLibrary\steamapps\common\ELDEN RING\Game\SeamlessCoop\elden_ring_seamless_coop.dll</Data>
    <Data>953c8eaa-fde9-482b-a127-bcbab637f06e</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by Nickontree13** [comment]
same here i dont know what to do

**Comment by Nickontree13** [comment]
yooo broo i got solution all u need to do is that your friend needs to copy all files except main files i mean all dll and this type of files and ur friend needs to uploud it on google drive then u copy all of that and BOOOM

**Comment by jerryjealously** [comment]
> yooo broo i got solution all u need to do is that your friend needs to copy all files except main files i mean all dll and this type of files and ur friend needs to uploud it on google drive then u copy all of that and BOOOM

Thanks for the reply, still doesn´t work for me. Same issue.

**Comment by okexi** [comment]
it seems you can't connect to steam network. Steam Datagram Relay (SDR) is Valve's virtual private gaming network. Maybe you can try a onlinegame accerlator. and if you want know more about SDR. there [https://partner.steamgames.com/doc/features/multiplayer/steamdatagramrelay](url)

**Comment by jerryjealously** [comment]
> it seems you can't connect to steam network. Steam Datagram Relay (SDR) is Valve's virtual private gaming network. Maybe you can try a onlinegame accerlator. and if you want know more about SDR. there [https://partner.steamgames.com/doc/features/multiplayer/steamdatagramrelay](url)

link is broken. and i dont really know what you mean by "onlinegame accelerator". do you mean a VPN? im afraid thats the whole issue actually. by checking "https://whatismyipaddress.com" i came across the weird and long ip from a IPv6 connection. since steam (and everyone else) dont really like doing stuff with IPv6 i gotta wait for my PtP configuration and try again i guess. maybe thats the reason why i cant connect to steam when i log in, sometimes.
