### ISSUE TITLE
[Bug]: Astrologer Class Crash

### ISSUE THREAD

**Issue by Fragool** [LukeYui/EldenRingSeamlessCoopRelease#555]
### Discord Username

Fragool#7731

### Describe the issue in detail

Hello,

Just installed to play with a friend. Decided on a mage build this time around since there are no PvP invaders, no need for the strength build... However, every time I select an Astrologer class to start with, my game crashes. 
I proceeded to re-open the game, new game, select a new class(vagabond) scroll through the class list, and THE SECOND I even hover over Astrologer, my client crashes. Even just simply hovering over the option, I didnt even click it yet.(crash)

Note: when you have the large screen where it shows "Model A & B" for the classes available, it will not crash. Its until you select astrologer from that screen^. Or, if u select a different class and try to switch it to Astrologer. I settled on Prisoner :(

### Steps to recreate the bug

New game/Class Select/ Astrologer/Crash
OR!?
New game/Class select/ Anything but Astrologer/ Select "Origin"/ Pick Astrologer/ Crash. 

### Version

1.4.5 (Latest)

### Relevant Crash log

```shell
1: "Successfully scheduled Software Protection service for re-start at 2123-02-12T02:20:50Z. Reason: RulesEngine.

2: "Offline downlevel migration succeeded."

I've tried selecting astrologer many times. I only get small variations of these 2 kinds of reports above^^^
```

**Comment by LukeYui** [comment]
Not a bug with the mod. Try verifying your game files with Steam.
