### ISSUE TITLE
not syncing prayerbook and dialogue

### ISSUE THREAD

**Issue by Loucantcode** [LukeYui/EldenRingSeamlessCoopRelease#556]
### Describe the issue in detail

i looted a prayerbook in a friends world and after the game disconnected me, wich randomly happens every few hours, i gave it to the dude in my own game at the roundtablehold. after i reconnected to his world, i couldnt get the spells from his npc, and neither could i when going back to my own world. the prayerbook is essentially lost now. 
Maybe i dont understand how it works but i thought the quest and dialogue is saved on my char and it would be sync in my and his world. I didnt look if i could loot it again in my singleplayer but the only way to get the spells now is him buying them and dropping them for me. 
Also at the roundtablehold everytime i talk to someone in my friends world, the dialogue is as if i talk to them for the first time. this is especially tricky for the girl wich ups the spirits and the dude that gives info about gurrang

anyway besides this i absolutely love the mod. thanks a lot for taking the time to work on it. 

### Steps to recreate the bug

everytime we are at roundtablehold my dialogue options reset to the first time dialogue. also the scroll i gave to the faith teacher in my singleplayer doestn come to my freinds world. 

### Version

1.4.5 (Latest)

**Comment by StoveN64** [comment]
This is the exact thing happening to me. The mod is flawless, but my friend and I are afraid to go forward if the player that is The Wanderer wont have their NPC questlines progress or save
