### ISSUE TITLE
[Bug]: host death reset boss encounters 

### ISSUE THREAD

**Issue by QTMcWhiskers** [LukeYui/EldenRingSeamlessCoopRelease#557]
### Describe the issue in detail

I was fighting the rotten erdtree avatar in Caelid near the Smoldering church with two friends (I hosted).  When boss killed me, instead of going into spectator mode, I was given the option to respawn at a grace or stake, and the world - including the field boss - reset.

For different reasons (one of my friends could not summon Torrent) we closed out the game and rejoined, but even after killing the erdtree avatar, the same issue with host death resetting the game happened with the magma wyrm

### Steps to recreate the bug

With a host and two wanderers, complete the opening steps of Milicent’s quest (fix needle, give needle), then run from the plague church to the smoldering church.
Fight your way down to the erdtree avatar and have the host die

### Version

1.4.5 (Latest)

**Comment by greenleafz** [comment]
I have also had a very similar issue, in the same place
