### ISSUE TITLE
[Bug]: Getting runes/rewards for bosses everytime the player sits on a grace.

### ISSUE THREAD

**Issue by loki2236** [LukeYui/EldenRingSeamlessCoopRelease#56]
### Discord Username

Crow#9190

### Describe the issue in detail

Sometimes when people join a world, everyone but the host is spammed with GREAT ENEMY FELLED and gets rewarded EACH time they rest with the runes awarded when a boss died. Two friends of mine got like 60k runes this way just standing around before I had to send them back.
3 people total. I was the host, and the two who joined me got the bonus runes. 

After I sent them home, I joined one of their worlds and the same thing happened to me. 1 rest = 1 'boss kill' and rune reward

### Steps to recreate the bug

*Not personally Tested:
After killing a boss, fast travel to any grace using the map, and make the host rest in the grace WHILE the other person is still loading, that should consistently trigger the bug

### Version

1.2.1 (Latest)

**Comment by Nordgaren** [comment]
7wisted#5397 - 

when my friends try to rejoin when they desync sometimes, they get a "Boss Felled" notification and a bunch of runes even though we haven't killed any boss. sometimes this repeats everytime they rest at a grace, meaning infinite runes.

I was this host in my case too, there was an additional issue probably wasn't caught in the other report, where resting at a grace kept granting runes

**Comment by SirDifferential** [comment]
We also experienced this yesterday. As addition to what's already listed, the guest players also lost access to the level up menu until they went back to main menu and rejoined the host. We had this happen when killing the first tree sentinel immediately out from the tutorial area in Limgrave.

**Comment by EvlAnimlCracker** [comment]
My friend and I beat the red wolf in Raya; the next day when we met back up it started happening.  I have a 2 min vid while we grace hopped trying to figure it out before we just reset.  The vid I was able to upload here happened later after we beat a Night's Calvery.  We fought, won and went to the grace and it started happening.  No idea what triggered it.

[Uploading ELDEN RING 2022-06-19 12-38-07.zip…]()

**Comment by clara-a-correia** [comment]
Even with the most recent update this keeps on happening. Me and my co-op partner still haven't figured out what triggers it - host doesn't do anything before opening the world and co-op partner joining in, same with co-op partner joining in before doing anything in their world.

**Comment by LukeYui** [comment]
This hasn't been fixed yet, it's a known issue

**Comment by Labowskyy** [comment]
Not sure what causes this issue but these are the things that happened when I experienced it both times:
- Cannot level up.
- Talk to Melina is an option but she just appears and disappears. 
- Killing things then resting seems to fix it, reloading the world does not.
