### ISSUE TITLE
[Bug]: friend can’t summon horse anymore 

### ISSUE THREAD

**Issue by Rrennegade** [LukeYui/EldenRingSeamlessCoopRelease#563]
### Discord Username

Rrenegade#7623

### Describe the issue in detail

My friend and I were both able to use our horses until a tree sentenial killed her . Now when she summons her horse it pops up for a second and then disappears. She can’t use / ride her horse anymore . 

### Steps to recreate the bug

We had 2 people . She died on her horse after I had already died . I was in the middle of talking to the witch ranni and she respawned with the tree sentinel still locked on. I went to the site of grace to reset the area and then afterwards she couldn’t summon her horse . My horse is fine but for her it’s still completely glitched out so all she sees is me riding air . I have it on video if you need it . 

### Version

Select version

**Comment by cjbottaro** [comment]
Same thing happened to us after we fought the ulcerated tree spirit in Caelid. The only thing that fixed it was using separation mist and then me rejoining the game.

**Comment by Rrennegade** [comment]
> Same thing happened to us after we fought the ulcerated tree spirit in Caelid. The only thing that fixed it was using separation mist and then me rejoining the game.

We tried . It won’t work :(

**Comment by Eamead** [comment]
Try specifically: Separation mist -> have friend summon Horse in Solo and ride it around for a moment - > Rejoin. Its the summoning in your own world that seems to make it work.
