### ISSUE TITLE
[Bug]: Game crashes when sitting at site of grace with summons

### ISSUE THREAD

**Issue by CosmicRey** [LukeYui/EldenRingSeamlessCoopRelease#565]
### Discord Username

CosmicRey#1663

### Describe the issue in detail

We kept experiencing crashes, and were able to isolate it down to having summons up when sitting at a site of grace. We are able to get a very consistent repro with this. Not sure if its more than one summon or not (we were using wolves)

I do have a crash dump I can share as well.

### Steps to recreate the bug

* Summon creatures (e.g. wolves)
* One of the players sits at site of grace
* Witness game crash

### Version

1.4.5 (Latest)

**Comment by LukeYui** [comment]
Hi, can you share the crash log?

**Comment by CosmicRey** [comment]
Hey there was no crash log associated with it that I could find, but this crash dump is from it
[6d881b5b-f39e-41f9-b5d1-7681120fa78b.zip](https://github.com/LukeYui/EldenRingSeamlessCoopRelease/files/11021348/6d881b5b-f39e-41f9-b5d1-7681120fa78b.zip)
