### ISSUE TITLE
[Bug]: Weapon art lock

### ISSUE THREAD

**Issue by Feldwin1211** [LukeYui/EldenRingSeamlessCoopRelease#569]
### Discord Username

TheLegendsEnder #5174

### Describe the issue in detail

I cant change my ash of war from the one that launches you in the air and you slam your weapon down instead of the selected one for the weapon.

### Steps to recreate the bug

I don't know how to recreate it I just started as a astrologer and it was stuck no matter what weapon i used or what ash of war i used.

### Version

1.4.5 (Latest)

**Comment by LukeYui** [comment]
Hi. The mod does not affect ash of war.
