### ISSUE TITLE
[Bug]: Maliketh dissapears after wiping the party

### ISSUE THREAD

**Issue by loki2236** [LukeYui/EldenRingSeamlessCoopRelease#57]
### Discord Username

DsyncXO#9305

### Describe the issue in detail

Maliketh seems to cause an issue for me and in co-op, after the first time wiping, as soon as my friend joins or spawn we get the cutscene for the second phase, but the boss is not even there and we never enter the room

https://streamable.com/xc0s89

So to fix, must go into seperate world, enter the room from the grace, then quit out
but it will happen every death/wipe

https://discord.com/channels/979042878091329587/984560114751123506

### Steps to recreate the bug

Go fight Maliketh
Get wiped
(cutscene plays)
Spawn again after the cutscene in the arena, boss hp bar still there, but there's no boss.

### Version

1.2.0

**Comment by kadejentink** [comment]
This occurs in 1.2.4 as well. 

In a situation with two players (host and cooperator):
-Fight Maliketh
-Reach phase 2
-Party wipe
-phase 2 cutscene plays again for cooperator
-cooperator is disconnected during cutscene
