### ISSUE TITLE
[Bug]: Unable to craft in another players world

### ISSUE THREAD

**Issue by ItsZman2006** [LukeYui/EldenRingSeamlessCoopRelease#571]
### Describe the issue in detail

Was in another players world and noticed that even when I'm not in conflict I cannot use the crafting menu. Even with the crafting kit. 

### Steps to recreate the bug

Go into another players world and try to use the crafting menu.

### Version

1.5.0 (Latest)

### Relevant Crash log

```shell
No crashes just not able to use crafting menu
```

**Comment by LukeYui** [comment]
Will be fixed in 1.5.2

**Comment by ItsZman2006** [comment]
> Will be fixed in 1.5.2

Awesome! thank you so much!
