### ISSUE TITLE
[Bug]: Horse still unresponsive after dying as a client

### ISSUE THREAD

**Issue by radaelilucca** [LukeYui/EldenRingSeamlessCoopRelease#573]
### Discord Username

Lucca#4554

### Describe the issue in detail

Whenever the horse dies it becomes unresponsive and I have to rejoin the session.

### Steps to recreate the bug

Summon the horse and let him die.

Edit: I thought the bug only happens when you die on horseback, but apparently it also happens when only the horse dies.

### Version

1.5.0 (Latest)

**Comment by Susanoo1337** [comment]
Can confirm, still a regular issue in 1.5.0.
