### ISSUE TITLE
[Bug]: When one of us dies while other player riding Torrent, Torrent will be invisible

### ISSUE THREAD

**Issue by csorokoporso** [LukeYui/EldenRingSeamlessCoopRelease#574]
### Describe the issue in detail

As the title says, when one of us dies while other players riding Torrent, Torrent will be invisible to the player that just respawned, this can be fixed if the other player re-summons Torrent. Not a game breaking bug, just letting you know.

### Steps to recreate the bug

We only played at Limgrave, so i don't know if this still buggy outside Limgrave. There was 2 players in the lobby when this happened.

### Version

1.5.0 (Latest)

**Comment by frogbombay** [comment]
Also regularly happens for me.
