### ISSUE TITLE
[Bug]: program won't open for both my BF and I

### ISSUE THREAD

**Issue by Saucyyyyy** [LukeYui/EldenRingSeamlessCoopRelease#578]
### Discord Username

ExtraMcSaucy69#1998

### Describe the issue in detail

I was able to open the program and play while I waited for my bf to get on, while I waited he got a report that wouldn't let him even open the game so I got off the game to help and when I joined back I was given the same code. Not sure if this is a mod issue but due to it happening to both of us I would assume so. We've tried a bunch of things and nothing has helped.
![03F4F05A-550F-4B0A-8D45-ACF8AB4DD0D4](https://user-images.githubusercontent.com/128744659/227332880-0209d870-81e9-4b1b-85f4-c3f439dfd732.jpeg)

### Steps to recreate the bug

opening the program

### Version

1.5.0 (Latest)

**Comment by WIZZxBIZZ** [comment]
I am a similar issue, i tried updating the mod and everything but nothing is working, and I have no other mods installed.

**Comment by LukeYui** [comment]
1.5.0 is not compatible with game version 1.09

Thanks.
