### ISSUE TITLE
[Bug]: my friend and i are trying to play seemless co op but his is crashing.

### ISSUE THREAD

**Issue by pizzaboy221** [LukeYui/EldenRingSeamlessCoopRelease#579]
### Describe the issue in detail

its at the white screen at the very start of the loading process, he sees it for a split second, then the game crashes.

### Steps to recreate the bug

.

### Version

1.5.0 (Latest)

**Comment by pizzaboy221** [comment]
adding a bit because i realized it'd probably solve the problem faster. its specifically when he launches the game, not when hes loading into a world or anything, and we're pretty sure we have the exact same folder, here's mine. i say pretty sure because im not talking with him at the moment, so if you need his folder i can get that sometime soon, and also he's able to launch the normal game, just not the mod.
![image](https://user-images.githubusercontent.com/127804045/227352588-bb783835-685b-485f-be04-26206572e52f.png)

**Comment by LukeYui** [comment]
1.5.0 is not compatible with game version 1.09

Thanks.

**Comment by pizzaboy221** [comment]
i found out from reading other threads that his game most likely broke from the steam update this morning. i paused mine last night when it started, his ended up updating and i think thats what's causing the problem, would he be able to roll his game version back? 

> 1.5.0 is not compatible with game version 1.09
> 
> Thanks.

**Comment by pizzaboy221** [comment]
> 

so he can roll his game version back however, its 40+ gigs and he runs on a hotspot, will the mod work on the new game version any time soon?
