### ISSUE TITLE
[Bug]: Wanderer flask resetting to +1 when trying to upgrade from +12

### ISSUE THREAD

**Issue by loki2236** [LukeYui/EldenRingSeamlessCoopRelease#58]
### Discord Username

Epoq#0125

### Describe the issue in detail

My friend was the wanderer and he could in some way upgrade his flasks when they were +12 and they went all the way back to +1

### Steps to recreate the bug

As a wanderer, upgrade the flasks after +12

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment]
I've tried this. Upgraded a flask from +0 to +12

Normal behaviour resulted, the flask upgraded correctly and no reset occurred.

**Comment by loki2236** [comment]
Happened to another player.

Bootman#6943

As a phantom, going from +10 to +11 cause the flask to turn back to +1

**Comment by LukeYui** [comment]
Recreated it successfully. Will be fixed pending the next update.

**Comment by LukeYui** [comment]
Fixed in 1.2.2
