### ISSUE TITLE
[Bug]: Dont run game after the last update

### ISSUE THREAD

**Issue by psychokir** [LukeYui/EldenRingSeamlessCoopRelease#581]
### Describe the issue in detail

The game can´t lauch after the last update
Get a white scren and can´t play the mod 

### Steps to recreate the bug

launch game 

### Version

1.5.0 (Latest)

**Comment by lionsaregod** [comment]
not a great solution but im currently fixing my issue with this by just downloading the old version of elden ring through console

**Comment by LukeYui** [comment]
1.5.0 is not compatible with game version 1.09

Thanks.
