### ISSUE TITLE
[Bug]: White screen, then crash on launch

### ISSUE THREAD

**Issue by pnwdevzac** [LukeYui/EldenRingSeamlessCoopRelease#583]
### Discord Username

ZBhartman#3015

### Describe the issue in detail

Starting a couple of days ago, I've had issues launching the seamless exe. Boots into white screen, then closes/fails. Tried to swap between the 1.4.5 and 1.5 dlls as well as completely removing downloaded zip, redownloading, extracting, etc. This is an immaculate project that I'm excited to continue sharing with friends. You've done the community such a solid. Thank you

### Steps to recreate the bug

Boot seamless_coop exe (after having it work last night for a session with some friends it has completely lost functionality to boot) Tried booting into regular elden ring which worked, then back into seamless and still got the white screen. 

### Version

1.5.0 (Latest)

### Relevant Crash log

```shell
Fault bucket 1982892846025155003, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: eldenring.exe
P2: 1.9.0.0
P3: 6405b0f3
P4: elden_ring_seamless_coop.dll
P5: 0.0.0.0
P6: 6414e93d
P7: c0000005
P8: 0000000000043ccf
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4259b4d8-0bb1-4f0e-83a7-0ace53ba64aa.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c5faf891-76fb-4ef3-8f4d-ac27200bb9ae.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e06f4482-da6d-42c6-ab86-2a6ad1aeb772.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.6ea5554d-28e1-4eac-8217-a785733729de.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7291ef0b-7dbf-425b-8a33-5333af87e9e1.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_eldenring.exe_6a338fd6f7c789337f774a99cab550ca8301_33fb3e7b_f9775aaa-614a-4f64-9dd2-d74ff138e44a

Analysis symbol: 
Rechecking for solution: 0
Report Id: 6e8d1d5e-91b9-4d21-a867-64294ea4afa4
Report Status: 268435456
Hashed bucket: 8a81cb711adc2c92eb84a689a2fe21bb
Cab Guid: 0
```

**Comment by LukeYui** [comment]
Update to 1.5.1
