### ISSUE TITLE
[Bug]: Updated to Client 1.5.1 - Game Continuously Crashing

### ISSUE THREAD

**Issue by cynicalsybill** [LukeYui/EldenRingSeamlessCoopRelease#585]
### Discord Username

cynical_sybill

### Describe the issue in detail

Updated the seamless co-op client to 1.5.1 and upon updating, my game now continuously crashes/won't load past the first load screen. 

I've tried selecting "Continue" and I've tried "Load", both result in crash of the game. My husband has the same exact issue, he and I updated our files at the exact same time, so we both have 1.5.1, and his game will go through the loading screen, then get stuck with playing the audio from th4e game, as if he's in game, but the video will just never load and ultimately the game will freeze his computer and crash essentially everything. He and I are both on $3K+ rigs, so it's not a hardware issue. 

I tried checking my computer's crash log to see if any information was gleaned from the crash, but nothing so far. I do have some weird internal data errors around then that are strange. I did however manage to get a crashdump report in the seamless co-op's folders, but I can't attach it here. I'll try to include what's interesting from it below, however I'm happy to provide more information if it would be helpful.

### Steps to recreate the bug

1. Update seamless co-op client to 1.5.1
2. Start game via seamless co-op client shortcut
3. Click "continue" or "load".
4. Game crashes either instantaneously and brings you back to desktop, or game will freeze and neither crash nor progress. 

### Version

1.5.0 (Latest)

### Relevant Crash log

```shell
Exception code: 0xC0000005
Exception information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

Sorry, I couldn't get any helpful information from the windows crash report as detailed in this section.
```

**Comment by cynicalsybill** [comment]
Quick update - I've tried deleting the 1.5.1 files and reverting back to the 1.5.0 client, and now I'm getting a different error, won't even get the opening game screen before the program has a critical error and crashes. Elden Ring is updated in steam at the time of this post.

**Comment by cynicalsybill** [comment]
Another update - so sorry to bother ya'll, but it seems that normal Elden Ring now won't play either without crashing, so this may not be a "you guys" issue.....

**Comment by CitrusHappy** [comment]
try turning off raytracing

https://steamcommunity.com/app/1245620/discussions/0/3820780968134385349/?ctp=2

**Comment by kotpfw** [comment]
I'm having the same issue, have you figured out how to fix it, or any advice on what I can do

**Comment by cynicalsybill** [comment]
> I'm having the same issue, have you figured out how to fix it, or any advice on what I can do

YES omfg I'm fucking unhinged over this right now hahaha - apparently NVIDIA released a new driver update like, I'm not kidding 2 minutes before the Elden Ring update last night (last night for me, east coast time). I updated my GPU drivers and everything works perfectly fine now for me. 

Try updating your GPU driver, if that doesn't work then I think that CitrusHappy above had the right idea - turn off your raytracing in the game.
