### ISSUE TITLE
[Bug]: Fast travel crashes game at certain game areas

### ISSUE THREAD

**Issue by TikaUnas** [LukeYui/EldenRingSeamlessCoopRelease#589]
### Discord Username

brick#5425

### Describe the issue in detail

Whenever I fast travel to a grace near the Castle Sol or within the castle, once the loading bar fills up, the game crashes. I traveled to an earlier grace more south and it worked find, but once I traveled north a little it crashed. The game just closes instantly without an error message. The same thing happens when I travel to the Erdtree-Gazing Hill grace. Caelid works fine, as well as the Inner Consecrated Snowfield area and Drainage Channel area. Those are the only areas I've tried so far. Ray tracing is disabled, my pc can't even use it, and my drivers are up to date. This is all playing solo without opening up the world, however opening my world did not change anything. 

As for the version, I am on 1.5.1 from the nexus website.

EDIT: I successfully fast traveled to the Castle Sol Rooftop grace, however the game crashed once I went down the elevator. Now the game crashes whenever I load the save.
EDIT: Converting the save to the regular game, the game still crashes upon loading the save, however this time it says program not responding, which gives an error that I added to the crash log.
### Steps to recreate the bug

Simply travel to any of the grace sights that I mentioned, specifically near the Castle Sol or within the castle and the Erdtree-Gazing Hill grace.

### Version

1.5.0 (Latest)

### Relevant Crash log

```shell
Faulting application name: eldenring.exe, version: 1.9.0.0, time stamp: 0x6405b0f3
Faulting module name: eldenring.exe, version: 1.9.0.0, time stamp: 0x6405b0f3
Exception code: 0xc0000005
Fault offset: 0x0000000001648166
Faulting process id: 0x4820
Faulting application start time: 0x01d95eabc3197cad
Faulting application path: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: D:\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Report Id: 07cf11ab-b6da-42d8-8c39-24b5fe8c2eef
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by LukeYui** [comment]
Did you try verifying your game files with Steam?

**Comment by TikaUnas** [comment]
So I verified the files and now it works in regular elden ring. I haven't launched to try it in seamless coop mode but once its updated I'll give it a try. 
Thanks
