### ISSUE TITLE
[Bug]: Italian translation file has wrong quotation marks in one line

### ISSUE THREAD

**Issue by dev-shaa** [LukeYui/EldenRingSeamlessCoopRelease#592]
### Describe the issue in detail

At line 376 of the Italian locale (`BONFIRENAME_30182950`) the line ends with `”` and not `"` which makes the json file invalid. When the game starts it shows an error message and then defaults to the english language. After replacing it, the error doesn't occur.

### Steps to recreate the bug

Simply open the game with italian translation turned on.

### Version

1.5.0 (Latest)

**Comment by LukeYui** [comment]
Thanks for letting me know. It will be resolved in the next update.

**Comment by opslash** [comment]
i would like to fix this
