### ISSUE TITLE
[Bug]: Russian translation file missing symbols in one line

### ISSUE THREAD

**Issue by Ringoto** [LukeYui/EldenRingSeamlessCoopRelease#593]
### Describe the issue in detail

In the json file with Russian localization, at line 177 `"BONFIRENAME_1052532950"`, the symbols `",` are missing at the end. For this reason, the json file does not run. After fixing everything works fine.

### Steps to recreate the bug

Launch the game with russian locale

### Version

1.5.0 (Latest)

**Comment by LukeYui** [comment]
Thanks for letting me know. It will be resolved in the next update.
