### ISSUE TITLE
[Bug]: Including a "@" in the online password breaks the mod

### ISSUE THREAD

**Issue by Sparkolo** [LukeYui/EldenRingSeamlessCoopRelease#595]
### Describe the issue in detail

As title, having the "@" character in the password makes the modded exe fail to launch the game

### Steps to recreate the bug

• Insert the email sign "@" in the online password
• Run the mod exe
• A black terminal screen appears for a second
• The game does not launch

### Version

1.5.0 (Latest)

**Comment by LukeYui** [comment]
It works for me. Can you post a crash report? Also please post more information such as game version.
