### ISSUE TITLE
[Bug]: Nerijus invasion aborted 

### ISSUE THREAD

**Issue by Sh1r01-K4g3** [LukeYui/EldenRingSeamlessCoopRelease#598]
### Discord Username

Sh1r01_K4g3#6204

### Describe the issue in detail

Me and a friend went to fight nerijus while both on torrent and he didn’t summon, alert on screen said he returned to his world and Yura moved as if we defeated him but no rewards were given

### Steps to recreate the bug

On horseback go from Agheel lake north down the ramp, past the skeleton ambush up towards the catacombs, past Patches’ cave. It is possible that me or the host accidentally left the area for nerijus to summon while it was happening but no fog barrier appeared (and this wasn’t intentional if we did accidentally leave)

### Version

1.5.1 (Latest)

### Relevant Crash log

```shell
I’m not tech savvy enough to think to do this
```

**Comment by LukeYui** [comment]
It's because you ran too far. The mod removes all fog walls from multiplayer so it wouldn't have been there. You can still get invaded by NPCs you just can't invade them at the moment (e.g. volcano manor quests)
