### ISSUE TITLE
[Bug]: Not able to mount the horse as guest after dying in open world boss fight

### ISSUE THREAD

**Issue by F0rce1991** [LukeYui/EldenRingSeamlessCoopRelease#599]
### Describe the issue in detail

After joining as guest to another players game and dying during a open world boss fight (I have onlytested this issue with tree avatars, but I think it occures with every open world boss), I'm not able to mount the horse after respawn. If I die under other circumstances this problem doesn't occure.

### Steps to recreate the bug

- Join the game of another player
- Die during an open world boss fight
- Try to mount the horse after respawn

### Version

1.5.1 (Latest)

**Comment by BlackDragonBE** [comment]
I can also confirm this bug. The host can see Torrent appearing briefly and then disappear, while the guest doesn't see anything after whistling.

**Comment by AndriySvyryd** [comment]
Only happens when the guest dies while riding Torrent
