### ISSUE TITLE
[Bug]: Rot Essence: Despair not removed after resting at site of grace

### ISSUE THREAD

**Issue by Ed-boye** [LukeYui/EldenRingSeamlessCoopRelease#60]
### Discord Username

Ed_boye#0069

### Describe the issue in detail

There seems to be an issue with one of my saves where I cannot remove two Rot Essence: Despair in my key items. Additional context in steps to reproduce.

Perhaps these don't actually do anything in single player mode? I will update this bug after I try resting when in a coop session to see if that removes them.

### Steps to recreate the bug

I started this save when the mod was first released
I am trying to remove these Rot Essences in singleplayer though not sure if I was also carrying them while playing with my friend.
I've tried different sites of grace still unable to remove them
I've tried dying as well and then resting--no luck

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment]
Hi, thanks for the report. You're right, the rot essence is both inactive and permanent while in single player. If you want to remove it, could you try using the tiny great pot to open a session then resting? That should remove the rot, and you can close the session afterwards if you like.
