### ISSUE TITLE
[Bug]: Dodge Bug

### ISSUE THREAD

**Issue by Lskiis** [LukeYui/EldenRingSeamlessCoopRelease#617]
### Discord Username

Lskiis#3739

### Describe the issue in detail

i get a wierd bug where if i dodge i start automatically running backwards, theres nothing i can do to stop unless i restart the game, it happens consitentl as soon as i dodge. ive reinstalled the mod and bug persists, and does not occur in the base game. HELP.

### Steps to recreate the bug

all i do is click the dodge button, ive rebound it to a different key to see if its my NEW keyboard but issue persists - doesnt happen in base game

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
not a bug with the mod...
