### ISSUE TITLE
[Bug]: A couple bosses randomly dying after sitting at grace

### ISSUE THREAD

**Issue by reconwafflez** [LukeYui/EldenRingSeamlessCoopRelease#618]
### Describe the issue in detail

Occasionally when me and a friend sit at a grace we get the "Great Enemy Felled" message along with souls + boss items if available. The things we have gotten is 5 dragon hearts and the Ruins Greatsword. The dragon hearts seem to be from Elder Dragon Greyoll and the surrounding dragons, and the Ruins Greatsword obviously from the duo boss fight in Redmane. 

### Steps to recreate the bug

Not sure how to get it to happen, but it has only happened after sitting at a grace.

### Version

1.5.1 (Latest)

**Comment by mivor** [comment]
This also happened to me, after a the host's game crashed. Suddenly some bosses died and I gained like 400k runes.

**Comment by carlosomarpabon** [comment]
Same thing happened to me. I got 5 dragon hearts and tens of thousands of runes.
