### ISSUE TITLE
[Bug]: Melina always talks to wanderers about taking her to the mountaintop of the giants after beating Morgott

### ISSUE THREAD

**Issue by 3th3** [LukeYui/EldenRingSeamlessCoopRelease#62]
### Describe the issue in detail

Melina talks to wanderers about taking her to the mountaintop of the giants every time they rest at a grace. Does not happen to the hosts, only the wanderers

### Steps to recreate the bug

Beat morgott and have a friend co op with you afterwards. whenever they rest at a grace they get pestered by Melina

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment]
Duplicate of #61
