### ISSUE TITLE
[Bug]: Malenia boss fight breaks if you rest at a site of grace.

### ISSUE THREAD

**Issue by nm12001** [LukeYui/EldenRingSeamlessCoopRelease#625]
### Describe the issue in detail

As the title suggests, Malenia's boss fight can be broken if one of the players in a session rests at a site of grace. Her AI stands fully still, doesn't do any attacks. However, she can be beaten that way, as she still takes damage.

### Steps to recreate the bug

1. Co-operator/host walks through Malenia's fog gate.
2. A person rests at a site of grace

And that's pretty much all there's to it. 

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
Not really a bug, just don't do this.
