### ISSUE TITLE
[Bug]: Game crash BSOD's

### ISSUE THREAD

**Issue by nkonneck** [LukeYui/EldenRingSeamlessCoopRelease#628]
### Discord Username

riister#6273

### Describe the issue in detail

Randomly while playing co-op, my game crashes with a BSOD. The error is mostly a bug check failure with a Memory Exception Error. Running through Windbg and processing the dump file, I located the error with eldenring.exe listed as the process name. I thought I had actual hardware issues and have replaced every component of my computer, not thinking the mod would cause it. I've contacted support as well to no avail and it only happens when running the mod. What is causing it though is unknown to me at this point. 

Running Elden Ring direct through Steam, I have no crash issues or other crashes with any other games. 

Not sure if it is relevant, but here are my comp specs - ALL hardware is brand new, less than a month old.

- CPU - AMD Ryzen 9 5900X
- GPU - GeForce RTX 3070
- SSD - Samsung 980 PRO 1TB, PCIe Gen 4x4 NVMe
- RAM - Corsair Vengeance PRO RGB 32GB DDR4
- PSU - Corsair RM1000x
- CPU Cooler - CoolerMaster ML240L AIO
- Mobo - Gigabyte B550 Aorus Elite AX V2 - BIOS version FB
- OS - Windows 11

all drivers are up to date - even tried rolling some drivers back to see if there was a potential conflict. also tried using my older RAM which are Corsair Vengeance LPX 32GB DDR4. Also tried just using Windows 10, fresh install with no other programs installed. Same with Windows 11 - only driver updates and necessary files to run the game with nothing else installed. 

### Steps to recreate the bug

It's hard to re-create it as it happens randomly. Sometimes it happens within 10-15 minutes, other times 3-4 hours after playing. 

Things I have tried though:

- Turning XMP on or off
- Lowering graphics quality
- Having no other applications open
- Opening my world to have my friend join, rather than me joining their world
- Playing through the mod solo to see if co-op play was causing an issue
- Loading in to the game and just letting it sit

### Version

1.5.1 (Latest)

### Relevant Crash log

```shell
Faulting application name: eldenring.exe, version: 1.9.1.0, time stamp: 0x642e6380
Faulting module name: elden_ring_seamless_coop.dll, version: 0.0.0.0, time stamp: 0x641cc4e0
Exception code: 0xc0000409
Fault offset: 0x000000000013bb99
Faulting process id: 0x0x3360
Faulting application start time: 0x0x1D9724E5E35236A
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: C:\Program Files (x86)\Steam\steamapps\common\ELDEN RING\Game\SeamlessCoop\elden_ring_seamless_coop.dll
Report Id: b22431db-1144-466f-949a-816f71167097
Faulting package full name: 
Faulting package-relative application ID:
```

**Comment by LukeYui** [comment]
HI, do you have a full crash log? The report attached is generic and doesn't help diagnose the issue. Thanks

**Comment by nkonneck** [comment]
https://drive.google.com/file/d/1cQbMlFy_UnlgKN3IXf5fnkYzBuaEt3J0/view?usp=share_link 

this is the link to the dump file. running in windbg is where I found the error in deeper detail.

**Comment by LukeYui** [comment]
I meant the crash report generated in "..Game\SeamlessCoop\crashdumps"

**Comment by nkonneck** [comment]
https://drive.google.com/file/d/13F-ELlyKzZ9TypVuXXkBOmafUBpLDJVv/view?usp=share_link

**Comment by nkonneck** [comment]
So…what was the problem? Is it fixed or do I need to do something to fix it?
