### ISSUE TITLE
[Bug]: Trapped chest

### ISSUE THREAD

**Issue by smog1217** [LukeYui/EldenRingSeamlessCoopRelease#63]
### Describe the issue in detail

When my brother had opened the trap chest in Patches' place me and him where sent to the area with all the bears, we went up to the third church of Marika to rest and get rid of the captured status. the capture status persisted through resting at the bonfire so we where unable to fast travel. eventually we both died, which seemed to fix it.

### Steps to recreate the bug

I have yet to try to recreate it, and I'm unsure if it's a persistent bug or not.

### Version

1.2.1 (Latest)

**Comment by jksmilton** [comment]
Some more details, same version:
Using the trap chest at tower of return it didn't matter which player activated the chest, only one player was transported (only tried once each). The player not teleported was considered trapped and didn't lose the condition until they died. While separated grace discovery wasn't synchronised across games either.

No idea if its useful information but both games thought the other player was in the vicinity and the "clones" did the same actions as the actual player. Enemies would target the clones but the clones didn't take damage, didn't manage to check if the clones could hurt enemies.

**Comment by LunarFuror** [comment]
We also ran into this issue. I was the "host" and one of my 2 buddies opened the chest after we beat patches into submission. One of the other 2 opened the chest. We all went to the same Church bonfire, their trapped condition cleared, mine did not. Had to quit to character select to clear.
