### ISSUE TITLE
Co-op not working due to being out of date of the new updated 1.09.1 elden ring.

### ISSUE THREAD

**Issue by decentcloth** [LukeYui/EldenRingSeamlessCoopRelease#630]
### Discord Username

Bubatunde#1946

### Describe the issue in detail

the entire seamless co-op mode is not working but i cant still play on the seamless co-op server but its just like vanilla elden ring I cant even join my friends and also the stuff that you use to join someone like the stake of marika ect don't show up they just say ICONS, I think it is to do with the fact that elden ring just had update 1.91 and mabey the mod isn't up to date but it really SUCKS because  I love playing elden ring with friends on this MOD and I can't now. 

### Steps to recreate the bug

Load up the MOD on the new version of elden ring and try join someone else.

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
Mod works on 1.09.1
