### ISSUE TITLE
[Bug]: unable to start new game plus

### ISSUE THREAD

**Issue by JLAarwen** [LukeYui/EldenRingSeamlessCoopRelease#632]
### Discord Username

EliasFenic#6214

### Describe the issue in detail

My friend and I beat the game. He triggered the frenzied flame ending as I was disconnecting to do a different ending. It triggered the cutscene for both of us. After the ending it prompted us to enter new game plus. We said no so that we could get the remembrance of the elden beast.

Once we had what we wanted we pressed new game plus. Both of us froze. No inputs would work on the keyboard or mouse but the animations on screen continued. We has to quit the game via task manager.

Now I do not have the option to enter new game plus and cannot enter the end tree.

Also, when I travel to the elden throne sight of grace I cannot fast travel until after jumping off a ledge

This has Effectively locked me from progressing.

### Steps to recreate the bug

Defeat elden beast. Host Chooses frenzied flame ending but cooperater uses white mist at about the same time. Now cooperater should not be able to enter new game plus. And fast travel from the elden throne should be broken

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
#121

**Comment by JLAarwen** [comment]
I've viewed the linked thread. It is not the same issue. I am at the round table hold, resting at the fire there. There is no option to start new game plus.
