### ISSUE TITLE
[Bug]: Game closing in a especific area

### ISSUE THREAD

**Issue by Mucahs10** [LukeYui/EldenRingSeamlessCoopRelease#635]
### Discord Username

Mucahs10

### Describe the issue in detail

I killed comander nail, and after going trought the ice lake, the game crashes, all the rest of the map works fine. My coop mate, goes and take a site of grace after the lake, i try to teleport and still crashing, cant progress.

### Steps to recreate the bug

walking or getting near the ice lake before comander nail, trying to teleport still crashes

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
Ignoring this because you haven't explained what you've tried, and you've attached no crash report.

**Comment by Mucahs10** [comment]
Hi Lule, sorry. I tryed nothing, just walking to advance in that location, the game suddently closes. That happens everytime i go there, so, i cant advance the game
