### ISSUE TITLE
[Bug]: Game closing alone in a specific part of the map

### ISSUE THREAD

**Issue by Mucahs10** [LukeYui/EldenRingSeamlessCoopRelease#636]
### Discord Username

Muca#5758

### Describe the issue in detail

Hello,

My game is closing alone, in a specific part of the map, next to the ice lake (where there is a dragon). I killed Commander Nail, but I can't progress in the game because of that, when I get close to the area the game closes by itself (I'm not trying anything specific, just getting close already closes). My friend who is in the coop with me, manages to advance normally, he got the grace right after the lake, I tried to teleport there, and even so the game closes alone. This is preventing progress... the rest of the map works normally.

### Steps to recreate the bug

I didn't do anything specific, I'm just trying to pass that part of the map to progress in the game

### Version

1.5.1 (Latest)

### Relevant Crash log

```shell
Warning: Updated file "SteamService.exe" from version 0x0007005e003a0057 to version 0x000800020012002c.
Warning: Updated file "secure_desktop_capture.exe" from version 0x0007005e003a0057 to version 0x000800020012002c.
Warning: Updated file "steamxboxutil64.exe" from version 0x0007005e003a0057 to version 0x000800020012002c.
Warning: Updated file "SteamService.dll" from version 0x0007005e003a0057 to version 0x000800020012002c.

There is nothing with the name elden ring, just steam
```

**Comment by LukeYui** [comment]
Try the common debugging steps listen on the NexusMods page.
