### ISSUE TITLE
[Bug]:  Bosses getting stuck

### ISSUE THREAD

**Issue by adecoy95** [LukeYui/EldenRingSeamlessCoopRelease#64]
### Describe the issue in detail

When fighting bosses, when one of us dies it causes the boss to stop attacking, he just stands there, happens with godrick the grafted and happened with another boss before

### Steps to recreate the bug

just go fight godrick and let player 1 die

### Version

1.2.1 (Latest)

**Comment by halphius** [comment]
the bug is repeatable with rennala as well

**Comment by PowerElites** [comment]
Me and my friends experienced this constantly with Godrick.

**Comment by Ekibunnel** [comment]
yeah it make that no one has to die in the malenia fight or else she go brain dead.... it's very annoying.

[Video Link](https://youtu.be/042M2V75aBE?t=72)

**Comment by Dizis249** [comment]
Keeps happening to us with pretty much every boss and the runebearers in particular. Even happened with the Elden Beast.

**Comment by Daco-cl** [comment]
Hi, i can confirm this bug. It has happened to me with several bosses This is a serious picture showing it
![elde_bug](https://user-images.githubusercontent.com/109253757/178858224-f3bc4b4f-9333-44c3-8209-5434ee05f53a.png)
t

**Comment by A1steaksa** [comment]
This is still a problem on beta 1.5.0 and causes fighting Rennala to be very time consuming, as the co-op partner needs to fully disconnect and reconnect before you can try again as there's no good way to start over in that situation.
