### ISSUE TITLE
[Bug]: Disconnected from host and returned to my own world 30 seconds after joining.

### ISSUE THREAD

**Issue by KankBank** [LukeYui/EldenRingSeamlessCoopRelease#640]
### Discord Username

KankBank#8330

### Describe the issue in detail

My friend cannot join my world, but I can join his. Every time I join his world I get disconnected and returned to my own after around 30 seconds. This issue has persisted for several updates, with or without other mods. If it is a client side issue, I have no idea how to fix it because I cannot find anything online about it.

### Steps to recreate the bug

I just join my friend's world and wait around 30 seconds, then I get disconnected.

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
Bad internet
