### ISSUE TITLE
[Bug]: Friend does miniscule damage when joining my world or when i join him.

### ISSUE THREAD

**Issue by Yushimer** [LukeYui/EldenRingSeamlessCoopRelease#643]
### Discord Username

ExYushimer#5686

### Describe the issue in detail

For some reason, when my friend is in his world (and he is not playing online) his damage is as it should. Let's say 200 per hit.
The moment i join his world or he joins me, his damage becomes like 50, like a broken weapon from Dark Souls games. Restarting the game resolves the issue, but when again, he joins or i join (using online must be the culprit for some reason,  the moment he uses Tiny Pot (to open world), his damage is reduced. It only has happend to him, i'm not affected, not in his world nor mine.
I've been using the mod for about 6 months now, and it's a first time that this happend. Any suggestion?

*edit: Spells do the right damage, only weapons seem to have reduced damage. So propably a bug from the backstab i say below

### Steps to recreate the bug

If i'm not mistaken, he backstabbed an enemy without a weapon, disconnected because of internet and now When he opens his world or i open mine, the moment he uses Tiny Pot (to open world) his damage is vastly reduced

### Version

1.5.1 (Latest)

**Comment by Yushimer** [comment]
The problem seems to be character specific too. When we join with another character, the damage is as it should.

**Comment by LukeYui** [comment]
It's not a bug. Make sure they don't have any rot essence which can reduce damage (found in the key items tab of the inventory) and try resting at a site of grace to remove it.

**Comment by Yushimer** [comment]
> It's not a bug. Make sure they don't have any rot essence which can reduce damage (found in the key items tab of the inventory) and try resting at a site of grace to remove it.

No really, even if he rests, has a rune arc, dies, hasn't died, the damage is still in the 50s. If it was rot essense, her spells would do low damage too. Anyway, we tried it but it's not that sadly

**Comment by Yushimer** [comment]
> It's not a bug. Make sure they don't have any rot essence which can reduce damage (found in the key items tab of the inventory) and try resting at a site of grace to remove it.

Add me on discord if you want me to send you some videos

**Comment by Yushimer** [comment]
Changing multiplayer passwords seem to have resolved the issue
