### ISSUE TITLE
[Bug]: Teleport to Round Table softlocked both players when in co-op and talking to Melina at the same time

### ISSUE THREAD

**Issue by hexotoxin** [LukeYui/EldenRingSeamlessCoopRelease#645]
### Describe the issue in detail

We were in co-op both resting at the site of grace and talking to Melina. I accidentally activated the teleport through her dialogue to the Rount Table. It teleported me successfully, but the other person playing remained softlocked at the site of grace. When I opened the map attempt to teleport back to the original site of grace the game became stuck on the map, softlocked as well. 

### Steps to recreate the bug

Let Melina take you to the Round Table hold while another player is sitting at the site of grace.

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
Works properly for me. Can't recreate it
