### ISSUE TITLE
[Bug]: Every enemy is scaled extremely high with only two players

### ISSUE THREAD

**Issue by redcj22** [LukeYui/EldenRingSeamlessCoopRelease#646]
### Discord Username

Smegma male#7182

### Describe the issue in detail

Me and my friend have been playing this mod and noticed that enemies and bosses are having their health and damage scaled up to ng+ levels.  Is this an issue or feature of the mod?

### Steps to recreate the bug

Since we started it has been this way

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
Not a bug, it's just the scaling. For 2 players health and resistances are more or less doubled
