### ISSUE TITLE
[Bug]: Infinite loading loop after playing with friends for a few hours, then teleporting to Roundtable in solo play.

### ISSUE THREAD

**Issue by DevinBacon7** [LukeYui/EldenRingSeamlessCoopRelease#647]
### Discord Username

Devin Bacon#4367

### Describe the issue in detail

I made my character, progressed to the point of unlocking Torrent, then talking to Ranni, then ran to the Grace just before Margit.
After that, I joined some friends that had progressed a bit further than me. They hadn't killed any bosses yet, but they did unlock the Roundtable Hold, while I had not.
Being in their world, however, I then could teleport to any Sites of Grace that they have unlocked, so we were able to go to the Roundtable Hold regardless of the fact I haven't unlocked it yet.
We played for a few hours, killed Margit with no armor and just clubs, worked our way up to Godrick, attempted to kill him a few times, then called it a night after getting into his 2nd phase a few times.
I returned to my world, then rested at a Site of Grace that I unlocked in my friend's world (though it sort of treated me as if I haven't activated it yet, despite it also being available on the map) and then Melina took me to the Roundtable Hold, where I was stuck in an infinite loading loop. I can't do anything about it. I restarted my game, and it still happens.

### Steps to recreate the bug

Uncertain if it would actually work, but I guess going to Roundtable Hold in a friend's world before you've unlocked it yourself, then go there when Melina offers to take you there?

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
#645
