### ISSUE TITLE
[Bug]: Malenia keeps healing while attacking dead player

### ISSUE THREAD

**Issue by michaelmdresser** [LukeYui/EldenRingSeamlessCoopRelease#648]
### Describe the issue in detail

If Malenia kills a player during one of her combo moves, she seems to keep healing while finishing the combo. I would expect her to stop healing after the last hit that kills the player.

### Steps to recreate the bug

Go to Malenia (with 3 players? not sure if that matters). Have 1 player killed by Malenia during a combo move. Observe her health increase while she finishes her combo on top of the dead player.

### Version

1.5.1 (Latest)

**Comment by LukeYui** [comment]
Not a bug with the mod, it's just how the hitboxes work.
