### ISSUE TITLE
[Bug]: One of the friends get kicked from session 

### ISSUE THREAD

**Issue by ZeaGmoN** [LukeYui/EldenRingSeamlessCoopRelease#65]
### Discord Username

ЈованЦ.#0309

### Describe the issue in detail

It happens after the 1.2.0 update.
Me and 2 friends are trying to play ER via Seamless Coop. 1 makes session and 2 others joins the session, right?
Well, no. One who joins the session can see everyone else, but other player can't see his avatar nor his hp bar, idk about host.
This player can damage enemies but for few seconds until they get their hp back the same amount of players damage. 
Also the player who's invisible to the other one, gets kicked from session after 2-3minutes.
I think it has something with mod since all 3 of us use the same mod version, and it didn't happen before.

### Steps to recreate the bug

Joins players session

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment]
Hi, thanks for the report.

I'll look into it, though I can't recreate any of the bugs that you are experiencing. Is it only that 3rd player experiencing those issues - it could be that their connection quality is poor.

**Comment by ZeaGmoN** [comment]
> Hi, thanks for the report.
> 
> I'll look into it, though I can't recreate any of the bugs that you are experiencing. Is it only that 3rd player experiencing those issues - it could be that their connection quality is poor.

Is always different player who gets kicked, depending on the host.

**Comment by Scooda** [comment]
I'm experiencing the same issue no matter who I join. No one can see me but I can see everyone else. I hit enemies and the regen the health I hit them for they also ignore then about a minute or two later I'm returned to my own world. I have a video that shows what goes on as well
