### ISSUE TITLE
[Bug]: Players still respawning automatically during boss fights 

### ISSUE THREAD

**Issue by gitKevinW** [LukeYui/EldenRingSeamlessCoopRelease#66]
### Discord Username

SmoliSandwiches#3606

### Describe the issue in detail

Happens when fighting various bosses in Elden ring. When playing with 4 players, when a player dies sometimes they would respawn automatically instead of going into the spectator screen.

### Steps to recreate the bug

When fighting a boss, go die and there is almost a 40 percent chance of respawning. Cannot say exactly which bosses as it happened to many/various bosses. 

### Version

1.2.1(Latest)

**Comment by LukeYui** [comment]
Hi, thanks for the report.

I'll look into it. You will only enter spectator mode if the boss health bar is present on the screen. There is a bug which means that the bar won't appear for some players when fighting the boss, and that might be the issue.

**Comment by Dizis249** [comment]
Same happens here from time to time but with a total of 2 players in a session.
