### ISSUE TITLE
[Bug]: Can't join a friends session

### ISSUE THREAD

**Issue by BosForPresident** [LukeYui/EldenRingSeamlessCoopRelease#69]
### Discord Username

BosForPresident#9853

### Describe the issue in detail

When i'm trying to join my friends session with the effigy of malenia i can't join. I see the message that it is trying to join and then nothing happens. Normally i can't use the mod items after it is trying to join but this doesn't seem to be the case when i can't join, i can use the items almost instantly after i used it the first time. I don't know if this has something to do with my internet connection or not but i don't think this is the case, since almost everytime i use it for the first time after booting the game for the first time on the day i can join. He can join me and another friend can join his session with no problem.

### Steps to recreate the bug

Don;t really know, it just happens when i try to join.

### Version

1.2.1 (Latest)

**Comment by tuxplex** [comment]
Same - playing with my son and both of us tried to host and join without success - nothing happend
Updated to the latest version some hours ago.

Version
1.2.1 (Latest)
