### ISSUE TITLE
[Bug]: Infinite loading loop after travelling to roundtable

### ISSUE THREAD

**Issue by bluesbus** [LukeYui/EldenRingSeamlessCoopRelease#73]
### Discord Username

bluey#4527

### Describe the issue in detail

Video:

https://user-images.githubusercontent.com/51495814/173152482-a3f4ea81-0f5b-4fd6-9ccc-0cdc96a05156.mp4

Basically, after being invited to the round table in singleplayer, traveling there started an infinite loading loop.

### Steps to recreate the bug

Not sure what is relevant so I will just describe the entire session.

We joined the host while he was in the roundtable hold. I do not think the rest of us had access to the roundtable hold at this point. So me and my two other friends could not vote to go there, but the host could. We went to Caelid and Weeping Peninsula and explored around, and never got an invite to the hold. Then we defeated Margit and Godrick, still no invite. After defeating Godrick, we disconnected and the three of us (but not the host) sat at a site of grace and were invited to go to the roundtable hold.  All three of us accepted, and all three of us got into the infinite loading loop. 

### Version

1.2.1 (Latest)

### Relevant Crash log

```shell
No crash log
```

**Comment by norperz** [comment]
same issue, here's my save file if you guys need to see data with the issue

[ER0000.zip](https://github.com/LukeYui/EldenRingSeamlessCoopRelease/files/8883259/ER0000.zip)

**Comment by OneWhoLepps** [comment]
I also have this issue.

**Comment by ryvin** [comment]
My friends and I have also experienced this, I got out of the loop by killing the game and reloading. My friend gets the loop even when he loads the game back up

**Comment by LukeYui** [comment]
> same issue, here's my save file if you guys need to see data with the issue
> 
> [ER0000.zip](https://github.com/LukeYui/EldenRingSeamlessCoopRelease/files/8883259/ER0000.zip)

Thank you for this, I've managed to find the problem. I'll get back to you when I have a solution

**Comment by DieselRulez** [comment]
Hey, if you search "#105" and look at a comment from N0rd on a similar closed thread it will tell you to enable the flag 105 with the debug tool, this fixed it for me :>
