### ISSUE TITLE
[Bug]: Shardbearers breaking when another player spectates

### ISSUE THREAD

**Issue by flowuh** [LukeYui/EldenRingSeamlessCoopRelease#75]
### Discord Username

flowuh#3136

### Describe the issue in detail

Me and my friend have been attempting to play the entire game within the coop mod, and have noticed several big issues already.
One of the biggest being that bosses with cutscenes in between their phases (i.e Godrick, Rennala, Rykard) will totally break when another player dies. Most of the time they will just stop moving and attacking, and just letting you wail on them until they die. We would restart the fight whenever this would happen because its not fun otherwise.

### Steps to recreate the bug

Go to Godrick, whittle him down to his second phase where he gets the dragon arm, and let another coop player die. This can include the host.

### Version

1.2.0

**Comment by halphius** [comment]
Yep. Myself and friends have been experiencing this exact bug.
