### ISSUE TITLE
Failed to find "eldenring.exe" on Linux

### ISSUE THREAD

**Issue by KinoSchmino** [LukeYui/EldenRingSeamlessCoopRelease#8]
When trying to run the mod under ProtonGE 7-17 in Linux, the mod shows a dialogue box stating that it could not find eldenring.exe even though it is undoubtedly in the same directory as the game executable.

![Screenshot from 2022-05-29 20-46-39](https://user-images.githubusercontent.com/36028029/170913619-7ad2332e-754d-4cee-bd58-3d7e407945ff.png)
![Screenshot from 2022-05-29 20-48-40](https://user-images.githubusercontent.com/36028029/170913819-6bf78d21-c97c-4e45-93b0-6911af2b8699.png)

**Comment by thembees** [comment]
You need to launch the seamlesscoop exe through the same wine prefix as Elden Ring on Steam, here's the easy workaround I use: 
Add a non-steam game, and point it to the seamless coop exe like so: 
![image](https://user-images.githubusercontent.com/106179211/171033044-bf4c8e42-62f1-4c4a-9bdc-de6fcb8902cd.png)

Works great for me!

**Comment by KinoSchmino** [comment]
Thanks for the reply!
I probably should have mentioned this in my initial post, but I was running it through the same wine prefix as the base game. The issue seemed to be that the path to the game directory was too long. Shortening it resolved the issue entirely!

**Comment by nullstalgia** [comment]
How are you setting the WINE prefix? When adding the launcher as a Non-Steam game, it makes a new prefix in `~/.local/share/Steam/steamapps/compatdata/<random number>/` instead of using the Elden Ring prefix in `~/.local/share/Steam/steamapps/compatdata/1245620/`

**Comment by KinoSchmino** [comment]
@nullstalgia You are right, it does create a new wine prefix when you add a non-steam game. I guess I somehow got confused about how the wine prefixes work and thought the mod was using the same prefix as the game. I am new to the Linux community, so some of this stuff is kinda confusing. 

Here is what works for me:
![Screenshot from 2022-06-02 15-09-20](https://user-images.githubusercontent.com/36028029/171746845-96e9789d-bb39-4e27-9c9e-f060a41942f9.png)
No special arguments or anything and it works fantastic!
