### ISSUE TITLE
[Bug]: chariot  falling off bridge and getting stuck

### ISSUE THREAD

**Issue by singleshotgamer** [LukeYui/EldenRingSeamlessCoopRelease#80]
### Discord Username

single shot#7748

### Describe the issue in detail

![image](https://user-images.githubusercontent.com/38291227/173164054-3ae34fc5-5164-4bea-b997-0ebb33cbfbc7.png)
The chariot from stranded graveyard once on the second level will sometimes fall down the middle hole and end up stuck.
some times if free it self then fall down the pit. after wards it will be gone until reset at a grace.

### Steps to recreate the bug

not sure if its consistent, but when two players are on the map, on is near the bridge, and another is in the upper walk way, he always falls down.

### Version

1.2.1 (Latest)

**Comment by AranaiRa** [comment]
Some more information from a different session with a similar issue.

The chariot in the Fringefolk Hero's Grave frequently gets confused over which player to use to determine what part of the ramp it should be menacing. At one point, ours even stopped mid charge, spun diagonally, and moved itself into one of the hidey holes, getting stuck until we rested at the Grace to reset the dungeon.

The jars on the ceiling used to destroy the chariot also did not respawn on resting. We tried individual rests and both of us resting at the same time.

**Comment by Ed-boye** [comment]
I ran into this issue as well and I could only guess that it had something to do with me and my friend being separated inside there. I had died so had gone back to the grace. Then I think the chariots started targeting us seperately/weirdly and they started acting weird and getting stuck in places.

We ended up just making sure we were sticking together the whole time for this.
