### ISSUE TITLE
[Bug]: Locked in Ranni's Rise, during her questline after talking to Blaidd in Siofria....

### ISSUE THREAD

**Issue by Potatokev1n** [LukeYui/EldenRingSeamlessCoopRelease#82]
### Discord Username

potatokev1n#7918

### Describe the issue in detail

My wife and I were doing Rannis's questline and reached the point of talking to Blaidd in Sofria. However, when we fast-traveled to Rannis's rise to talk to Seluvis nearby, the fog walls that come up when first talking to Ranni and her followers reappeared. Ranni cannot be talked to since she's asleep and there are no other NPCs to talk to. I'm stuck in Rannis rise and my wife is unable to enter Rannis' in her own game. I am basically rendered soft-locked out of fast travel due to the "trapped" debuff. 

Side note: Love the mod, you rock!

### Steps to recreate the bug

This takes place in Rannis's rise during her questline after talking to Blaidd in sofria, when he tells you to talk to Seluvis. When you fast-travel to Rannis at this point, you're unable to leave the area. Invisible fog walls like those in the initial Ranni dialog are in effect just without the other NPCs, and Ranni is asleep.

### Version

1.2.1 (Latest)

**Comment by Eitheages** [comment]
Yesterday i almost met the same bug playing with my friend. But we got stuck because of Seluvis's disappearance, and after rest beside Site of Grace we saw him again, talked to him and then Ranni then we are free.

**Comment by Potatokev1n** [comment]
Hey , I'm just replying to let you know that the bug has somewhat of a fix
that i found. To not be trapped in rannis rise you must join a friend whose
hasn't defeated radahn and who is far from the caria manor vicinity, the
issue should fix once radahn has been defeated. It's not much of a fix but
if you can let people know as you have more clout. Also to fix the
teleportation thing just use a random teleporter.

**Comment by oCursed** [comment]
Killing Radhan makes the teleportation available, but if you teleport to Ranni's Rise again, the issue remains the same, the teleportation is get back to "locked". The barrier is still there.

More and more people are getting this issue, I guess that everybody should avoid Ranni's Rise for now.

**Comment by dotEXCEL** [comment]
Ok here is the fix

Step 1: One player is creating a new character and joins the bugged lobby of player 2 to grab the site of grace at ranni's tower

Step2: Player one leaves the lobby and fast travels up to rannis tower

Step 3: Player 2 (bugged save) joins player 1's lobby and both talk to ranni and the spirits and ranni again

Step 4: Player 2 leaves player 1's world

Step 5: Player 2's savegame should be fixed.

Step 6: Repeat this until all savegames are fixed

Step 7: No need to thank me :D
