### ISSUE TITLE
[Bug]: Killing Tearstone Scarab When Too Far Away Locks Users Out of Skill

### ISSUE THREAD

**Issue by Dimmondback** [LukeYui/EldenRingSeamlessCoopRelease#88]
### Discord Username

Dimmondback#6304

### Describe the issue in detail

Friend killed Bloodflame Scarab (Liurnia of the Lakes near Rose Church) while the rest of us were near boilprawn shack and the 3 of us did not receive the skill but when joining another of our worlds the scarab does not spawn anymore.

### Steps to recreate the bug

Have 1 player kill bloodflame scarab at Rose Church while another player is at Boilprawn Shack

### Version

1.2.1 (Latest)

**Comment by Keiggy** [comment]
Same thing happened to me and my friend in Limgrave; my friend was in the Third Church of Marika area where a scarab drops Sacred Blade and I was closer to the Bridge of Sacrifice (Closer to the Weeping Peninsula) while making my way to him. He killed the scarab and I did not get the skill.
