### ISSUE TITLE
Question about if it's possible to use this mod with randomizer mod together.

### ISSUE THREAD

**Issue by MisakaRua** [LukeYui/EldenRingSeamlessCoopRelease#9]
I'm wondering that will this mod conflicted with the randomizer mod? I can see that the bosses can be sycronized on the NexusMod web, but will the items in the world be sycronized during gaming? Thanks a lot if you can answer this question or give me a possible way to make these two mods work together.

**Comment by elenashen2010** [comment]
I've been using the two together and yea everything gets synced.

**Comment by MisakaRua** [comment]
您好，您发的邮件我已收到，我将稍后阅读。
