### ISSUE TITLE
[Bug]: Desyncing On Flying Dragon Agheel

### ISSUE THREAD

**Issue by saber57draxus** [LukeYui/EldenRingSeamlessCoopRelease#92]
### Discord Username

saber57draxus#7820

### Describe the issue in detail

On horseback fighting flying dragon agheel: can't see my party members unless on foot.  

game syncs in dungeons but in world i can't see them

### Steps to recreate the bug

i have no idea and sitting at the grace site fixes it [kind of] 

### Version

1.2.1 (Latest)

**Comment by Neofaucheur** [comment]
We encountered a similar bug. One of my coop partners (client) couldn't see either myself (host) or our other coop partner while we were on horseback, during and after fighting Agheel.
Not sure if that might be relevant, be we fought the Night Cavalry on the bridge nearby right before that, and their horse was left behind in a semi-undead state.

**Comment by brian8544** [comment]
Game crashes for me, but not my friend when engaging this boss. It happens after around ~1 minute, everytime.
