### ISSUE TITLE
[Bug]: Constant Disconnects on Version 1.2.1

### ISSUE THREAD

**Issue by ItzUmiii** [LukeYui/EldenRingSeamlessCoopRelease#93]
### Discord Username

Umi#2156

### Describe the issue in detail

After my friends and I updated to the newest version(changed the dll and even reinstalled the launcher), the two players that join the host will eventually disconnect. After restarting the session and our games many times, we decided to go back to version 1.1.0 and had no issues with anyone disconnecting. I don't know if this bit info would help, but when we were playing on 1.2.1 we only played in Caelid.

### Steps to recreate the bug

We had three people traversing through Caelid around the Caelem Ruins area. While traversing, the players that joined as wanderers would disconnect.

### Version

1.2.1 (Latest)

**Comment by HarryWang828** [comment]
same problem
