### ISSUE TITLE
[Bug]: Waypoints desync and cause crashes

### ISSUE THREAD

**Issue by Neofaucheur** [LukeYui/EldenRingSeamlessCoopRelease#94]
### Discord Username

Neofaucheur#3706

### Describe the issue in detail

Some waypoints are desynced. They may appear to all players, but under different numbers.

Removing them occasionally cause some players to crash. Presumably only ones that don't exist for every players', causing crash when sessions that are missing it attempt to remove it. It can happen either by removing it manually from the map, on walking through it during regular gameplay.
Might also happen when two players try to place a waypoint at the same time.

Usually crashes the game for some players, not everyone, and can affect host and clients.

### Steps to recreate the bug

I'll try to do more testing on the subject, but I suspect waypoint desync start happening when people with different existing waypoints join the same session. We're playing as a group of 3, so that maybe also happen specifically when the first two players starts placing waypoints and the 3rd player joins.

After that, either remove waypoints from the map or walk through them (the later seems to trigger it more often, but that might also be because we're just used to remove them like that after reaching our destination). The game usually freezes or crashes to desktop on a "bad" waypoint.

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment]
"Some waypoints are desynced. They may appear to all players, but under different numbers." - Is just how the waypoints are synced if you have previous waypoints. They still appear, they are just in a different order.

I'll look into the crash. It would have been helpful for a crash report though because I can't recreate this issue.

**Comment by Neofaucheur** [comment]
I was expecting to encounter it today while playing, to be able to provide one that I would be confident was related, but we didn't, possibly because we were more cautious around using waypoints. Here are my most recent crash reports related to Elden Ring, if that helps :
```
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000160895a1800
Faulting process ID: 0xfba4
Faulting application start time: 0x01d87cedfa3c7aee
Faulting application path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: unknown
Report ID: d7dc1272-f5ad-4909-baee-356135431549
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Exception code: 0xc0000005
Fault offset: 0x0000000000848d3d
Faulting process ID: 0xa45c
Faulting application start time: 0x01d87ceacc2e3adf
Faulting application path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Report ID: 772724dd-b628-46b6-8145-9f4e1fdf2723
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: crashhandler64.dll_unloaded, version: 7.30.20.28, time stamp: 0x629ec371
Exception code: 0xc0000005
Fault offset: 0x00000000000044d7
Faulting process ID: 0x43ec
Faulting application start time: 0x01d87c36a1362c2d
Faulting application path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: crashhandler64.dll
Report ID: 4183fe9e-3196-4d06-b660-403bed2c2b6b
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000001d7f2801800
Faulting process ID: 0xc2c4
Faulting application start time: 0x01d87b6e980625a6
Faulting application path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: unknown
Report ID: 41b548b2-d956-436b-a18d-6a1f07543dcc
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Faulting application name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Faulting module name: eldenring.exe, version: 1.4.1.0, time stamp: 0x625fce14
Exception code: 0xc0000005
Fault offset: 0x0000000000848d3d
Faulting process ID: 0xea34
Faulting application start time: 0x01d87b66d9d85150
Faulting application path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Report ID: a7bd8652-771a-4169-89cd-4902801a3058
Faulting package full name: 
Faulting package-relative application ID: 
```
I'll make sure to send a crash report I'm more confident is related if it happens again.

**Comment by Neofaucheur** [comment]
Here are two I know for sure happened to me when coop partners walked through a waypoint.
```
Faulting application name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Faulting module name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Exception code: 0xc0000005
Fault offset: 0x000000000084c50d
Faulting process ID: 0xc378
Faulting application start time: 0x01d881b2d6aa6c47
Faulting application path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Report ID: b7bb67a7-618b-4cdf-95cf-df65f2588023
Faulting package full name: 
Faulting package-relative application ID: 
```
```
Faulting application name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Faulting module name: eldenring.exe, version: 1.5.0.0, time stamp: 0x6295c83c
Exception code: 0xc0000005
Fault offset: 0x000000000084c50d
Faulting process ID: 0xff00
Faulting application start time: 0x01d881b555a9a8a2
Faulting application path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Faulting module path: N:\Game\SteamLibrary\steamapps\common\ELDEN RING\Game\eldenring.exe
Report ID: ec8b9ef2-558c-431d-95aa-9a3b7973c257
Faulting package full name: 
Faulting package-relative application ID: 
```
Playing on game version 1.05 with mod in 1.2.4

**Comment by LukeYui** [comment]
@Neofaucheur Thank you so much for the crash logs! I have identified the problem which seems to be the game trying to delete waypoint markers that have already been removed. I'll fix this for the next version.

**Comment by Himeki** [comment]
Just adding info I didn't see
Removing a waypoint while someone is hovering over it reliably crashes them as well, probably caused by the same or similar issue.
