### ISSUE TITLE
[Bug]: Falling out of Sky when joining another player and runes stuck in the sky

### ISSUE THREAD

**Issue by Irving-Delgad0** [LukeYui/EldenRingSeamlessCoopRelease#95]
### Discord Username

F0xMcC10ud

### Describe the issue in detail

When joining a player's session sometimes you spawn out in the sky and fall to your death, ive also noticed that on some occasions this causes your runes to drop on the spot you spawned way up in the sky making it impossible to get them

### Steps to recreate the bug

Join a players session as soon as you boot up the game, sometimes youll spawn in the sky and fall to your death 

### Version

1.2.1 (Latest)

**Comment by kagurazaki8472** [comment]
the same is happening for me (v1.2.0)

i joined from rykard grace to friends world in altis platue and spawned in sky.  rejoined again later and same thing happend.

![20220611155945_1](https://user-images.githubusercontent.com/14856729/173199892-defa34b8-1eb9-42af-a605-77205c8d4c2d.jpg)

**Comment by kagurazaki8472** [comment]
After a bit of testing, it seems to only happen when being summoned into altis platau
