### ISSUE TITLE
[Bug]: Rot not disapperaing  after resting at site of grace

### ISSUE THREAD

**Issue by SoapKnight** [LukeYui/EldenRingSeamlessCoopRelease#97]
### Discord Username

02likeslunchables#3643

### Describe the issue in detail

Rot stacks and does not disappear after resting at site of grace. No matter how many times i did it or restarted my game.

### Steps to recreate the bug

Die

### Version

1.2.1 (Latest)

**Comment by LukeYui** [comment]
Hi, thanks for the report.

Rot Essence can only be removed by resting at a site of grace whilst in a party. Did you try using the tiny great pot first, then resting?

**Comment by SoapKnight** [comment]
I used the separation mist

**Comment by LukeYui** [comment]
Try using the pot and resting again

**Comment by Ed-boye** [comment]
@SoapKnight also the rot essences are disabled in singleplayer fwiw even if you can't remove them without potting.

**Comment by LukeYui** [comment]
I'll make it so that rot can be removed outside of sessions to avoid confusion.

**Comment by SoapKnight** [comment]
Thank you. Your feedback was awesome im glad we have modders such as yourself
