### ISSUE TITLE
[Bug]:  ''Failed to find "SeamlessCoop//elden_ring_seamless_coop.dll"

### ISSUE THREAD

**Issue by AmbrosiaIsTaken** [LukeYui/EldenRingSeamlessCoopRelease#98]
### Discord Username

Ambrosia#2425

### Describe the issue in detail

Whenever i boot the mod i recieve an error message of "SeamlessCoop//elden_ring_seamless_coop.dll" and it proceeds to boot the orginal game. Ive followed all download instructions and files are in the right place. 

### Steps to recreate the bug

no clue, my friends havent had the same problem

### Version

1.2.1 (Latest)

**Comment by maguid28** [comment]
I also have the same issue.

**Comment by maguid28** [comment]
Alternatively you can also just create a shortcut in "C:\Program Files (x86)\Steam\steamapps\common\" to the location of your Elden Ring installation instead of moving it.

**Comment by abwesend890** [comment]
in my case a "&" in the path was causing this kind of error
